export interface City {
  name: string;
  slug: string;
  country: string;
  countrySlug: string;
  continent: 'europe' | 'asia' | 'north-america' | 'south-america' | 'africa' | 'oceania' | 'middle-east';
  studentPopulation: string;
  universityCount: number;
}

type CityTuple = [
  name: string,
  slug: string,
  country: string,
  countrySlug: string,
  continent: City['continent'],
  studentPopulation: string,
  universityCount: number,
];

const cityData: CityTuple[] = [
  // ── United Kingdom (32) ──────────────────────────────────────────
  ['London', 'london', 'United Kingdom', 'united-kingdom', 'europe', '400,000', 43],
  ['Manchester', 'manchester', 'United Kingdom', 'united-kingdom', 'europe', '100,000', 9],
  ['Birmingham', 'birmingham', 'United Kingdom', 'united-kingdom', 'europe', '80,000', 5],
  ['Leeds', 'leeds', 'United Kingdom', 'united-kingdom', 'europe', '70,000', 4],
  ['Sheffield', 'sheffield', 'United Kingdom', 'united-kingdom', 'europe', '65,000', 2],
  ['Bristol', 'bristol', 'United Kingdom', 'united-kingdom', 'europe', '60,000', 4],
  ['Nottingham', 'nottingham', 'United Kingdom', 'united-kingdom', 'europe', '60,000', 2],
  ['Liverpool', 'liverpool', 'United Kingdom', 'united-kingdom', 'europe', '55,000', 3],
  ['Newcastle upon Tyne', 'newcastle-upon-tyne', 'United Kingdom', 'united-kingdom', 'europe', '50,000', 2],
  ['Edinburgh', 'edinburgh', 'United Kingdom', 'united-kingdom', 'europe', '80,000', 4],
  ['Glasgow', 'glasgow', 'United Kingdom', 'united-kingdom', 'europe', '70,000', 3],
  ['Cardiff', 'cardiff', 'United Kingdom', 'united-kingdom', 'europe', '55,000', 3],
  ['Southampton', 'southampton', 'United Kingdom', 'united-kingdom', 'europe', '45,000', 2],
  ['Brighton', 'brighton', 'United Kingdom', 'united-kingdom', 'europe', '40,000', 2],
  ['Oxford', 'oxford', 'United Kingdom', 'united-kingdom', 'europe', '30,000', 2],
  ['Cambridge', 'cambridge', 'United Kingdom', 'united-kingdom', 'europe', '25,000', 2],
  ['Coventry', 'coventry', 'United Kingdom', 'united-kingdom', 'europe', '40,000', 3],
  ['Leicester', 'leicester', 'United Kingdom', 'united-kingdom', 'europe', '35,000', 2],
  ['Reading', 'reading', 'United Kingdom', 'united-kingdom', 'europe', '25,000', 1],
  ['York', 'york', 'United Kingdom', 'united-kingdom', 'europe', '20,000', 1],
  ['Exeter', 'exeter', 'United Kingdom', 'united-kingdom', 'europe', '22,000', 1],
  ['Bath', 'bath', 'United Kingdom', 'united-kingdom', 'europe', '15,000', 1],
  ['Durham', 'durham', 'United Kingdom', 'united-kingdom', 'europe', '20,000', 1],
  ['Aberdeen', 'aberdeen', 'United Kingdom', 'united-kingdom', 'europe', '30,000', 2],
  ['St Andrews', 'st-andrews', 'United Kingdom', 'united-kingdom', 'europe', '10,000', 1],
  ['Wolverhampton', 'wolverhampton', 'United Kingdom', 'united-kingdom', 'europe', '25,000', 1],
  ['Derby', 'derby', 'United Kingdom', 'united-kingdom', 'europe', '22,000', 1],
  ['Portsmouth', 'portsmouth', 'United Kingdom', 'united-kingdom', 'europe', '25,000', 2],
  ['Norwich', 'norwich', 'United Kingdom', 'united-kingdom', 'europe', '18,000', 1],
  ['Swansea', 'swansea', 'United Kingdom', 'united-kingdom', 'europe', '20,000', 2],
  ['Lancaster', 'lancaster', 'United Kingdom', 'united-kingdom', 'europe', '14,000', 1],
  ['Warwick', 'warwick', 'United Kingdom', 'united-kingdom', 'europe', '27,000', 1],

  // ── Germany (28) ─────────────────────────────────────────────────
  ['Berlin', 'berlin', 'Germany', 'germany', 'europe', '175,000', 4],
  ['Munich', 'munich', 'Germany', 'germany', 'europe', '130,000', 6],
  ['Hamburg', 'hamburg', 'Germany', 'germany', 'europe', '95,000', 6],
  ['Frankfurt', 'frankfurt', 'Germany', 'germany', 'europe', '75,000', 5],
  ['Cologne', 'cologne', 'Germany', 'germany', 'europe', '85,000', 4],
  ['Stuttgart', 'stuttgart', 'Germany', 'germany', 'europe', '65,000', 5],
  ['Heidelberg', 'heidelberg', 'Germany', 'germany', 'europe', '32,000', 2],
  ['Freiburg', 'freiburg', 'Germany', 'germany', 'europe', '32,000', 2],
  ['Tübingen', 'tubingen', 'Germany', 'germany', 'europe', '28,000', 1],
  ['Göttingen', 'gottingen', 'Germany', 'germany', 'europe', '32,000', 1],
  ['Bonn', 'bonn', 'Germany', 'germany', 'europe', '38,000', 2],
  ['Dresden', 'dresden', 'Germany', 'germany', 'europe', '42,000', 3],
  ['Leipzig', 'leipzig', 'Germany', 'germany', 'europe', '44,000', 3],
  ['Düsseldorf', 'dusseldorf', 'Germany', 'germany', 'europe', '55,000', 3],
  ['Bochum', 'bochum', 'Germany', 'germany', 'europe', '48,000', 2],
  ['Münster', 'munster', 'Germany', 'germany', 'europe', '52,000', 2],
  ['Aachen', 'aachen', 'Germany', 'germany', 'europe', '47,000', 2],
  ['Erlangen', 'erlangen', 'Germany', 'germany', 'europe', '32,000', 1],
  ['Jena', 'jena', 'Germany', 'germany', 'europe', '20,000', 2],
  ['Marburg', 'marburg', 'Germany', 'germany', 'europe', '18,000', 1],
  ['Karlsruhe', 'karlsruhe', 'Germany', 'germany', 'europe', '35,000', 2],
  ['Kiel', 'kiel', 'Germany', 'germany', 'europe', '28,000', 2],
  ['Mainz', 'mainz', 'Germany', 'germany', 'europe', '30,000', 2],
  ['Augsburg', 'augsburg', 'Germany', 'germany', 'europe', '22,000', 1],
  ['Nuremberg', 'nuremberg', 'Germany', 'germany', 'europe', '45,000', 3],
  ['Regensburg', 'regensburg', 'Germany', 'germany', 'europe', '22,000', 1],
  ['Wiesbaden', 'wiesbaden', 'Germany', 'germany', 'europe', '20,000', 1],
  ['Darmstadt', 'darmstadt', 'Germany', 'germany', 'europe', '30,000', 1],

  // ── France (25) ──────────────────────────────────────────────────
  ['Paris', 'paris', 'France', 'france', 'europe', '350,000', 17],
  ['Lyon', 'lyon', 'France', 'france', 'europe', '135,000', 5],
  ['Marseille', 'marseille', 'France', 'france', 'europe', '72,000', 3],
  ['Bordeaux', 'bordeaux', 'France', 'france', 'europe', '73,000', 4],
  ['Strasbourg', 'strasbourg', 'France', 'france', 'europe', '57,000', 3],
  ['Lille', 'lille', 'France', 'france', 'europe', '82,000', 4],
  ['Toulouse', 'toulouse', 'France', 'france', 'europe', '115,000', 4],
  ['Grenoble', 'grenoble', 'France', 'france', 'europe', '68,000', 3],
  ['Nantes', 'nantes', 'France', 'france', 'europe', '62,000', 3],
  ['Rennes', 'rennes', 'France', 'france', 'europe', '68,000', 3],
  ['Montpellier', 'montpellier', 'France', 'france', 'europe', '85,000', 4],
  ['Nice', 'nice', 'France', 'france', 'europe', '38,000', 1],
  ['Aix-en-Provence', 'aix-en-provence', 'France', 'france', 'europe', '48,000', 2],
  ['Caen', 'caen', 'France', 'france', 'europe', '32,000', 2],
  ['Poitiers', 'poitiers', 'France', 'france', 'europe', '30,000', 2],
  ['Clermont-Ferrand', 'clermont-ferrand', 'France', 'france', 'europe', '38,000', 2],
  ['Tours', 'tours', 'France', 'france', 'europe', '30,000', 2],
  ['Dijon', 'dijon', 'France', 'france', 'europe', '28,000', 2],
  ['Nancy', 'nancy', 'France', 'france', 'europe', '32,000', 2],
  ['Angers', 'angers', 'France', 'france', 'europe', '28,000', 2],
  ['Brest', 'brest', 'France', 'france', 'europe', '22,000', 1],
  ['Perpignan', 'perpignan', 'France', 'france', 'europe', '18,000', 1],
  ['Toulon', 'toulon', 'France', 'france', 'europe', '20,000', 1],
  ['Reims', 'reims', 'France', 'france', 'europe', '28,000', 2],
  ['Orléans', 'orleans', 'France', 'france', 'europe', '20,000', 2],

  // ── Netherlands (10) ─────────────────────────────────────────────
  ['Amsterdam', 'amsterdam', 'Netherlands', 'netherlands', 'europe', '70,000', 3],
  ['Rotterdam', 'rotterdam', 'Netherlands', 'netherlands', 'europe', '42,000', 2],
  ['Leiden', 'leiden', 'Netherlands', 'netherlands', 'europe', '28,000', 1],
  ['Utrecht', 'utrecht', 'Netherlands', 'netherlands', 'europe', '38,000', 1],
  ['Delft', 'delft', 'Netherlands', 'netherlands', 'europe', '27,000', 1],
  ['Eindhoven', 'eindhoven', 'Netherlands', 'netherlands', 'europe', '22,000', 1],
  ['Groningen', 'groningen', 'Netherlands', 'netherlands', 'europe', '32,000', 1],
  ['Tilburg', 'tilburg', 'Netherlands', 'netherlands', 'europe', '22,000', 1],
  ['Maastricht', 'maastricht', 'Netherlands', 'netherlands', 'europe', '20,000', 1],
  ['Nijmegen', 'nijmegen', 'Netherlands', 'netherlands', 'europe', '25,000', 1],

  // ── Italy (21) ───────────────────────────────────────────────────
  ['Rome', 'rome', 'Italy', 'italy', 'europe', '210,000', 11],
  ['Milan', 'milan', 'Italy', 'italy', 'europe', '185,000', 9],
  ['Bologna', 'bologna', 'Italy', 'italy', 'europe', '95,000', 2],
  ['Florence', 'florence', 'Italy', 'italy', 'europe', '65,000', 4],
  ['Turin', 'turin', 'Italy', 'italy', 'europe', '85,000', 4],
  ['Naples', 'naples', 'Italy', 'italy', 'europe', '108,000', 5],
  ['Padova', 'padova', 'Italy', 'italy', 'europe', '65,000', 2],
  ['Pisa', 'pisa', 'Italy', 'italy', 'europe', '52,000', 3],
  ['Venice', 'venice', 'Italy', 'italy', 'europe', '28,000', 2],
  ['Trento', 'trento', 'Italy', 'italy', 'europe', '20,000', 1],
  ['Perugia', 'perugia', 'Italy', 'italy', 'europe', '38,000', 3],
  ['Catania', 'catania', 'Italy', 'italy', 'europe', '52,000', 2],
  ['Genoa', 'genoa', 'Italy', 'italy', 'europe', '45,000', 2],
  ['Bari', 'bari', 'Italy', 'italy', 'europe', '48,000', 2],
  ['Palermo', 'palermo', 'Italy', 'italy', 'europe', '55,000', 2],
  ['Brescia', 'brescia', 'Italy', 'italy', 'europe', '25,000', 2],
  ['Verona', 'verona', 'Italy', 'italy', 'europe', '30,000', 1],
  ['Trieste', 'trieste', 'Italy', 'italy', 'europe', '25,000', 1],
  ['Ferrara', 'ferrara', 'Italy', 'italy', 'europe', '28,000', 1],
  ['Modena', 'modena', 'Italy', 'italy', 'europe', '22,000', 1],
  ['Parma', 'parma', 'Italy', 'italy', 'europe', '26,000', 1],

  // ── Spain (19) ───────────────────────────────────────────────────
  ['Madrid', 'madrid', 'Spain', 'spain', 'europe', '210,000', 7],
  ['Barcelona', 'barcelona', 'Spain', 'spain', 'europe', '165,000', 8],
  ['Valencia', 'valencia', 'Spain', 'spain', 'europe', '85,000', 5],
  ['Seville', 'seville', 'Spain', 'spain', 'europe', '72,000', 4],
  ['Bilbao', 'bilbao', 'Spain', 'spain', 'europe', '52,000', 3],
  ['Granada', 'granada', 'Spain', 'spain', 'europe', '58,000', 2],
  ['Salamanca', 'salamanca', 'Spain', 'spain', 'europe', '32,000', 2],
  ['Zaragoza', 'zaragoza', 'Spain', 'spain', 'europe', '38,000', 2],
  ['Pamplona', 'pamplona', 'Spain', 'spain', 'europe', '22,000', 1],
  ['Malaga', 'malaga', 'Spain', 'spain', 'europe', '42,000', 2],
  ['Murcia', 'murcia', 'Spain', 'spain', 'europe', '38,000', 2],
  ['Valladolid', 'valladolid', 'Spain', 'spain', 'europe', '28,000', 1],
  ['Alicante', 'alicante', 'Spain', 'spain', 'europe', '30,000', 1],
  ['Oviedo', 'oviedo', 'Spain', 'spain', 'europe', '25,000', 1],
  ['Santiago de Compostela', 'santiago-de-compostela', 'Spain', 'spain', 'europe', '28,000', 1],
  ['San Sebastián', 'san-sebastian', 'Spain', 'spain', 'europe', '20,000', 1],
  ['A Coruña', 'a-coruna', 'Spain', 'spain', 'europe', '22,000', 1],
  ['Lleida', 'lleida', 'Spain', 'spain', 'europe', '15,000', 1],
  ['Vigo', 'vigo', 'Spain', 'spain', 'europe', '22,000', 1],

  // ── Portugal (5) ─────────────────────────────────────────────────
  ['Lisbon', 'lisbon', 'Portugal', 'portugal', 'europe', '105,000', 5],
  ['Porto', 'porto', 'Portugal', 'portugal', 'europe', '65,000', 4],
  ['Coimbra', 'coimbra', 'Portugal', 'portugal', 'europe', '35,000', 2],
  ['Braga', 'braga', 'Portugal', 'portugal', 'europe', '25,000', 2],
  ['Aveiro', 'aveiro', 'Portugal', 'portugal', 'europe', '18,000', 1],

  // ── Belgium (5) ──────────────────────────────────────────────────
  ['Brussels', 'brussels', 'Belgium', 'belgium', 'europe', '90,000', 6],
  ['Ghent', 'ghent', 'Belgium', 'belgium', 'europe', '48,000', 3],
  ['Leuven', 'leuven', 'Belgium', 'belgium', 'europe', '55,000', 2],
  ['Liège', 'liege', 'Belgium', 'belgium', 'europe', '32,000', 2],
  ['Antwerp', 'antwerp', 'Belgium', 'belgium', 'europe', '42,000', 3],

  // ── Switzerland (8) ──────────────────────────────────────────────
  ['Zurich', 'zurich', 'Switzerland', 'switzerland', 'europe', '55,000', 3],
  ['Geneva', 'geneva', 'Switzerland', 'switzerland', 'europe', '38,000', 2],
  ['Lausanne', 'lausanne', 'Switzerland', 'switzerland', 'europe', '28,000', 2],
  ['Basel', 'basel', 'Switzerland', 'switzerland', 'europe', '22,000', 2],
  ['Bern', 'bern', 'Switzerland', 'switzerland', 'europe', '20,000', 1],
  ['Lucerne', 'lucerne', 'Switzerland', 'switzerland', 'europe', '12,000', 1],
  ['St. Gallen', 'st-gallen', 'Switzerland', 'switzerland', 'europe', '15,000', 1],
  ['Winterthur', 'winterthur', 'Switzerland', 'switzerland', 'europe', '10,000', 1],

  // ── Austria (5) ──────────────────────────────────────────────────
  ['Vienna', 'vienna', 'Austria', 'austria', 'europe', '185,000', 9],
  ['Graz', 'graz', 'Austria', 'austria', 'europe', '55,000', 4],
  ['Innsbruck', 'innsbruck', 'Austria', 'austria', 'europe', '35,000', 2],
  ['Linz', 'linz', 'Austria', 'austria', 'europe', '30,000', 3],
  ['Salzburg', 'salzburg', 'Austria', 'austria', 'europe', '25,000', 2],

  // ── Sweden (8) ───────────────────────────────────────────────────
  ['Stockholm', 'stockholm', 'Sweden', 'sweden', 'europe', '115,000', 5],
  ['Gothenburg', 'gothenburg', 'Sweden', 'sweden', 'europe', '60,000', 3],
  ['Uppsala', 'uppsala', 'Sweden', 'sweden', 'europe', '48,000', 1],
  ['Lund', 'lund', 'Sweden', 'sweden', 'europe', '42,000', 1],
  ['Linköping', 'linkoping', 'Sweden', 'sweden', 'europe', '30,000', 1],
  ['Malmö', 'malmo', 'Sweden', 'sweden', 'europe', '35,000', 2],
  ['Västerås', 'vasteras', 'Sweden', 'sweden', 'europe', '15,000', 1],
  ['Örebro', 'orebro', 'Sweden', 'sweden', 'europe', '18,000', 1],

  // ── Norway (5) ───────────────────────────────────────────────────
  ['Oslo', 'oslo', 'Norway', 'norway', 'europe', '70,000', 4],
  ['Bergen', 'bergen', 'Norway', 'norway', 'europe', '38,000', 2],
  ['Trondheim', 'trondheim', 'Norway', 'norway', 'europe', '42,000', 2],
  ['Stavanger', 'stavanger', 'Norway', 'norway', 'europe', '25,000', 1],
  ['Tromsø', 'tromso', 'Norway', 'norway', 'europe', '15,000', 1],

  // ── Denmark (4) ──────────────────────────────────────────────────
  ['Copenhagen', 'copenhagen', 'Denmark', 'denmark', 'europe', '85,000', 4],
  ['Aarhus', 'aarhus', 'Denmark', 'denmark', 'europe', '48,000', 2],
  ['Odense', 'odense', 'Denmark', 'denmark', 'europe', '28,000', 1],
  ['Aalborg', 'aalborg', 'Denmark', 'denmark', 'europe', '22,000', 1],

  // ── Finland (7) ──────────────────────────────────────────────────
  ['Helsinki', 'helsinki', 'Finland', 'finland', 'europe', '75,000', 5],
  ['Tampere', 'tampere', 'Finland', 'finland', 'europe', '32,000', 2],
  ['Turku', 'turku', 'Finland', 'finland', 'europe', '30,000', 3],
  ['Oulu', 'oulu', 'Finland', 'finland', 'europe', '22,000', 2],
  ['Espoo', 'espoo', 'Finland', 'finland', 'europe', '18,000', 1],
  ['Jyväskylä', 'jyvaskyla', 'Finland', 'finland', 'europe', '18,000', 1],
  ['Kuopio', 'kuopio', 'Finland', 'finland', 'europe', '15,000', 1],

  // ── Poland (11) ──────────────────────────────────────────────────
  ['Warsaw', 'warsaw', 'Poland', 'poland', 'europe', '250,000', 8],
  ['Krakow', 'krakow', 'Poland', 'poland', 'europe', '165,000', 9],
  ['Wroclaw', 'wroclaw', 'Poland', 'poland', 'europe', '130,000', 8],
  ['Poznan', 'poznan', 'Poland', 'poland', 'europe', '120,000', 7],
  ['Gdansk', 'gdansk', 'Poland', 'poland', 'europe', '85,000', 5],
  ['Lodz', 'lodz', 'Poland', 'poland', 'europe', '80,000', 5],
  ['Katowice', 'katowice', 'Poland', 'poland', 'europe', '70,000', 3],
  ['Lublin', 'lublin', 'Poland', 'poland', 'europe', '65,000', 4],
  ['Rzeszow', 'rzeszow', 'Poland', 'poland', 'europe', '40,000', 2],
  ['Szczecin', 'szczecin', 'Poland', 'poland', 'europe', '55,000', 3],
  ['Bialystok', 'bialystok', 'Poland', 'poland', 'europe', '45,000', 3],

  // ── Czech Republic (4) ───────────────────────────────────────────
  ['Prague', 'prague', 'Czech Republic', 'czech-republic', 'europe', '145,000', 8],
  ['Brno', 'brno', 'Czech Republic', 'czech-republic', 'europe', '75,000', 5],
  ['Olomouc', 'olomouc', 'Czech Republic', 'czech-republic', 'europe', '30,000', 2],
  ['Ostrava', 'ostrava', 'Czech Republic', 'czech-republic', 'europe', '42,000', 3],

  // ── Hungary (4) ──────────────────────────────────────────────────
  ['Budapest', 'budapest', 'Hungary', 'hungary', 'europe', '190,000', 8],
  ['Debrecen', 'debrecen', 'Hungary', 'hungary', 'europe', '45,000', 2],
  ['Pécs', 'pecs', 'Hungary', 'hungary', 'europe', '30,000', 2],
  ['Szeged', 'szeged', 'Hungary', 'hungary', 'europe', '28,000', 1],

  // ── Romania (5) ──────────────────────────────────────────────────
  ['Bucharest', 'bucharest', 'Romania', 'romania', 'europe', '165,000', 8],
  ['Cluj-Napoca', 'cluj-napoca', 'Romania', 'romania', 'europe', '80,000', 4],
  ['Timisoara', 'timisoara', 'Romania', 'romania', 'europe', '45,000', 3],
  ['Iasi', 'iasi', 'Romania', 'romania', 'europe', '55,000', 4],
  ['Craiova', 'craiova', 'Romania', 'romania', 'europe', '30,000', 2],

  // ── Greece (3) ───────────────────────────────────────────────────
  ['Athens', 'athens', 'Greece', 'greece', 'europe', '185,000', 8],
  ['Thessaloniki', 'thessaloniki', 'Greece', 'greece', 'europe', '95,000', 4],
  ['Patras', 'patras', 'Greece', 'greece', 'europe', '38,000', 1],

  // ── Turkey (3) ───────────────────────────────────────────────────
  ['Istanbul', 'istanbul', 'Turkey', 'turkey', 'europe', '450,000', 40],
  ['Ankara', 'ankara', 'Turkey', 'turkey', 'europe', '275,000', 15],
  ['Izmir', 'izmir', 'Turkey', 'turkey', 'europe', '135,000', 8],

  // ── Russia (4) ───────────────────────────────────────────────────
  ['Moscow', 'moscow', 'Russia', 'russia', 'europe', '850,000', 50],
  ['St. Petersburg', 'st-petersburg', 'Russia', 'russia', 'europe', '400,000', 25],
  ['Novosibirsk', 'novosibirsk', 'Russia', 'russia', 'europe', '120,000', 8],
  ['Yekaterinburg', 'yekaterinburg', 'Russia', 'russia', 'europe', '100,000', 6],

  // ── Ukraine (4) ──────────────────────────────────────────────────
  ['Kyiv', 'kyiv', 'Ukraine', 'ukraine', 'europe', '380,000', 15],
  ['Kharkiv', 'kharkiv', 'Ukraine', 'ukraine', 'europe', '200,000', 12],
  ['Lviv', 'lviv', 'Ukraine', 'ukraine', 'europe', '95,000', 6],
  ['Odessa', 'odessa', 'Ukraine', 'ukraine', 'europe', '80,000', 7],

  // ── Ireland (5) ──────────────────────────────────────────────────
  ['Dublin', 'dublin', 'Ireland', 'ireland', 'europe', '85,000', 7],
  ['Cork', 'cork', 'Ireland', 'ireland', 'europe', '32,000', 3],
  ['Galway', 'galway', 'Ireland', 'ireland', 'europe', '28,000', 2],
  ['Limerick', 'limerick', 'Ireland', 'ireland', 'europe', '18,000', 2],
  ['Waterford', 'waterford', 'Ireland', 'ireland', 'europe', '12,000', 1],

  // ── Other Europe (14) ────────────────────────────────────────────
  ['Belgrade', 'belgrade', 'Serbia', 'serbia', 'europe', '90,000', 8],
  ['Novi Sad', 'novi-sad', 'Serbia', 'serbia', 'europe', '35,000', 2],
  ['Zagreb', 'zagreb', 'Croatia', 'croatia', 'europe', '65,000', 5],
  ['Bratislava', 'bratislava', 'Slovakia', 'slovakia', 'europe', '55,000', 4],
  ['Sofia', 'sofia', 'Bulgaria', 'bulgaria', 'europe', '80,000', 5],
  ['Plovdiv', 'plovdiv', 'Bulgaria', 'bulgaria', 'europe', '28,000', 2],
  ['Vilnius', 'vilnius', 'Lithuania', 'lithuania', 'europe', '55,000', 5],
  ['Riga', 'riga', 'Latvia', 'latvia', 'europe', '38,000', 4],
  ['Tallinn', 'tallinn', 'Estonia', 'estonia', 'europe', '25,000', 3],
  ['Ljubljana', 'ljubljana', 'Slovenia', 'slovenia', 'europe', '28,000', 2],
  ['Sarajevo', 'sarajevo', 'Bosnia and Herzegovina', 'bosnia-and-herzegovina', 'europe', '35,000', 3],
  ['Skopje', 'skopje', 'North Macedonia', 'north-macedonia', 'europe', '45,000', 4],
  ['Tirana', 'tirana', 'Albania', 'albania', 'europe', '55,000', 5],
  ['Reykjavik', 'reykjavik', 'Iceland', 'iceland', 'europe', '22,000', 1],
  ['Nicosia', 'nicosia', 'Cyprus', 'cyprus', 'europe', '18,000', 2],
  ['Baku', 'baku', 'Azerbaijan', 'azerbaijan', 'europe', '75,000', 5],
  ['Tbilisi', 'tbilisi', 'Georgia', 'georgia', 'europe', '65,000', 5],
  ['Yerevan', 'yerevan', 'Armenia', 'armenia', 'europe', '55,000', 6],

  // ── India (30) ───────────────────────────────────────────────────
  ['Mumbai', 'mumbai', 'India', 'india', 'asia', '500,000', 15],
  ['Delhi', 'delhi', 'India', 'india', 'asia', '620,000', 20],
  ['Bangalore', 'bangalore', 'India', 'india', 'asia', '420,000', 12],
  ['Chennai', 'chennai', 'India', 'india', 'asia', '265,000', 15],
  ['Hyderabad', 'hyderabad', 'India', 'india', 'asia', '285,000', 12],
  ['Pune', 'pune', 'India', 'india', 'asia', '215,000', 10],
  ['Kolkata', 'kolkata', 'India', 'india', 'asia', '320,000', 14],
  ['Ahmedabad', 'ahmedabad', 'India', 'india', 'asia', '165,000', 8],
  ['Jaipur', 'jaipur', 'India', 'india', 'asia', '110,000', 6],
  ['Chandigarh', 'chandigarh', 'India', 'india', 'asia', '85,000', 5],
  ['Lucknow', 'lucknow', 'India', 'india', 'asia', '130,000', 7],
  ['Kochi', 'kochi', 'India', 'india', 'asia', '85,000', 5],
  ['Bhopal', 'bhopal', 'India', 'india', 'asia', '95,000', 5],
  ['Patna', 'patna', 'India', 'india', 'asia', '105,000', 6],
  ['Bhubaneswar', 'bhubaneswar', 'India', 'india', 'asia', '75,000', 5],
  ['Thiruvananthapuram', 'thiruvananthapuram', 'India', 'india', 'asia', '65,000', 4],
  ['Coimbatore', 'coimbatore', 'India', 'india', 'asia', '85,000', 5],
  ['Nagpur', 'nagpur', 'India', 'india', 'asia', '85,000', 5],
  ['Vadodara', 'vadodara', 'India', 'india', 'asia', '75,000', 4],
  ['Surat', 'surat', 'India', 'india', 'asia', '65,000', 3],
  ['Allahabad', 'allahabad', 'India', 'india', 'asia', '95,000', 5],
  ['Varanasi', 'varanasi', 'India', 'india', 'asia', '80,000', 4],
  ['Mysore', 'mysore', 'India', 'india', 'asia', '55,000', 4],
  ['Visakhapatnam', 'visakhapatnam', 'India', 'india', 'asia', '70,000', 4],
  ['Indore', 'indore', 'India', 'india', 'asia', '75,000', 4],
  ['Amritsar', 'amritsar', 'India', 'india', 'asia', '50,000', 3],
  ['Rajkot', 'rajkot', 'India', 'india', 'asia', '45,000', 2],
  ['Ranchi', 'ranchi', 'India', 'india', 'asia', '60,000', 4],
  ['Guwahati', 'guwahati', 'India', 'india', 'asia', '55,000', 4],
  ['Dehradun', 'dehradun', 'India', 'india', 'asia', '45,000', 3],

  // ── Japan (16) ───────────────────────────────────────────────────
  ['Tokyo', 'tokyo', 'Japan', 'japan', 'asia', '820,000', 100],
  ['Kyoto', 'kyoto', 'Japan', 'japan', 'asia', '155,000', 37],
  ['Osaka', 'osaka', 'Japan', 'japan', 'asia', '260,000', 50],
  ['Nagoya', 'nagoya', 'Japan', 'japan', 'asia', '165,000', 15],
  ['Fukuoka', 'fukuoka', 'Japan', 'japan', 'asia', '105,000', 15],
  ['Sapporo', 'sapporo', 'Japan', 'japan', 'asia', '85,000', 8],
  ['Sendai', 'sendai', 'Japan', 'japan', 'asia', '75,000', 8],
  ['Kobe', 'kobe', 'Japan', 'japan', 'asia', '65,000', 10],
  ['Yokohama', 'yokohama', 'Japan', 'japan', 'asia', '115,000', 10],
  ['Hiroshima', 'hiroshima', 'Japan', 'japan', 'asia', '55,000', 8],
  ['Nagasaki', 'nagasaki', 'Japan', 'japan', 'asia', '30,000', 4],
  ['Kumamoto', 'kumamoto', 'Japan', 'japan', 'asia', '38,000', 5],
  ['Okayama', 'okayama', 'Japan', 'japan', 'asia', '32,000', 4],
  ['Kanazawa', 'kanazawa', 'Japan', 'japan', 'asia', '28,000', 2],
  ['Hamamatsu', 'hamamatsu', 'Japan', 'japan', 'asia', '25,000', 2],
  ['Naha', 'naha', 'Japan', 'japan', 'asia', '18,000', 2],

  // ── South Korea (8) ──────────────────────────────────────────────
  ['Seoul', 'seoul', 'South Korea', 'south-korea', 'asia', '525,000', 30],
  ['Busan', 'busan', 'South Korea', 'south-korea', 'asia', '165,000', 8],
  ['Daejeon', 'daejeon', 'South Korea', 'south-korea', 'asia', '110,000', 5],
  ['Incheon', 'incheon', 'South Korea', 'south-korea', 'asia', '85,000', 3],
  ['Gwangju', 'gwangju', 'South Korea', 'south-korea', 'asia', '75,000', 4],
  ['Daegu', 'daegu', 'South Korea', 'south-korea', 'asia', '95,000', 5],
  ['Suwon', 'suwon', 'South Korea', 'south-korea', 'asia', '65,000', 3],
  ['Ulsan', 'ulsan', 'South Korea', 'south-korea', 'asia', '55,000', 3],

  // ── China (20) ───────────────────────────────────────────────────
  ['Beijing', 'beijing', 'China', 'china', 'asia', '850,000', 92],
  ['Shanghai', 'shanghai', 'China', 'china', 'asia', '735,000', 68],
  ['Guangzhou', 'guangzhou', 'China', 'china', 'asia', '430,000', 30],
  ['Wuhan', 'wuhan', 'China', 'china', 'asia', '370,000', 50],
  ['Nanjing', 'nanjing', 'China', 'china', 'asia', '320,000', 30],
  ['Chengdu', 'chengdu', 'China', 'china', 'asia', '295,000', 25],
  ['Tianjin', 'tianjin', 'China', 'china', 'asia', '265,000', 55],
  ['Hangzhou', 'hangzhou', 'China', 'china', 'asia', '215,000', 15],
  ['Shenzhen', 'shenzhen', 'China', 'china', 'asia', '195,000', 12],
  ["Xi'an", 'xian', 'China', 'china', 'asia', '265,000', 50],
  ['Harbin', 'harbin', 'China', 'china', 'asia', '175,000', 35],
  ['Dalian', 'dalian', 'China', 'china', 'asia', '145,000', 15],
  ['Changsha', 'changsha', 'China', 'china', 'asia', '200,000', 20],
  ['Hefei', 'hefei', 'China', 'china', 'asia', '185,000', 15],
  ['Xiamen', 'xiamen', 'China', 'china', 'asia', '120,000', 8],
  ['Qingdao', 'qingdao', 'China', 'china', 'asia', '160,000', 12],
  ['Kunming', 'kunming', 'China', 'china', 'asia', '145,000', 15],
  ['Chongqing', 'chongqing', 'China', 'china', 'asia', '310,000', 30],
  ['Nanchang', 'nanchang', 'China', 'china', 'asia', '130,000', 10],
  ['Fuzhou', 'fuzhou', 'China', 'china', 'asia', '115,000', 8],

  // ── Southeast Asia (24) ──────────────────────────────────────────
  ['Singapore', 'singapore', 'Singapore', 'singapore', 'asia', '80,000', 6],
  ['Hong Kong', 'hong-kong', 'Hong Kong', 'hong-kong', 'asia', '135,000', 8],
  ['Bangkok', 'bangkok', 'Thailand', 'thailand', 'asia', '265,000', 20],
  ['Chiang Mai', 'chiang-mai', 'Thailand', 'thailand', 'asia', '55,000', 7],
  ['Kuala Lumpur', 'kuala-lumpur', 'Malaysia', 'malaysia', 'asia', '165,000', 15],
  ['Penang', 'penang', 'Malaysia', 'malaysia', 'asia', '45,000', 5],
  ['Johor Bahru', 'johor-bahru', 'Malaysia', 'malaysia', 'asia', '35,000', 3],
  ['Manila', 'manila', 'Philippines', 'philippines', 'asia', '215,000', 30],
  ['Cebu', 'cebu', 'Philippines', 'philippines', 'asia', '85,000', 12],
  ['Davao', 'davao', 'Philippines', 'philippines', 'asia', '55,000', 8],
  ['Jakarta', 'jakarta', 'Indonesia', 'indonesia', 'asia', '320,000', 20],
  ['Surabaya', 'surabaya', 'Indonesia', 'indonesia', 'asia', '120,000', 8],
  ['Bandung', 'bandung', 'Indonesia', 'indonesia', 'asia', '95,000', 6],
  ['Yogyakarta', 'yogyakarta', 'Indonesia', 'indonesia', 'asia', '65,000', 5],
  ['Ho Chi Minh City', 'ho-chi-minh-city', 'Vietnam', 'vietnam', 'asia', '215,000', 20],
  ['Hanoi', 'hanoi', 'Vietnam', 'vietnam', 'asia', '195,000', 18],
  ['Da Nang', 'da-nang', 'Vietnam', 'vietnam', 'asia', '45,000', 5],
  ['Taipei', 'taipei', 'Taiwan', 'taiwan', 'asia', '215,000', 20],
  ['Kaohsiung', 'kaohsiung', 'Taiwan', 'taiwan', 'asia', '85,000', 6],
  ['Taichung', 'taichung', 'Taiwan', 'taiwan', 'asia', '75,000', 5],
  ['Yangon', 'yangon', 'Myanmar', 'myanmar', 'asia', '95,000', 6],
  ['Colombo', 'colombo', 'Sri Lanka', 'sri-lanka', 'asia', '55,000', 10],
  ['Phnom Penh', 'phnom-penh', 'Cambodia', 'cambodia', 'asia', '55,000', 8],
  ['Vientiane', 'vientiane', 'Laos', 'laos', 'asia', '25,000', 3],

  // ── South Asia (non-India) (6) ────────────────────────────────────
  ['Dhaka', 'dhaka', 'Bangladesh', 'bangladesh', 'asia', '250,000', 15],
  ['Chittagong', 'chittagong', 'Bangladesh', 'bangladesh', 'asia', '85,000', 5],
  ['Karachi', 'karachi', 'Pakistan', 'pakistan', 'asia', '280,000', 20],
  ['Lahore', 'lahore', 'Pakistan', 'pakistan', 'asia', '215,000', 18],
  ['Islamabad', 'islamabad', 'Pakistan', 'pakistan', 'asia', '85,000', 8],
  ['Kathmandu', 'kathmandu', 'Nepal', 'nepal', 'asia', '65,000', 8],

  // ── Central Asia (3) ─────────────────────────────────────────────
  ['Almaty', 'almaty', 'Kazakhstan', 'kazakhstan', 'asia', '85,000', 8],
  ['Nur-Sultan', 'nur-sultan', 'Kazakhstan', 'kazakhstan', 'asia', '55,000', 5],
  ['Tashkent', 'tashkent', 'Uzbekistan', 'uzbekistan', 'asia', '95,000', 10],

  // ── Middle East (15) ─────────────────────────────────────────────
  ['Dubai', 'dubai', 'United Arab Emirates', 'united-arab-emirates', 'middle-east', '55,000', 5],
  ['Abu Dhabi', 'abu-dhabi', 'United Arab Emirates', 'united-arab-emirates', 'middle-east', '38,000', 4],
  ['Riyadh', 'riyadh', 'Saudi Arabia', 'saudi-arabia', 'middle-east', '115,000', 10],
  ['Jeddah', 'jeddah', 'Saudi Arabia', 'saudi-arabia', 'middle-east', '85,000', 6],
  ['Beirut', 'beirut', 'Lebanon', 'lebanon', 'middle-east', '85,000', 8],
  ['Tel Aviv', 'tel-aviv', 'Israel', 'israel', 'middle-east', '120,000', 6],
  ['Jerusalem', 'jerusalem', 'Israel', 'israel', 'middle-east', '55,000', 4],
  ['Amman', 'amman', 'Jordan', 'jordan', 'middle-east', '65,000', 5],
  ['Doha', 'doha', 'Qatar', 'qatar', 'middle-east', '35,000', 3],
  ['Kuwait City', 'kuwait-city', 'Kuwait', 'kuwait', 'middle-east', '28,000', 4],
  ['Tehran', 'tehran', 'Iran', 'iran', 'middle-east', '355,000', 25],
  ['Muscat', 'muscat', 'Oman', 'oman', 'middle-east', '25,000', 4],
  ['Baghdad', 'baghdad', 'Iraq', 'iraq', 'middle-east', '185,000', 10],
  ['Damascus', 'damascus', 'Syria', 'syria', 'middle-east', '95,000', 5],
  ['Sharjah', 'sharjah', 'United Arab Emirates', 'united-arab-emirates', 'middle-east', '20,000', 2],

  // ── Canada (25) ──────────────────────────────────────────────────
  ['Toronto', 'toronto', 'Canada', 'canada', 'north-america', '215,000', 4],
  ['Vancouver', 'vancouver', 'Canada', 'canada', 'north-america', '135,000', 3],
  ['Montreal', 'montreal', 'Canada', 'canada', 'north-america', '165,000', 4],
  ['Ottawa', 'ottawa', 'Canada', 'canada', 'north-america', '58,000', 3],
  ['Calgary', 'calgary', 'Canada', 'canada', 'north-america', '65,000', 2],
  ['Edmonton', 'edmonton', 'Canada', 'canada', 'north-america', '60,000', 2],
  ['Winnipeg', 'winnipeg', 'Canada', 'canada', 'north-america', '38,000', 3],
  ['Halifax', 'halifax', 'Canada', 'canada', 'north-america', '32,000', 4],
  ['Quebec City', 'quebec-city', 'Canada', 'canada', 'north-america', '58,000', 4],
  ['Victoria', 'victoria', 'Canada', 'canada', 'north-america', '28,000', 2],
  ['Waterloo', 'waterloo', 'Canada', 'canada', 'north-america', '38,000', 2],
  ['Kingston', 'kingston', 'Canada', 'canada', 'north-america', '28,000', 2],
  ['London Ontario', 'london-ontario', 'Canada', 'canada', 'north-america', '38,000', 2],
  ['Hamilton', 'hamilton-ontario', 'Canada', 'canada', 'north-america', '35,000', 2],
  ['Saskatoon', 'saskatoon', 'Canada', 'canada', 'north-america', '28,000', 2],
  ['Regina', 'regina', 'Canada', 'canada', 'north-america', '18,000', 2],
  ['Fredericton', 'fredericton', 'Canada', 'canada', 'north-america', '14,000', 2],
  ['Charlottetown', 'charlottetown', 'Canada', 'canada', 'north-america', '9,000', 1],
  ['Sudbury', 'sudbury', 'Canada', 'canada', 'north-america', '12,000', 1],
  ['Thunder Bay', 'thunder-bay', 'Canada', 'canada', 'north-america', '9,000', 1],
  ['Kelowna', 'kelowna', 'Canada', 'canada', 'north-america', '18,000', 1],
  ['Lethbridge', 'lethbridge', 'Canada', 'canada', 'north-america', '12,000', 1],
  ['Barrie', 'barrie', 'Canada', 'canada', 'north-america', '10,000', 1],
  ['Moncton', 'moncton', 'Canada', 'canada', 'north-america', '12,000', 1],
  ["St. John's", 'st-johns', 'Canada', 'canada', 'north-america', '18,000', 1],

  // ── Mexico (5) ───────────────────────────────────────────────────
  ['Mexico City', 'mexico-city', 'Mexico', 'mexico', 'north-america', '520,000', 40],
  ['Guadalajara', 'guadalajara', 'Mexico', 'mexico', 'north-america', '215,000', 10],
  ['Monterrey', 'monterrey', 'Mexico', 'mexico', 'north-america', '195,000', 8],
  ['Puebla', 'puebla', 'Mexico', 'mexico', 'north-america', '120,000', 6],
  ['Tijuana', 'tijuana', 'Mexico', 'mexico', 'north-america', '65,000', 4],

  // ── Caribbean & Central America (10) ─────────────────────────────
  ['Havana', 'havana', 'Cuba', 'cuba', 'north-america', '95,000', 5],
  ['Santo Domingo', 'santo-domingo', 'Dominican Republic', 'dominican-republic', 'north-america', '85,000', 7],
  ['San Juan', 'san-juan', 'Puerto Rico', 'puerto-rico', 'north-america', '75,000', 5],
  ['San José', 'san-jose-cr', 'Costa Rica', 'costa-rica', 'north-america', '65,000', 5],
  ['Guatemala City', 'guatemala-city', 'Guatemala', 'guatemala', 'north-america', '95,000', 8],
  ['Panama City', 'panama-city', 'Panama', 'panama', 'north-america', '55,000', 5],
  ['Kingston', 'kingston-jamaica', 'Jamaica', 'jamaica', 'north-america', '35,000', 2],
  ['San Salvador', 'san-salvador', 'El Salvador', 'el-salvador', 'north-america', '25,000', 5],
  ['Tegucigalpa', 'tegucigalpa', 'Honduras', 'honduras', 'north-america', '45,000', 5],
  ['Managua', 'managua', 'Nicaragua', 'nicaragua', 'north-america', '35,000', 4],

  // ── Brazil (12) ──────────────────────────────────────────────────
  ['São Paulo', 'sao-paulo', 'Brazil', 'brazil', 'south-america', '850,000', 30],
  ['Rio de Janeiro', 'rio-de-janeiro', 'Brazil', 'brazil', 'south-america', '420,000', 15],
  ['Brasília', 'brasilia', 'Brazil', 'brazil', 'south-america', '165,000', 8],
  ['Belo Horizonte', 'belo-horizonte', 'Brazil', 'brazil', 'south-america', '165,000', 10],
  ['Curitiba', 'curitiba', 'Brazil', 'brazil', 'south-america', '165,000', 8],
  ['Porto Alegre', 'porto-alegre', 'Brazil', 'brazil', 'south-america', '165,000', 10],
  ['Fortaleza', 'fortaleza', 'Brazil', 'brazil', 'south-america', '145,000', 8],
  ['Recife', 'recife', 'Brazil', 'brazil', 'south-america', '135,000', 8],
  ['Salvador', 'salvador', 'Brazil', 'brazil', 'south-america', '125,000', 7],
  ['Manaus', 'manaus', 'Brazil', 'brazil', 'south-america', '75,000', 4],
  ['Florianópolis', 'florianopolis', 'Brazil', 'brazil', 'south-america', '65,000', 4],
  ['Goiânia', 'goiania', 'Brazil', 'brazil', 'south-america', '75,000', 5],

  // ── Argentina (5) ────────────────────────────────────────────────
  ['Buenos Aires', 'buenos-aires', 'Argentina', 'argentina', 'south-america', '425,000', 8],
  ['Córdoba', 'cordoba-argentina', 'Argentina', 'argentina', 'south-america', '175,000', 6],
  ['Rosario', 'rosario', 'Argentina', 'argentina', 'south-america', '95,000', 4],
  ['Mendoza', 'mendoza', 'Argentina', 'argentina', 'south-america', '55,000', 3],
  ['Tucumán', 'tucuman', 'Argentina', 'argentina', 'south-america', '50,000', 3],

  // ── Colombia (3) ─────────────────────────────────────────────────
  ['Bogotá', 'bogota', 'Colombia', 'colombia', 'south-america', '320,000', 20],
  ['Medellín', 'medellin', 'Colombia', 'colombia', 'south-america', '165,000', 8],
  ['Cali', 'cali', 'Colombia', 'colombia', 'south-america', '125,000', 6],

  // ── Chile (3) ────────────────────────────────────────────────────
  ['Santiago', 'santiago', 'Chile', 'chile', 'south-america', '265,000', 15],
  ['Valparaíso', 'valparaiso', 'Chile', 'chile', 'south-america', '65,000', 4],
  ['Concepción', 'concepcion', 'Chile', 'chile', 'south-america', '55,000', 4],

  // ── Peru (3) ─────────────────────────────────────────────────────
  ['Lima', 'lima', 'Peru', 'peru', 'south-america', '265,000', 15],
  ['Arequipa', 'arequipa', 'Peru', 'peru', 'south-america', '55,000', 4],
  ['Trujillo', 'trujillo', 'Peru', 'peru', 'south-america', '45,000', 4],

  // ── Rest of South America (9) ─────────────────────────────────────
  ['Caracas', 'caracas', 'Venezuela', 'venezuela', 'south-america', '165,000', 10],
  ['Maracaibo', 'maracaibo', 'Venezuela', 'venezuela', 'south-america', '75,000', 4],
  ['Quito', 'quito', 'Ecuador', 'ecuador', 'south-america', '135,000', 10],
  ['Guayaquil', 'guayaquil', 'Ecuador', 'ecuador', 'south-america', '95,000', 6],
  ['Montevideo', 'montevideo', 'Uruguay', 'uruguay', 'south-america', '85,000', 4],
  ['La Paz', 'la-paz', 'Bolivia', 'bolivia', 'south-america', '95,000', 5],
  ['Santa Cruz de la Sierra', 'santa-cruz', 'Bolivia', 'bolivia', 'south-america', '65,000', 4],
  ['Asuncion', 'asuncion', 'Paraguay', 'paraguay', 'south-america', '65,000', 4],
  ['Barranquilla', 'barranquilla', 'Colombia', 'colombia', 'south-america', '85,000', 5],

  // ── Africa (25) ──────────────────────────────────────────────────
  ['Cairo', 'cairo', 'Egypt', 'egypt', 'africa', '320,000', 20],
  ['Alexandria', 'alexandria', 'Egypt', 'egypt', 'africa', '105,000', 7],
  ['Cape Town', 'cape-town', 'South Africa', 'south-africa', 'africa', '115,000', 5],
  ['Johannesburg', 'johannesburg', 'South Africa', 'south-africa', 'africa', '165,000', 7],
  ['Durban', 'durban', 'South Africa', 'south-africa', 'africa', '75,000', 4],
  ['Nairobi', 'nairobi', 'Kenya', 'kenya', 'africa', '88,000', 5],
  ['Mombasa', 'mombasa', 'Kenya', 'kenya', 'africa', '28,000', 2],
  ['Lagos', 'lagos', 'Nigeria', 'nigeria', 'africa', '215,000', 10],
  ['Ibadan', 'ibadan', 'Nigeria', 'nigeria', 'africa', '85,000', 4],
  ['Accra', 'accra', 'Ghana', 'ghana', 'africa', '65,000', 5],
  ['Kumasi', 'kumasi', 'Ghana', 'ghana', 'africa', '40,000', 3],
  ['Addis Ababa', 'addis-ababa', 'Ethiopia', 'ethiopia', 'africa', '88,000', 5],
  ['Dar es Salaam', 'dar-es-salaam', 'Tanzania', 'tanzania', 'africa', '55,000', 4],
  ['Kampala', 'kampala', 'Uganda', 'uganda', 'africa', '48,000', 5],
  ['Lusaka', 'lusaka', 'Zambia', 'zambia', 'africa', '35,000', 3],
  ['Harare', 'harare', 'Zimbabwe', 'zimbabwe', 'africa', '38,000', 4],
  ['Kigali', 'kigali', 'Rwanda', 'rwanda', 'africa', '28,000', 3],
  ['Casablanca', 'casablanca', 'Morocco', 'morocco', 'africa', '85,000', 6],
  ['Tunis', 'tunis', 'Tunisia', 'tunisia', 'africa', '95,000', 8],
  ['Dakar', 'dakar', 'Senegal', 'senegal', 'africa', '55,000', 5],
  ['Kinshasa', 'kinshasa', 'DR Congo', 'dr-congo', 'africa', '95,000', 5],
  ['Khartoum', 'khartoum', 'Sudan', 'sudan', 'africa', '75,000', 5],
  ['Abidjan', 'abidjan', 'Ivory Coast', 'ivory-coast', 'africa', '55,000', 4],
  ['Maputo', 'maputo', 'Mozambique', 'mozambique', 'africa', '38,000', 3],
  ['Windhoek', 'windhoek', 'Namibia', 'namibia', 'africa', '22,000', 2],

  // ── Australia (18) ───────────────────────────────────────────────
  ['Sydney', 'sydney', 'Australia', 'australia', 'oceania', '215,000', 6],
  ['Melbourne', 'melbourne', 'Australia', 'australia', 'oceania', '195,000', 7],
  ['Brisbane', 'brisbane', 'Australia', 'australia', 'oceania', '115,000', 4],
  ['Perth', 'perth', 'Australia', 'australia', 'oceania', '88,000', 4],
  ['Adelaide', 'adelaide', 'Australia', 'australia', 'oceania', '60,000', 5],
  ['Canberra', 'canberra', 'Australia', 'australia', 'oceania', '32,000', 2],
  ['Newcastle', 'newcastle-nsw', 'Australia', 'australia', 'oceania', '28,000', 2],
  ['Wollongong', 'wollongong', 'Australia', 'australia', 'oceania', '22,000', 1],
  ['Gold Coast', 'gold-coast', 'Australia', 'australia', 'oceania', '45,000', 3],
  ['Sunshine Coast', 'sunshine-coast', 'Australia', 'australia', 'oceania', '18,000', 1],
  ['Hobart', 'hobart', 'Australia', 'australia', 'oceania', '20,000', 1],
  ['Darwin', 'darwin', 'Australia', 'australia', 'oceania', '9,000', 1],
  ['Geelong', 'geelong', 'Australia', 'australia', 'oceania', '18,000', 1],
  ['Townsville', 'townsville', 'Australia', 'australia', 'oceania', '14,000', 1],
  ['Cairns', 'cairns', 'Australia', 'australia', 'oceania', '9,000', 1],
  ['Ballarat', 'ballarat', 'Australia', 'australia', 'oceania', '12,000', 1],
  ['Toowoomba', 'toowoomba', 'Australia', 'australia', 'oceania', '10,000', 1],
  ['Albury', 'albury', 'Australia', 'australia', 'oceania', '8,000', 1],

  // ── New Zealand (8) ──────────────────────────────────────────────
  ['Auckland', 'auckland', 'New Zealand', 'new-zealand', 'oceania', '75,000', 5],
  ['Wellington', 'wellington', 'New Zealand', 'new-zealand', 'oceania', '38,000', 3],
  ['Christchurch', 'christchurch', 'New Zealand', 'new-zealand', 'oceania', '28,000', 2],
  ['Dunedin', 'dunedin', 'New Zealand', 'new-zealand', 'oceania', '22,000', 2],
  ['Hamilton', 'hamilton-nz', 'New Zealand', 'new-zealand', 'oceania', '20,000', 1],
  ['Palmerston North', 'palmerston-north', 'New Zealand', 'new-zealand', 'oceania', '14,000', 1],
  ['Tauranga', 'tauranga', 'New Zealand', 'new-zealand', 'oceania', '12,000', 1],
  ['Napier', 'napier', 'New Zealand', 'new-zealand', 'oceania', '8,000', 1],
];

export const cities: City[] = cityData.map(
  ([name, slug, country, countrySlug, continent, studentPopulation, universityCount]) => ({
    name,
    slug,
    country,
    countrySlug,
    continent,
    studentPopulation,
    universityCount,
  }),
);

export function getCityBySlug(slug: string): City | undefined {
  return cities.find((c) => c.slug === slug);
}

export function getAllCitySlugs(): { city: string }[] {
  return cities.map((c) => ({ city: c.slug }));
}

export function getCitiesByCountry(countrySlug: string): City[] {
  return cities.filter((c) => c.countrySlug === countrySlug);
}

export function getCitiesByContinent(continent: string): City[] {
  return cities.filter((c) => c.continent === continent);
}
