export interface Competitor {
  name: string;
  slug: string;
  url: string;
  tagline: string;
  targetAudience: "teachers" | "students" | "both" | "general";
  pricing: {
    free: boolean;
    monthlyPrice: number | null;
    annualPrice: number | null;
    enterprise: boolean;
    notes?: string;
  };
  strengths: string[];
  weaknesses: string[];
  syllioDifference: string[];
}

export const competitors: Competitor[] = [
  {
    name: "MagicSchool AI",
    slug: "magicschool-ai",
    url: "https://www.magicschool.ai",
    tagline: "AI tools for teachers — lesson plans, rubrics, and more at scale",
    targetAudience: "teachers",
    pricing: {
      free: true,
      monthlyPrice: 12.99,
      annualPrice: 8.33,
      enterprise: true,
      notes: "$8.33/mo billed annually; $12.99/mo billed monthly; school and district plans available",
    },
    strengths: [
      "80+ AI tools for teachers covering lesson plans, rubrics, IEP drafts, email templates, and more",
      "Massive traction: 7 million+ users across 13,000+ schools",
      "Strong brand awareness in the K-12 teacher community",
      "Free tier allows meaningful use before upgrading",
      "Active community and regular feature releases",
      "Raina AI chatbot for personalized educator support",
    ],
    weaknesses: [
      "Zero student-facing features — students cannot use the platform at all",
      "No syllabus scanning or deadline extraction for students",
      "No calendar integration or academic OS for students",
      "No club management, portfolio, or extracurricular tracking",
      "Heavily US-centric with limited international curriculum support",
      "No LMS sync for pulling student data — output only, not bidirectional",
      "Teacher workflow ends when content is created — no student engagement loop",
    ],
    syllioDifference: [
      "Syllio serves both sides of the classroom — teachers build syllabi; students auto-import them",
      "Syllio's Burnout Radar™ gives students predictive load alerts MagicSchool cannot provide",
      "Syllio's Club OS manages student organizations — a gap MagicSchool has never addressed",
      "Syllio creates a closed loop: teacher creates → student scans → deadlines auto-populate",
      "Syllio's 4-year portfolio gives students a career artifact; MagicSchool creates no student output",
      "Syllio's Teacher + Student Bundle ($14.99/mo) delivers more value than MagicSchool's teacher-only plan",
    ],
  },
  {
    name: "Semora",
    slug: "semora",
    url: "https://www.semora.app",
    tagline: "Scan your syllabus, never miss a deadline",
    targetAudience: "students",
    pricing: {
      free: false,
      monthlyPrice: 3.99,
      annualPrice: 19.99,
      enterprise: false,
      notes: "$3.99/mo or $19.99/yr; no free tier",
    },
    strengths: [
      "Very affordable pricing — one of the lowest-cost syllabus tools available",
      "Core syllabus scanning feature is fast and easy to use",
      "Clean, focused iOS app experience",
      "Students can quickly capture deadlines from a photo of their syllabus",
    ],
    weaknesses: [
      "iOS only — Android and web users are completely excluded",
      "No teacher-facing tools whatsoever",
      "No club management, organization tracking, or extracurricular features",
      "No LMS integration with Canvas, Blackboard, or Google Classroom",
      "No predictive workload management or burnout alerts",
      "No portfolio or long-term academic planning features",
      "Very narrow feature set — scanning is the entire product",
      "No teacher-side sharing or class code system",
    ],
    syllioDifference: [
      "Syllio is cross-platform (iOS, Android, web PWA) — no student is excluded",
      "Syllio includes teacher tools so the scan has context: teacher creates, student imports",
      "Syllio's Burnout Radar™ predicts overload weeks — Semora just captures dates",
      "Syllio's Club OS is a complete student organization management suite Semora has no answer to",
      "Syllio's OS Student plan includes a 4-year portfolio and career milestone tracking",
      "Syllio's LMS sync (Canvas, Blackboard, Google Classroom) eliminates manual syllabus upload",
    ],
  },
  {
    name: "TeachQuill",
    slug: "teachquill",
    url: "https://www.teachquill.com",
    tagline: "AI-powered lesson planning and resource creation for teachers",
    targetAudience: "teachers",
    pricing: {
      free: true,
      monthlyPrice: 25.0,
      annualPrice: 15.0,
      enterprise: true,
      notes: "$15/mo billed annually; $25/mo billed monthly; free tier uses credit system with friction",
    },
    strengths: [
      "100+ AI tools purpose-built for teachers",
      "Strong lesson plan generation with subject and grade-level customization",
      "Comprehensive output types: lesson plans, worksheets, rubrics, assessments, and reports",
      "PDF and DOCX export for easy classroom distribution",
      "Active template library contributed by the teacher community",
    ],
    weaknesses: [
      "No student-facing features — students are invisible to the platform",
      "Free tier is credit-limited, creating friction that pushes users toward paid plans quickly",
      "At $25/mo, the monthly plan is among the highest-priced teacher AI tools",
      "No LMS integration — all output must be manually uploaded to Canvas or Google Classroom",
      "No syllabus-to-student pipeline — teachers create content in isolation",
      "No club or extracurricular management for student organizations",
      "No burnout prediction or student workload visibility",
    ],
    syllioDifference: [
      "Syllio's Teacher Pro plan ($11.99/mo annual) includes all core AI tools at less than half TeachQuill's price",
      "Syllio connects teacher output directly to students via class codes and LMS export — TeachQuill stops at PDF",
      "Syllio's free tier offers 2 full syllabus scans with no credit-draining microtransaction model",
      "Syllio's student join dashboard lets teachers see exactly who scanned their syllabus",
      "Syllio builds both sides of the classroom — TeachQuill serves only one",
      "Syllio's Teacher + Student Bundle gives an entire class a shared academic OS",
    ],
  },
  {
    name: "Education Copilot",
    slug: "education-copilot",
    url: "https://www.educationcopilot.com",
    tagline: "AI lesson plans, handouts, and curriculum resources for educators",
    targetAudience: "teachers",
    pricing: {
      free: true,
      monthlyPrice: null,
      annualPrice: 9.0,
      enterprise: false,
      notes: "$9/mo billed annually; limited free tier; no monthly billing option",
    },
    strengths: [
      "Low annual price makes it accessible for budget-conscious educators",
      "Core lesson plan and handout generation is quick",
      "Simple interface with minimal learning curve",
      "Subject and grade-level filters for content generation",
    ],
    weaknesses: [
      "Platform shows signs of declining investment and slow feature development",
      "No LMS integration — outputs must be manually distributed",
      "No student-facing tools or student data visibility",
      "No syllabus scanning or deadline extraction for students",
      "Feature set is narrower than MagicSchool, TeachQuill, or Syllio",
      "No mobile app — web only",
      "No club management or extracurricular tools",
      "Billing structure requires annual commitment with no monthly option",
    ],
    syllioDifference: [
      "Syllio is actively developed with a growing feature roadmap; Education Copilot shows declining momentum",
      "Syllio's Teacher Starter plan ($5.99/mo annual) is cheaper and more capable",
      "Syllio integrates with Canvas and Google Classroom for export — Education Copilot does not",
      "Syllio serves both teachers and students; Education Copilot is teacher-output only",
      "Syllio's PWA and mobile-first design means use anywhere, any device",
      "Syllio connects teacher content creation directly to student workflows",
    ],
  },
  {
    name: "DormWay",
    slug: "dormway",
    url: "https://www.dormway.app",
    tagline: "The student app for college life — scan syllabi, manage campus life",
    targetAudience: "students",
    pricing: {
      free: true,
      monthlyPrice: null,
      annualPrice: null,
      enterprise: false,
      notes: "Free base tier; premium pricing not publicly disclosed",
    },
    strengths: [
      "Student-focused design with campus-life context",
      "Syllabus scanning is a core feature",
      "Free tier provides immediate value with no upfront cost",
      "Focused on the college student experience",
    ],
    weaknesses: [
      "No teacher tools — teachers cannot create or share syllabi through the platform",
      "No club or student organization management features",
      "Paid tier pricing is opaque and not publicly listed",
      "No LMS sync with Canvas, Blackboard, or Google Classroom",
      "No predictive workload management or burnout alerts",
      "No 4-year portfolio or long-term academic planning",
      "Limited to individual students — no class-wide deployment or teacher-student connection",
      "No verified leadership badges or extracurricular record",
    ],
    syllioDifference: [
      "Syllio's Club OS provides member management, push notifications, and PDF rosters — DormWay has no equivalent",
      "Syllio connects teachers and students in a closed loop — DormWay is student-only",
      "Syllio's Burnout Radar™ proactively flags high-workload weeks before they hit",
      "Syllio's OS Student plan includes a 4-year portfolio with link-in-bio for career building",
      "Syllio's pricing is fully transparent with clear annual and monthly options",
      "Syllio's LMS sync pulls deadlines automatically; students don't need to scan manually",
    ],
  },
  {
    name: "Google Classroom",
    slug: "google-classroom",
    url: "https://classroom.google.com",
    tagline: "A free, simple way to manage your classes with Google",
    targetAudience: "both",
    pricing: {
      free: true,
      monthlyPrice: null,
      annualPrice: null,
      enterprise: true,
      notes: "Free for K-12 schools via Google Workspace for Education; premium tiers for advanced features",
    },
    strengths: [
      "Completely free for most K-12 schools via Google Workspace for Education",
      "Deep integration with Google Docs, Drive, Forms, Meet, and Calendar",
      "Extremely wide adoption — used in tens of millions of classrooms worldwide",
      "Simple assignment distribution and grade passback",
      "Familiar interface for students already in the Google ecosystem",
      "Solid mobile apps for iOS and Android",
    ],
    weaknesses: [
      "No AI syllabus generation — teachers must manually create and post content",
      "No automated deadline extraction or calendar parsing from syllabi",
      "No club or student organization management",
      "No predictive student workload management",
      "No student portfolio or career milestone tracking",
      "Designed as an LMS, not as an academic planning OS",
      "No burnout prediction or academic load visualization",
      "Grade passback is one-way — no student-facing smart scheduling",
    ],
    syllioDifference: [
      "Syllio generates AI syllabi instantly — Google Classroom requires manual content creation",
      "Syllio scans and extracts deadlines automatically; Google Classroom just posts what teachers manually enter",
      "Syllio's Burnout Radar™ gives students a predictive view of their workload — Google Classroom has no equivalent",
      "Syllio's Club OS is a complete student organization management layer Google Classroom cannot provide",
      "Syllio exports directly to Google Classroom — it extends what Classroom can do, not replaces it",
      "Syllio's 4-year portfolio gives students a permanent record of their academic and extracurricular life",
    ],
  },
  {
    name: "Notion",
    slug: "notion",
    url: "https://www.notion.so",
    tagline: "The all-in-one workspace for notes, docs, and projects",
    targetAudience: "general",
    pricing: {
      free: true,
      monthlyPrice: 8.0,
      annualPrice: null,
      enterprise: true,
      notes: "Free personal plan; Plus at $8/mo per seat billed annually; Business and Enterprise tiers available",
    },
    strengths: [
      "Extremely flexible — can be customized for almost any workflow",
      "Strong free tier with unlimited pages and blocks",
      "Notion AI adds writing assistance and summarization across any document",
      "Popular among college students as a personal knowledge management tool",
      "Templates marketplace with thousands of student and teacher templates",
      "Multi-platform with solid mobile and desktop apps",
    ],
    weaknesses: [
      "Not built for education — no education-specific AI features",
      "No syllabus scanning or automated deadline extraction",
      "No LMS integration — nothing syncs with Canvas, Blackboard, or Google Classroom",
      "No club management or student organization tools",
      "No burnout prediction or academic workload intelligence",
      "Setup requires significant time investment to build a useful system",
      "No teacher-to-student sharing via class codes",
      "No verified academic credentials or portfolio attestation",
    ],
    syllioDifference: [
      "Syllio is built specifically for the classroom — no setup, no template hunting",
      "Syllio scans syllabi and populates a calendar automatically; Notion requires manual entry",
      "Syllio's LMS sync with Canvas and Google Classroom is native — Notion has no LMS awareness",
      "Syllio's Burnout Radar™ actively monitors academic load; Notion is passive documentation",
      "Syllio's Club OS gives student organizations a full management suite; Notion is generic project boards",
      "Syllio costs less than Notion Plus while delivering far more education-specific value",
    ],
  },
  {
    name: "myHomework Student Planner",
    slug: "myhomework",
    url: "https://myhomeworkapp.com",
    tagline: "The student planner app that keeps you organized",
    targetAudience: "students",
    pricing: {
      free: true,
      monthlyPrice: null,
      annualPrice: 4.99,
      enterprise: false,
      notes: "Free base app; Premium at $4.99/yr for ad removal and extra features",
    },
    strengths: [
      "Very low cost — $4.99/year is among the cheapest student tools available",
      "Simple, clean interface specifically designed for student homework tracking",
      "Available on iOS, Android, and web",
      "Long-standing brand recognition among K-12 students",
      "Class and assignment color-coding for visual organization",
    ],
    weaknesses: [
      "Manual entry only — students must type in every assignment and deadline by hand",
      "No AI syllabus scanning or automated deadline extraction",
      "No LMS integration with Canvas, Blackboard, or Google Classroom",
      "No club or extracurricular management",
      "No teacher tools or teacher-student connection",
      "No burnout prediction or workload intelligence",
      "Very basic feature set with limited innovation since launch",
      "No portfolio or long-term academic planning",
      "Minimal active development — aging product",
    ],
    syllioDifference: [
      "Syllio eliminates manual entry entirely — AI scans syllabi and auto-populates the calendar",
      "Syllio's LMS sync means deadlines flow in automatically without student action",
      "Syllio's Burnout Radar™ actively surfaces overload risk; myHomework is a passive checklist",
      "Syllio's Club OS serves student organizations; myHomework is limited to individual task tracking",
      "Syllio's OS Student plan includes a 4-year portfolio for career building",
      "Syllio's AI Pro Student plan ($4.99/mo) costs more but delivers dramatically more automation and intelligence",
    ],
  },
  {
    name: "Canvas LMS",
    slug: "canvas-lms",
    url: "https://www.instructure.com/canvas",
    tagline: "The learning management system that connects teachers and students",
    targetAudience: "both",
    pricing: {
      free: true,
      monthlyPrice: null,
      annualPrice: null,
      enterprise: true,
      notes: "Free for instructors (Canvas Free for Teachers); institutional licensing for full features; pricing not publicly listed",
    },
    strengths: [
      "Most widely adopted LMS in US higher education",
      "Comprehensive grade book, assignment submission, and discussion tools",
      "Robust API and third-party integration ecosystem",
      "SpeedGrader for efficient inline grading and annotation",
      "Integrates natively with hundreds of ed-tech tools",
      "Trusted and supported at the institutional level",
    ],
    weaknesses: [
      "Complex and designed for institution-level deployment — not individual teacher or student use",
      "No AI syllabus generation — all content must be manually created",
      "No student academic OS features: no burnout alerts, no portfolio, no club management",
      "Interface is dense and has a steep learning curve for new users",
      "Free version for teachers lacks key features available in institutional deployments",
      "No smart scheduling or workload prediction for students",
      "Syllabus tool is a static document, not an intelligent planning tool",
    ],
    syllioDifference: [
      "Syllio is designed for individual use — no IT department or institutional contract required",
      "Syllio generates AI syllabi that teachers can export directly to Canvas — extending Canvas, not competing",
      "Syllio adds the student academic OS layer that Canvas deliberately does not provide",
      "Syllio's Burnout Radar™ gives students workload intelligence that Canvas graders never surface",
      "Syllio works in minutes with no onboarding, training, or admin setup",
      "Syllio and Canvas are complementary — Syllio enriches the Canvas ecosystem for both sides",
    ],
  },
  {
    name: "Coursebox AI",
    slug: "coursebox-ai",
    url: "https://www.coursebox.ai",
    tagline: "Turn your content into a full online course with AI",
    targetAudience: "teachers",
    pricing: {
      free: true,
      monthlyPrice: 33.0,
      annualPrice: null,
      enterprise: true,
      notes: "$33/mo for Creator plan; higher tiers for teams and white-label",
    },
    strengths: [
      "Powerful AI course creation from existing documents, videos, and URLs",
      "Built-in AI quiz and assessment generation",
      "White-labeling and custom branding for institutional use",
      "Supports video course creation with AI-generated narration",
      "Strong fit for eLearning content creators and corporate trainers",
    ],
    weaknesses: [
      "Primarily for eLearning and asynchronous course creators — not K-12 or college syllabi",
      "At $33/mo, it is among the highest-priced tools in the space",
      "No student-facing academic OS features",
      "No syllabus scanning or deadline extraction for students",
      "No LMS export to Canvas or Google Classroom in standard tiers",
      "No club management or academic calendar for students",
      "Overkill for teachers who need syllabi and lesson plans, not full eLearning courses",
      "Not designed for traditional classroom settings",
    ],
    syllioDifference: [
      "Syllio is purpose-built for K-12 and higher education classrooms — not eLearning content production",
      "Syllio's Teacher Pro plan ($11.99/mo annual) is less than half of Coursebox's price",
      "Syllio creates syllabi, lesson plans, and rubrics — and connects them directly to student calendars",
      "Syllio's student-side tools (scanning, burnout radar, portfolio) have no equivalent in Coursebox",
      "Syllio's Club OS addresses student organizations — completely outside Coursebox's scope",
      "Syllio exports to Canvas and Google Classroom natively; Coursebox does not",
    ],
  },
];

export function getCompetitorBySlug(slug: string): Competitor | undefined {
  return competitors.find((c) => c.slug === slug);
}

export function getAllCompetitorSlugs(): { competitor: string }[] {
  return competitors.map((c) => ({ competitor: c.slug }));
}
