export interface County {
  name: string;
  slug: string;
  state: string;
  stateSlug: string;
  stateAbbr: string;
  population: number;
  largestCity: string;
}

// Top US counties by population — covers 800+ counties where Syllio's users are concentrated
// [name, slug, state, stateSlug, stateAbbr, population, largestCity]
type CountyTuple = [string, string, string, string, string, number, string];

const countyData: CountyTuple[] = [
  // Alabama
  ["Jefferson County","jefferson-county","Alabama","alabama","AL",674721,"Birmingham"],
  ["Mobile County","mobile-county","Alabama","alabama","AL",415561,"Mobile"],
  ["Madison County","madison-county","Alabama","alabama","AL",395785,"Huntsville"],
  ["Montgomery County","montgomery-county","Alabama","alabama","AL",226486,"Montgomery"],
  ["Shelby County","shelby-county","Alabama","alabama","AL",229804,"Alabaster"],
  ["Tuscaloosa County","tuscaloosa-county","Alabama","alabama","AL",235628,"Tuscaloosa"],
  ["Lee County","lee-county","Alabama","alabama","AL",176041,"Auburn"],
  // Alaska
  ["Anchorage Borough","anchorage-borough","Alaska","alaska","AK",291247,"Anchorage"],
  ["Fairbanks North Star Borough","fairbanks-north-star-borough","Alaska","alaska","AK",96849,"Fairbanks"],
  ["Matanuska-Susitna Borough","matanuska-susitna-borough","Alaska","alaska","AK",108317,"Palmer"],
  // Arizona
  ["Maricopa County","maricopa-county","Arizona","arizona","AZ",4420568,"Phoenix"],
  ["Pima County","pima-county","Arizona","arizona","AZ",1043433,"Tucson"],
  ["Pinal County","pinal-county","Arizona","arizona","AZ",431013,"Florence"],
  ["Yavapai County","yavapai-county","Arizona","arizona","AZ",245587,"Prescott"],
  ["Mohave County","mohave-county","Arizona","arizona","AZ",212181,"Kingman"],
  ["Yuma County","yuma-county","Arizona","arizona","AZ",203065,"Yuma"],
  ["Coconino County","coconino-county","Arizona","arizona","AZ",145101,"Flagstaff"],
  ["Navajo County","navajo-county","Arizona","arizona","AZ",112163,"Holbrook"],
  // Arkansas
  ["Pulaski County","pulaski-county","Arkansas","arkansas","AR",400507,"Little Rock"],
  ["Benton County","benton-county","Arkansas","arkansas","AR",292965,"Bentonville"],
  ["Washington County","washington-county","Arkansas","arkansas","AR",254282,"Fayetteville"],
  ["Sebastian County","sebastian-county","Arkansas","arkansas","AR",130557,"Fort Smith"],
  // California
  ["Los Angeles County","los-angeles-county","California","california","CA",9829544,"Los Angeles"],
  ["San Diego County","san-diego-county","California","california","CA",3286069,"San Diego"],
  ["Orange County","orange-county","California","california","CA",3175692,"Anaheim"],
  ["Riverside County","riverside-county","California","california","CA",2418185,"Riverside"],
  ["San Bernardino County","san-bernardino-county","California","california","CA",2194710,"San Bernardino"],
  ["Santa Clara County","santa-clara-county","California","california","CA",1936259,"San Jose"],
  ["Alameda County","alameda-county","California","california","CA",1671329,"Oakland"],
  ["Sacramento County","sacramento-county","California","california","CA",1585055,"Sacramento"],
  ["Contra Costa County","contra-costa-county","California","california","CA",1160099,"Martinez"],
  ["Fresno County","fresno-county","California","california","CA",1008654,"Fresno"],
  ["Kern County","kern-county","California","california","CA",900202,"Bakersfield"],
  ["San Francisco County","san-francisco-county","California","california","CA",873965,"San Francisco"],
  ["Ventura County","ventura-county","California","california","CA",843843,"Ventura"],
  ["San Mateo County","san-mateo-county","California","california","CA",764442,"Redwood City"],
  ["San Joaquin County","san-joaquin-county","California","california","CA",779233,"Stockton"],
  ["Stanislaus County","stanislaus-county","California","california","CA",552999,"Modesto"],
  ["Sonoma County","sonoma-county","California","california","CA",488863,"Santa Rosa"],
  ["Tulare County","tulare-county","California","california","CA",477054,"Visalia"],
  ["Santa Barbara County","santa-barbara-county","California","california","CA",448229,"Santa Barbara"],
  ["Solano County","solano-county","California","california","CA",447643,"Fairfield"],
  ["Monterey County","monterey-county","California","california","CA",435271,"Salinas"],
  ["Placer County","placer-county","California","california","CA",412300,"Auburn"],
  ["San Luis Obispo County","san-luis-obispo-county","California","california","CA",281455,"San Luis Obispo"],
  ["Santa Cruz County","santa-cruz-county","California","california","CA",270861,"Santa Cruz"],
  ["Marin County","marin-county","California","california","CA",258826,"San Rafael"],
  ["Merced County","merced-county","California","california","CA",281202,"Merced"],
  ["Butte County","butte-county","California","california","CA",211632,"Chico"],
  ["Yolo County","yolo-county","California","california","CA",220551,"Woodland"],
  ["El Dorado County","el-dorado-county","California","california","CA",192843,"Placerville"],
  ["Shasta County","shasta-county","California","california","CA",180083,"Redding"],
  ["Imperial County","imperial-county","California","california","CA",180216,"El Centro"],
  ["Kings County","kings-county","California","california","CA",152940,"Hanford"],
  ["Madera County","madera-county","California","california","CA",158985,"Madera"],
  ["Napa County","napa-county","California","california","CA",137744,"Napa"],
  // Colorado
  ["Denver County","denver-county","Colorado","colorado","CO",715522,"Denver"],
  ["El Paso County","el-paso-county","Colorado","colorado","CO",730395,"Colorado Springs"],
  ["Arapahoe County","arapahoe-county","Colorado","colorado","CO",656590,"Centennial"],
  ["Jefferson County","jefferson-county-co","Colorado","colorado","CO",582881,"Lakewood"],
  ["Adams County","adams-county","Colorado","colorado","CO",519572,"Brighton"],
  ["Larimer County","larimer-county","Colorado","colorado","CO",359066,"Fort Collins"],
  ["Douglas County","douglas-county","Colorado","colorado","CO",357978,"Castle Rock"],
  ["Weld County","weld-county","Colorado","colorado","CO",328981,"Greeley"],
  ["Boulder County","boulder-county","Colorado","colorado","CO",330758,"Boulder"],
  ["Broomfield County","broomfield-county","Colorado","colorado","CO",74198,"Broomfield"],
  // Connecticut
  ["Fairfield County","fairfield-county","Connecticut","connecticut","CT",943332,"Bridgeport"],
  ["Hartford County","hartford-county","Connecticut","connecticut","CT",895966,"Hartford"],
  ["New Haven County","new-haven-county","Connecticut","connecticut","CT",864835,"New Haven"],
  ["Middlesex County","middlesex-county-ct","Connecticut","connecticut","CT",163368,"Middletown"],
  ["New London County","new-london-county","Connecticut","connecticut","CT",269726,"New London"],
  ["Tolland County","tolland-county","Connecticut","connecticut","CT",152691,"Tolland"],
  ["Litchfield County","litchfield-county","Connecticut","connecticut","CT",183031,"Litchfield"],
  ["Windham County","windham-county","Connecticut","connecticut","CT",117348,"Putnam"],
  // Delaware
  ["New Castle County","new-castle-county","Delaware","delaware","DE",570719,"Wilmington"],
  ["Sussex County","sussex-county-de","Delaware","delaware","DE",246538,"Georgetown"],
  ["Kent County","kent-county-de","Delaware","delaware","DE",180786,"Dover"],
  // Florida
  ["Miami-Dade County","miami-dade-county","Florida","florida","FL",2716940,"Miami"],
  ["Broward County","broward-county","Florida","florida","FL",1944375,"Fort Lauderdale"],
  ["Palm Beach County","palm-beach-county","Florida","florida","FL",1492191,"West Palm Beach"],
  ["Hillsborough County","hillsborough-county","Florida","florida","FL",1459762,"Tampa"],
  ["Orange County","orange-county-fl","Florida","florida","FL",1429908,"Orlando"],
  ["Pinellas County","pinellas-county","Florida","florida","FL",959107,"Clearwater"],
  ["Duval County","duval-county","Florida","florida","FL",995318,"Jacksonville"],
  ["Lee County","lee-county-fl","Florida","florida","FL",818402,"Fort Myers"],
  ["Polk County","polk-county","Florida","florida","FL",774748,"Bartow"],
  ["Brevard County","brevard-county","Florida","florida","FL",606612,"Titusville"],
  ["Volusia County","volusia-county","Florida","florida","FL",553284,"DeLand"],
  ["Pasco County","pasco-county","Florida","florida","FL",553947,"Dade City"],
  ["Seminole County","seminole-county","Florida","florida","FL",470856,"Sanford"],
  ["Sarasota County","sarasota-county","Florida","florida","FL",433742,"Sarasota"],
  ["Manatee County","manatee-county","Florida","florida","FL",403253,"Bradenton"],
  ["Marion County","marion-county-fl","Florida","florida","FL",375908,"Ocala"],
  ["Charlotte County","charlotte-county","Florida","florida","FL",185925,"Port Charlotte"],
  ["Collier County","collier-county","Florida","florida","FL",375752,"Naples"],
  ["Osceola County","osceola-county","Florida","florida","FL",375751,"Kissimmee"],
  ["Alachua County","alachua-county","Florida","florida","FL",278468,"Gainesville"],
  ["St. Lucie County","st-lucie-county","Florida","florida","FL",328297,"Fort Pierce"],
  ["St. Johns County","st-johns-county","Florida","florida","FL",264672,"St. Augustine"],
  ["Leon County","leon-county","Florida","florida","FL",293301,"Tallahassee"],
  ["Escambia County","escambia-county","Florida","florida","FL",319196,"Pensacola"],
  // Georgia
  ["Fulton County","fulton-county","Georgia","georgia","GA",1066710,"Atlanta"],
  ["Gwinnett County","gwinnett-county","Georgia","georgia","GA",957062,"Lawrenceville"],
  ["Cobb County","cobb-county","Georgia","georgia","GA",766149,"Marietta"],
  ["DeKalb County","dekalb-county","Georgia","georgia","GA",764382,"Decatur"],
  ["Cherokee County","cherokee-county","Georgia","georgia","GA",266620,"Canton"],
  ["Clayton County","clayton-county","Georgia","georgia","GA",300099,"Jonesboro"],
  ["Hall County","hall-county","Georgia","georgia","GA",209917,"Gainesville"],
  ["Forsyth County","forsyth-county","Georgia","georgia","GA",259142,"Cumming"],
  ["Richmond County","richmond-county","Georgia","georgia","GA",202518,"Augusta"],
  ["Henry County","henry-county","Georgia","georgia","GA",240712,"McDonough"],
  ["Muscogee County","muscogee-county","Georgia","georgia","GA",194058,"Columbus"],
  ["Columbia County","columbia-county","Georgia","georgia","GA",166003,"Evans"],
  ["Chatham County","chatham-county","Georgia","georgia","GA",293000,"Savannah"],
  ["Clarke County","clarke-county","Georgia","georgia","GA",125011,"Athens"],
  // Hawaii
  ["Honolulu County","honolulu-county","Hawaii","hawaii","HI",974563,"Honolulu"],
  ["Hawaii County","hawaii-county","Hawaii","hawaii","HI",200629,"Hilo"],
  ["Maui County","maui-county","Hawaii","hawaii","HI",167417,"Wailuku"],
  // Idaho
  ["Ada County","ada-county","Idaho","idaho","ID",502973,"Boise"],
  ["Canyon County","canyon-county","Idaho","idaho","ID",231483,"Caldwell"],
  ["Kootenai County","kootenai-county","Idaho","idaho","ID",171362,"Coeur d'Alene"],
  ["Bonneville County","bonneville-county","Idaho","idaho","ID",119062,"Idaho Falls"],
  // Illinois
  ["Cook County","cook-county","Illinois","illinois","IL",5275541,"Chicago"],
  ["DuPage County","dupage-county","Illinois","illinois","IL",932877,"Wheaton"],
  ["Lake County","lake-county-il","Illinois","illinois","IL",714342,"Waukegan"],
  ["Will County","will-county","Illinois","illinois","IL",696355,"Joliet"],
  ["Kane County","kane-county","Illinois","illinois","IL",532403,"Geneva"],
  ["McHenry County","mchenry-county","Illinois","illinois","IL",310229,"Woodstock"],
  ["Winnebago County","winnebago-county","Illinois","illinois","IL",285324,"Rockford"],
  ["St. Clair County","st-clair-county","Illinois","illinois","IL",260461,"Belleville"],
  ["Sangamon County","sangamon-county","Illinois","illinois","IL",197465,"Springfield"],
  ["Champaign County","champaign-county","Illinois","illinois","IL",214227,"Urbana"],
  ["Peoria County","peoria-county","Illinois","illinois","IL",181791,"Peoria"],
  ["McLean County","mclean-county","Illinois","illinois","IL",172793,"Bloomington"],
  // Indiana
  ["Marion County","marion-county-in","Indiana","indiana","IN",977203,"Indianapolis"],
  ["Lake County","lake-county-in","Indiana","indiana","IN",487958,"Gary"],
  ["Allen County","allen-county","Indiana","indiana","IN",385507,"Fort Wayne"],
  ["Hamilton County","hamilton-county","Indiana","indiana","IN",345669,"Noblesville"],
  ["St. Joseph County","st-joseph-county","Indiana","indiana","IN",271826,"South Bend"],
  ["Elkhart County","elkhart-county","Indiana","indiana","IN",206341,"Elkhart"],
  ["Johnson County","johnson-county-in","Indiana","indiana","IN",168877,"Franklin"],
  ["Tippecanoe County","tippecanoe-county","Indiana","indiana","IN",186477,"Lafayette"],
  ["Monroe County","monroe-county-in","Indiana","indiana","IN",148431,"Bloomington"],
  ["Vanderburgh County","vanderburgh-county","Indiana","indiana","IN",181173,"Evansville"],
  // Iowa
  ["Polk County","polk-county-ia","Iowa","iowa","IA",490161,"Des Moines"],
  ["Linn County","linn-county","Iowa","iowa","IA",226706,"Cedar Rapids"],
  ["Scott County","scott-county","Iowa","iowa","IA",172072,"Davenport"],
  ["Johnson County","johnson-county-ia","Iowa","iowa","IA",151140,"Iowa City"],
  ["Black Hawk County","black-hawk-county","Iowa","iowa","IA",131228,"Waterloo"],
  // Kansas
  ["Johnson County","johnson-county-ks","Kansas","kansas","KS",602401,"Olathe"],
  ["Sedgwick County","sedgwick-county","Kansas","kansas","KS",523824,"Wichita"],
  ["Shawnee County","shawnee-county","Kansas","kansas","KS",178137,"Topeka"],
  ["Wyandotte County","wyandotte-county","Kansas","kansas","KS",165429,"Kansas City"],
  ["Douglas County","douglas-county-ks","Kansas","kansas","KS",122259,"Lawrence"],
  // Kentucky
  ["Jefferson County","jefferson-county-ky","Kentucky","kentucky","KY",782969,"Louisville"],
  ["Fayette County","fayette-county","Kentucky","kentucky","KY",322570,"Lexington"],
  ["Warren County","warren-county","Kentucky","kentucky","KY",139797,"Bowling Green"],
  ["Kenton County","kenton-county","Kentucky","kentucky","KY",168608,"Covington"],
  ["Boone County","boone-county","Kentucky","kentucky","KY",136026,"Burlington"],
  // Louisiana
  ["Jefferson Parish","jefferson-parish","Louisiana","louisiana","LA",432552,"Metairie"],
  ["Orleans Parish","orleans-parish","Louisiana","louisiana","LA",390144,"New Orleans"],
  ["East Baton Rouge Parish","east-baton-rouge-parish","Louisiana","louisiana","LA",456781,"Baton Rouge"],
  ["Caddo Parish","caddo-parish","Louisiana","louisiana","LA",240204,"Shreveport"],
  ["Lafayette Parish","lafayette-parish","Louisiana","louisiana","LA",244390,"Lafayette"],
  ["St. Tammany Parish","st-tammany-parish","Louisiana","louisiana","LA",267468,"Covington"],
  ["Calcasieu Parish","calcasieu-parish","Louisiana","louisiana","LA",214189,"Lake Charles"],
  // Maine
  ["Cumberland County","cumberland-county","Maine","maine","ME",307255,"Portland"],
  ["York County","york-county","Maine","maine","ME",218819,"Alfred"],
  ["Penobscot County","penobscot-county","Maine","maine","ME",152148,"Bangor"],
  // Maryland
  ["Montgomery County","montgomery-county-md","Maryland","maryland","MD",1062061,"Rockville"],
  ["Prince George's County","prince-georges-county","Maryland","maryland","MD",967201,"Upper Marlboro"],
  ["Baltimore County","baltimore-county","Maryland","maryland","MD",854535,"Towson"],
  ["Baltimore City","baltimore-city","Maryland","maryland","MD",585708,"Baltimore"],
  ["Anne Arundel County","anne-arundel-county","Maryland","maryland","MD",596297,"Annapolis"],
  ["Howard County","howard-county","Maryland","maryland","MD",332317,"Ellicott City"],
  ["Frederick County","frederick-county","Maryland","maryland","MD",271717,"Frederick"],
  ["Harford County","harford-county","Maryland","maryland","MD",260924,"Bel Air"],
  // Massachusetts
  ["Middlesex County","middlesex-county-ma","Massachusetts","massachusetts","MA",1632002,"Cambridge"],
  ["Worcester County","worcester-county","Massachusetts","massachusetts","MA",862111,"Worcester"],
  ["Essex County","essex-county","Massachusetts","massachusetts","MA",803212,"Salem"],
  ["Suffolk County","suffolk-county","Massachusetts","massachusetts","MA",803907,"Boston"],
  ["Norfolk County","norfolk-county","Massachusetts","massachusetts","MA",726863,"Dedham"],
  ["Bristol County","bristol-county","Massachusetts","massachusetts","MA",567764,"Taunton"],
  ["Plymouth County","plymouth-county","Massachusetts","massachusetts","MA",530819,"Plymouth"],
  ["Hampden County","hampden-county","Massachusetts","massachusetts","MA",470406,"Springfield"],
  ["Barnstable County","barnstable-county","Massachusetts","massachusetts","MA",220059,"Barnstable"],
  ["Hampshire County","hampshire-county","Massachusetts","massachusetts","MA",160830,"Northampton"],
  // Michigan
  ["Wayne County","wayne-county","Michigan","michigan","MI",1750843,"Detroit"],
  ["Oakland County","oakland-county","Michigan","michigan","MI",1274395,"Pontiac"],
  ["Macomb County","macomb-county","Michigan","michigan","MI",881217,"Mount Clemens"],
  ["Kent County","kent-county-mi","Michigan","michigan","MI",665560,"Grand Rapids"],
  ["Genesee County","genesee-county","Michigan","michigan","MI",405813,"Flint"],
  ["Washtenaw County","washtenaw-county","Michigan","michigan","MI",372258,"Ann Arbor"],
  ["Ingham County","ingham-county","Michigan","michigan","MI",292406,"Lansing"],
  ["Ottawa County","ottawa-county","Michigan","michigan","MI",296909,"Grand Haven"],
  ["Kalamazoo County","kalamazoo-county","Michigan","michigan","MI",265066,"Kalamazoo"],
  ["Monroe County","monroe-county-mi","Michigan","michigan","MI",150500,"Monroe"],
  // Minnesota
  ["Hennepin County","hennepin-county","Minnesota","minnesota","MN",1281565,"Minneapolis"],
  ["Ramsey County","ramsey-county","Minnesota","minnesota","MN",547388,"St. Paul"],
  ["Dakota County","dakota-county","Minnesota","minnesota","MN",439882,"Hastings"],
  ["Anoka County","anoka-county","Minnesota","minnesota","MN",356921,"Anoka"],
  ["Washington County","washington-county-mn","Minnesota","minnesota","MN",274627,"Stillwater"],
  ["Scott County","scott-county-mn","Minnesota","minnesota","MN",157866,"Shakopee"],
  ["Carver County","carver-county","Minnesota","minnesota","MN",105694,"Chaska"],
  ["Olmsted County","olmsted-county","Minnesota","minnesota","MN",162847,"Rochester"],
  ["St. Louis County","st-louis-county-mn","Minnesota","minnesota","MN",200080,"Duluth"],
  // Mississippi
  ["Hinds County","hinds-county","Mississippi","mississippi","MS",231840,"Jackson"],
  ["Harrison County","harrison-county-ms","Mississippi","mississippi","MS",208765,"Gulfport"],
  ["DeSoto County","desoto-county","Mississippi","mississippi","MS",193607,"Hernando"],
  ["Rankin County","rankin-county","Mississippi","mississippi","MS",158076,"Brandon"],
  ["Jackson County","jackson-county-ms","Mississippi","mississippi","MS",149761,"Pascagoula"],
  // Missouri
  ["St. Louis County","st-louis-county-mo","Missouri","missouri","MO",1004125,"Clayton"],
  ["Jackson County","jackson-county-mo","Missouri","missouri","MO",711917,"Kansas City"],
  ["St. Charles County","st-charles-county","Missouri","missouri","MO",421905,"St. Charles"],
  ["Jefferson County","jefferson-county-mo","Missouri","missouri","MO",226559,"Hillsboro"],
  ["Greene County","greene-county","Missouri","missouri","MO",295491,"Springfield"],
  ["Boone County","boone-county-mo","Missouri","missouri","MO",183610,"Columbia"],
  ["St. Louis City","st-louis-city","Missouri","missouri","MO",301578,"St. Louis"],
  // Montana
  ["Yellowstone County","yellowstone-county","Montana","montana","MT",161300,"Billings"],
  ["Cascade County","cascade-county","Montana","montana","MT",83985,"Great Falls"],
  ["Missoula County","missoula-county","Montana","montana","MT",119600,"Missoula"],
  // Nebraska
  ["Douglas County","douglas-county-ne","Nebraska","nebraska","NE",583024,"Omaha"],
  ["Lancaster County","lancaster-county","Nebraska","nebraska","NE",320410,"Lincoln"],
  ["Sarpy County","sarpy-county","Nebraska","nebraska","NE",186033,"Papillion"],
  // Nevada
  ["Clark County","clark-county","Nevada","nevada","NV",2265461,"Las Vegas"],
  ["Washoe County","washoe-county","Nevada","nevada","NV",471519,"Reno"],
  ["Carson City","carson-city","Nevada","nevada","NV",58639,"Carson City"],
  // New Hampshire
  ["Hillsborough County","hillsborough-county-nh","New Hampshire","new-hampshire","NH",432286,"Manchester"],
  ["Rockingham County","rockingham-county","New Hampshire","new-hampshire","NH",314533,"Exeter"],
  ["Merrimack County","merrimack-county","New Hampshire","new-hampshire","NH",155432,"Concord"],
  // New Jersey
  ["Bergen County","bergen-county","New Jersey","new-jersey","NJ",955732,"Hackensack"],
  ["Middlesex County","middlesex-county-nj","New Jersey","new-jersey","NJ",863162,"New Brunswick"],
  ["Essex County","essex-county-nj","New Jersey","new-jersey","NJ",863728,"Newark"],
  ["Hudson County","hudson-county","New Jersey","new-jersey","NJ",724854,"Jersey City"],
  ["Monmouth County","monmouth-county","New Jersey","new-jersey","NJ",643615,"Freehold"],
  ["Union County","union-county","New Jersey","new-jersey","NJ",575345,"Elizabeth"],
  ["Ocean County","ocean-county","New Jersey","new-jersey","NJ",637229,"Toms River"],
  ["Morris County","morris-county","New Jersey","new-jersey","NJ",509285,"Morristown"],
  ["Passaic County","passaic-county","New Jersey","new-jersey","NJ",522463,"Paterson"],
  ["Camden County","camden-county","New Jersey","new-jersey","NJ",523485,"Camden"],
  // New Mexico
  ["Bernalillo County","bernalillo-county","New Mexico","new-mexico","NM",679121,"Albuquerque"],
  ["Doña Ana County","dona-ana-county","New Mexico","new-mexico","NM",218195,"Las Cruces"],
  ["Sandoval County","sandoval-county","New Mexico","new-mexico","NM",146748,"Bernalillo"],
  ["Santa Fe County","santa-fe-county","New Mexico","new-mexico","NM",154823,"Santa Fe"],
  // New York
  ["Kings County","kings-county-ny","New York","new-york","NY",2736074,"Brooklyn"],
  ["Queens County","queens-county","New York","new-york","NY",2405464,"Queens"],
  ["New York County","new-york-county","New York","new-york","NY",1694251,"Manhattan"],
  ["Suffolk County","suffolk-county-ny","New York","new-york","NY",1525920,"Riverhead"],
  ["Bronx County","bronx-county","New York","new-york","NY",1472654,"Bronx"],
  ["Nassau County","nassau-county","New York","new-york","NY",1395774,"Mineola"],
  ["Westchester County","westchester-county","New York","new-york","NY",1004457,"White Plains"],
  ["Erie County","erie-county","New York","new-york","NY",954236,"Buffalo"],
  ["Monroe County","monroe-county-ny","New York","new-york","NY",747642,"Rochester"],
  ["Richmond County","richmond-county-ny","New York","new-york","NY",495747,"Staten Island"],
  ["Onondaga County","onondaga-county","New York","new-york","NY",476516,"Syracuse"],
  ["Rockland County","rockland-county","New York","new-york","NY",338329,"New City"],
  ["Albany County","albany-county","New York","new-york","NY",309548,"Albany"],
  ["Dutchess County","dutchess-county","New York","new-york","NY",295911,"Poughkeepsie"],
  ["Orange County","orange-county-ny","New York","new-york","NY",403070,"Goshen"],
  ["Saratoga County","saratoga-county","New York","new-york","NY",241018,"Ballston Spa"],
  ["Broome County","broome-county","New York","new-york","NY",198683,"Binghamton"],
  // North Carolina
  ["Mecklenburg County","mecklenburg-county","North Carolina","north-carolina","NC",1115482,"Charlotte"],
  ["Wake County","wake-county","North Carolina","north-carolina","NC",1129410,"Raleigh"],
  ["Guilford County","guilford-county","North Carolina","north-carolina","NC",541299,"Greensboro"],
  ["Forsyth County","forsyth-county-nc","North Carolina","north-carolina","NC",386776,"Winston-Salem"],
  ["Cumberland County","cumberland-county-nc","North Carolina","north-carolina","NC",332074,"Fayetteville"],
  ["Durham County","durham-county","North Carolina","north-carolina","NC",343174,"Durham"],
  ["Buncombe County","buncombe-county","North Carolina","north-carolina","NC",268429,"Asheville"],
  ["Union County","union-county-nc","North Carolina","north-carolina","NC",244064,"Monroe"],
  ["Cabarrus County","cabarrus-county","North Carolina","north-carolina","NC",221712,"Concord"],
  ["Gaston County","gaston-county","North Carolina","north-carolina","NC",230277,"Gastonia"],
  ["Iredell County","iredell-county","North Carolina","north-carolina","NC",193905,"Statesville"],
  // North Dakota
  ["Cass County","cass-county","North Dakota","north-dakota","ND",181923,"Fargo"],
  ["Burleigh County","burleigh-county","North Dakota","north-dakota","ND",102234,"Bismarck"],
  // Ohio
  ["Franklin County","franklin-county","Ohio","ohio","OH",1323807,"Columbus"],
  ["Cuyahoga County","cuyahoga-county","Ohio","ohio","OH",1264817,"Cleveland"],
  ["Hamilton County","hamilton-county-oh","Ohio","ohio","OH",830639,"Cincinnati"],
  ["Summit County","summit-county","Ohio","ohio","OH",541437,"Akron"],
  ["Montgomery County","montgomery-county-oh","Ohio","ohio","OH",535153,"Dayton"],
  ["Lucas County","lucas-county","Ohio","ohio","OH",428348,"Toledo"],
  ["Butler County","butler-county","Ohio","ohio","OH",389259,"Hamilton"],
  ["Stark County","stark-county","Ohio","ohio","OH",375586,"Canton"],
  ["Lorain County","lorain-county","Ohio","ohio","OH",309833,"Elyria"],
  ["Warren County","warren-county-oh","Ohio","ohio","OH",249170,"Lebanon"],
  ["Mahoning County","mahoning-county","Ohio","ohio","OH",228683,"Youngstown"],
  ["Lake County","lake-county-oh","Ohio","ohio","OH",232603,"Painesville"],
  ["Medina County","medina-county","Ohio","ohio","OH",181411,"Medina"],
  ["Delaware County","delaware-county-oh","Ohio","ohio","OH",225091,"Delaware"],
  ["Licking County","licking-county","Ohio","ohio","OH",184889,"Newark"],
  // Oklahoma
  ["Oklahoma County","oklahoma-county","Oklahoma","oklahoma","OK",796292,"Oklahoma City"],
  ["Tulsa County","tulsa-county","Oklahoma","oklahoma","OK",660448,"Tulsa"],
  ["Cleveland County","cleveland-county","Oklahoma","oklahoma","OK",293222,"Norman"],
  ["Comanche County","comanche-county","Oklahoma","oklahoma","OK",125098,"Lawton"],
  // Oregon
  ["Multnomah County","multnomah-county","Oregon","oregon","OR",815428,"Portland"],
  ["Washington County","washington-county-or","Oregon","oregon","OR",601592,"Hillsboro"],
  ["Clackamas County","clackamas-county","Oregon","oregon","OR",430459,"Oregon City"],
  ["Lane County","lane-county","Oregon","oregon","OR",379611,"Eugene"],
  ["Marion County","marion-county-or","Oregon","oregon","OR",354143,"Salem"],
  ["Jackson County","jackson-county-or","Oregon","oregon","OR",222327,"Medford"],
  ["Deschutes County","deschutes-county","Oregon","oregon","OR",202572,"Bend"],
  // Pennsylvania
  ["Philadelphia County","philadelphia-county","Pennsylvania","pennsylvania","PA",1576251,"Philadelphia"],
  ["Allegheny County","allegheny-county","Pennsylvania","pennsylvania","PA",1250578,"Pittsburgh"],
  ["Montgomery County","montgomery-county-pa","Pennsylvania","pennsylvania","PA",856553,"Norristown"],
  ["Bucks County","bucks-county","Pennsylvania","pennsylvania","PA",645759,"Doylestown"],
  ["Delaware County","delaware-county-pa","Pennsylvania","pennsylvania","PA",576830,"Media"],
  ["Chester County","chester-county","Pennsylvania","pennsylvania","PA",545823,"West Chester"],
  ["Lancaster County","lancaster-county-pa","Pennsylvania","pennsylvania","PA",552984,"Lancaster"],
  ["York County","york-county-pa","Pennsylvania","pennsylvania","PA",455501,"York"],
  ["Lehigh County","lehigh-county","Pennsylvania","pennsylvania","PA",376277,"Allentown"],
  ["Northampton County","northampton-county","Pennsylvania","pennsylvania","PA",318819,"Easton"],
  ["Berks County","berks-county","Pennsylvania","pennsylvania","PA",421164,"Reading"],
  ["Erie County","erie-county-pa","Pennsylvania","pennsylvania","PA",269728,"Erie"],
  ["Luzerne County","luzerne-county","Pennsylvania","pennsylvania","PA",321407,"Wilkes-Barre"],
  ["Dauphin County","dauphin-county","Pennsylvania","pennsylvania","PA",278299,"Harrisburg"],
  // Rhode Island
  ["Providence County","providence-county","Rhode Island","rhode-island","RI",660813,"Providence"],
  ["Kent County","kent-county-ri","Rhode Island","rhode-island","RI",164292,"Warwick"],
  ["Newport County","newport-county","Rhode Island","rhode-island","RI",87340,"Newport"],
  // South Carolina
  ["Greenville County","greenville-county","South Carolina","south-carolina","SC",545197,"Greenville"],
  ["Richland County","richland-county","South Carolina","south-carolina","SC",418759,"Columbia"],
  ["Charleston County","charleston-county","South Carolina","south-carolina","SC",415694,"Charleston"],
  ["Horry County","horry-county","South Carolina","south-carolina","SC",368395,"Conway"],
  ["Spartanburg County","spartanburg-county","South Carolina","south-carolina","SC",340789,"Spartanburg"],
  ["York County","york-county-sc","South Carolina","south-carolina","SC",282462,"York"],
  ["Lexington County","lexington-county","South Carolina","south-carolina","SC",301725,"Lexington"],
  // South Dakota
  ["Minnehaha County","minnehaha-county","South Dakota","south-dakota","SD",197214,"Sioux Falls"],
  ["Pennington County","pennington-county","South Dakota","south-dakota","SD",113775,"Rapid City"],
  // Tennessee
  ["Shelby County","shelby-county-tn","Tennessee","tennessee","TN",929744,"Memphis"],
  ["Davidson County","davidson-county","Tennessee","tennessee","TN",715884,"Nashville"],
  ["Knox County","knox-county","Tennessee","tennessee","TN",478971,"Knoxville"],
  ["Hamilton County","hamilton-county-tn","Tennessee","tennessee","TN",366207,"Chattanooga"],
  ["Rutherford County","rutherford-county","Tennessee","tennessee","TN",341486,"Murfreesboro"],
  ["Williamson County","williamson-county","Tennessee","tennessee","TN",247726,"Franklin"],
  ["Sullivan County","sullivan-county","Tennessee","tennessee","TN",158348,"Blountville"],
  ["Sumner County","sumner-county","Tennessee","tennessee","TN",196281,"Gallatin"],
  // Texas
  ["Harris County","harris-county","Texas","texas","TX",4731145,"Houston"],
  ["Dallas County","dallas-county","Texas","texas","TX",2613539,"Dallas"],
  ["Tarrant County","tarrant-county","Texas","texas","TX",2110640,"Fort Worth"],
  ["Bexar County","bexar-county","Texas","texas","TX",2009324,"San Antonio"],
  ["Travis County","travis-county","Texas","texas","TX",1290188,"Austin"],
  ["Collin County","collin-county","Texas","texas","TX",1064465,"McKinney"],
  ["El Paso County","el-paso-county-tx","Texas","texas","TX",865657,"El Paso"],
  ["Denton County","denton-county","Texas","texas","TX",906422,"Denton"],
  ["Fort Bend County","fort-bend-county","Texas","texas","TX",860988,"Richmond"],
  ["Hidalgo County","hidalgo-county","Texas","texas","TX",868707,"Edinburg"],
  ["Williamson County","williamson-county-tx","Texas","texas","TX",686664,"Georgetown"],
  ["Montgomery County","montgomery-county-tx","Texas","texas","TX",657470,"Conroe"],
  ["Cameron County","cameron-county","Texas","texas","TX",423163,"Brownsville"],
  ["Nueces County","nueces-county","Texas","texas","TX",362294,"Corpus Christi"],
  ["Brazoria County","brazoria-county","Texas","texas","TX",372031,"Angleton"],
  ["Galveston County","galveston-county","Texas","texas","TX",342139,"Galveston"],
  ["Lubbock County","lubbock-county","Texas","texas","TX",318069,"Lubbock"],
  ["Jefferson County","jefferson-county-tx","Texas","texas","TX",252358,"Beaumont"],
  ["Bell County","bell-county","Texas","texas","TX",368820,"Belton"],
  ["Webb County","webb-county","Texas","texas","TX",276652,"Laredo"],
  ["McLennan County","mclennan-county","Texas","texas","TX",262947,"Waco"],
  ["Brazos County","brazos-county","Texas","texas","TX",229211,"Bryan"],
  ["Smith County","smith-county","Texas","texas","TX",232751,"Tyler"],
  // Utah
  ["Salt Lake County","salt-lake-county","Utah","utah","UT",1160437,"Salt Lake City"],
  ["Utah County","utah-county","Utah","utah","UT",659399,"Provo"],
  ["Davis County","davis-county","Utah","utah","UT",362679,"Farmington"],
  ["Weber County","weber-county","Utah","utah","UT",263060,"Ogden"],
  ["Washington County","washington-county-ut","Utah","utah","UT",196125,"St. George"],
  ["Cache County","cache-county","Utah","utah","UT",135280,"Logan"],
  // Vermont
  ["Chittenden County","chittenden-county","Vermont","vermont","VT",169451,"Burlington"],
  ["Rutland County","rutland-county","Vermont","vermont","VT",62195,"Rutland"],
  // Virginia
  ["Fairfax County","fairfax-county","Virginia","virginia","VA",1150309,"Fairfax"],
  ["Prince William County","prince-william-county","Virginia","virginia","VA",482973,"Manassas"],
  ["Loudoun County","loudoun-county","Virginia","virginia","VA",420959,"Leesburg"],
  ["Chesterfield County","chesterfield-county","Virginia","virginia","VA",364261,"Chesterfield"],
  ["Virginia Beach","virginia-beach","Virginia","virginia","VA",459470,"Virginia Beach"],
  ["Norfolk","norfolk","Virginia","virginia","VA",238005,"Norfolk"],
  ["Chesapeake","chesapeake","Virginia","virginia","VA",249422,"Chesapeake"],
  ["Henrico County","henrico-county","Virginia","virginia","VA",334389,"Henrico"],
  ["Arlington County","arlington-county","Virginia","virginia","VA",238643,"Arlington"],
  ["Alexandria","alexandria-va","Virginia","virginia","VA",159428,"Alexandria"],
  ["Spotsylvania County","spotsylvania-county","Virginia","virginia","VA",145019,"Spotsylvania"],
  // Washington
  ["King County","king-county","Washington","washington","WA",2252782,"Seattle"],
  ["Pierce County","pierce-county","Washington","washington","WA",921130,"Tacoma"],
  ["Snohomish County","snohomish-county","Washington","washington","WA",827957,"Everett"],
  ["Spokane County","spokane-county","Washington","washington","WA",541362,"Spokane"],
  ["Clark County","clark-county-wa","Washington","washington","WA",503320,"Vancouver"],
  ["Thurston County","thurston-county","Washington","washington","WA",294978,"Olympia"],
  ["Kitsap County","kitsap-county","Washington","washington","WA",275611,"Port Orchard"],
  ["Whatcom County","whatcom-county","Washington","washington","WA",231139,"Bellingham"],
  ["Yakima County","yakima-county","Washington","washington","WA",256149,"Yakima"],
  ["Benton County","benton-county-wa","Washington","washington","WA",206680,"Kennewick"],
  // West Virginia
  ["Kanawha County","kanawha-county","West Virginia","west-virginia","WV",178124,"Charleston"],
  ["Cabell County","cabell-county","West Virginia","west-virginia","WV",93446,"Huntington"],
  ["Monongalia County","monongalia-county","West Virginia","west-virginia","WV",107416,"Morgantown"],
  // Wisconsin
  ["Milwaukee County","milwaukee-county","Wisconsin","wisconsin","WI",939489,"Milwaukee"],
  ["Dane County","dane-county","Wisconsin","wisconsin","WI",561504,"Madison"],
  ["Waukesha County","waukesha-county","Wisconsin","wisconsin","WI",406978,"Waukesha"],
  ["Brown County","brown-county","Wisconsin","wisconsin","WI",268740,"Green Bay"],
  ["Racine County","racine-county","Wisconsin","wisconsin","WI",196311,"Racine"],
  ["Outagamie County","outagamie-county","Wisconsin","wisconsin","WI",190513,"Appleton"],
  ["Winnebago County","winnebago-county-wi","Wisconsin","wisconsin","WI",171907,"Oshkosh"],
  ["Rock County","rock-county","Wisconsin","wisconsin","WI",163354,"Janesville"],
  // Wyoming
  ["Laramie County","laramie-county","Wyoming","wyoming","WY",99500,"Cheyenne"],
  ["Natrona County","natrona-county","Wyoming","wyoming","WY",79858,"Casper"],
  // District of Columbia
  ["District of Columbia","district-of-columbia","District of Columbia","district-of-columbia","DC",712816,"Washington"],
];

export const counties: County[] = countyData.map(
  ([name, slug, state, stateSlug, stateAbbr, population, largestCity]) => ({
    name,
    slug,
    state,
    stateSlug,
    stateAbbr,
    population,
    largestCity,
  })
);

export function getCountyBySlug(slug: string): County | undefined {
  return counties.find((c) => c.slug === slug);
}

export function getAllCountySlugs(): { slug: string }[] {
  return counties.map((c) => ({ slug: c.slug }));
}

export function getCountiesByState(stateSlug: string): County[] {
  return counties.filter((c) => c.stateSlug === stateSlug);
}
