export interface Country {
  name: string;
  slug: string;
  continent: 'europe' | 'asia' | 'north-america' | 'south-america' | 'africa' | 'oceania' | 'middle-east';
  capital: string;
  studentPopulation: string;
  topUniversityCount: number;
  educationSystem: string;
  currency: string;
  languages: string[];
}

export const countries: Country[] = [
  // ── ENGLISH-SPEAKING ──────────────────────────────────────────────────────

  {
    name: 'United Kingdom',
    slug: 'united-kingdom',
    continent: 'europe',
    capital: 'London',
    studentPopulation: '2.9 million',
    topUniversityCount: 84,
    educationSystem: 'A-Levels, Bachelor\'s (3 yrs), Master\'s, PhD',
    currency: 'GBP',
    languages: ['English'],
  },
  {
    name: 'Ireland',
    slug: 'ireland',
    continent: 'europe',
    capital: 'Dublin',
    studentPopulation: '230,000',
    topUniversityCount: 8,
    educationSystem: 'Leaving Certificate, Bachelor\'s (3–4 yrs), Master\'s, PhD',
    currency: 'EUR',
    languages: ['English', 'Irish'],
  },
  {
    name: 'Australia',
    slug: 'australia',
    continent: 'oceania',
    capital: 'Canberra',
    studentPopulation: '1.6 million',
    topUniversityCount: 35,
    educationSystem: 'HSC/VCE, Bachelor\'s (3–4 yrs), Master\'s, PhD',
    currency: 'AUD',
    languages: ['English'],
  },
  {
    name: 'New Zealand',
    slug: 'new-zealand',
    continent: 'oceania',
    capital: 'Wellington',
    studentPopulation: '220,000',
    topUniversityCount: 8,
    educationSystem: 'NCEA, Bachelor\'s (3 yrs), Postgraduate Diploma, Master\'s, PhD',
    currency: 'NZD',
    languages: ['English', 'Maori'],
  },
  {
    name: 'Canada',
    slug: 'canada',
    continent: 'north-america',
    capital: 'Ottawa',
    studentPopulation: '2.3 million',
    topUniversityCount: 30,
    educationSystem: 'Provincial diplomas, Bachelor\'s (4 yrs), Master\'s, PhD',
    currency: 'CAD',
    languages: ['English', 'French'],
  },
  {
    name: 'South Africa',
    slug: 'south-africa',
    continent: 'africa',
    capital: 'Pretoria',
    studentPopulation: '1.0 million',
    topUniversityCount: 11,
    educationSystem: 'Matric, Bachelor\'s (3–4 yrs), Honours, Master\'s, PhD',
    currency: 'ZAR',
    languages: ['English', 'Zulu', 'Xhosa', 'Afrikaans'],
  },
  {
    name: 'Nigeria',
    slug: 'nigeria',
    continent: 'africa',
    capital: 'Abuja',
    studentPopulation: '1.9 million',
    topUniversityCount: 3,
    educationSystem: 'WAEC/NECO, Bachelor\'s (4–5 yrs), Master\'s, PhD',
    currency: 'NGN',
    languages: ['English'],
  },
  {
    name: 'Ghana',
    slug: 'ghana',
    continent: 'africa',
    capital: 'Accra',
    studentPopulation: '350,000',
    topUniversityCount: 2,
    educationSystem: 'WASSCE, Bachelor\'s (4 yrs), Master\'s, PhD',
    currency: 'GHS',
    languages: ['English'],
  },
  {
    name: 'Kenya',
    slug: 'kenya',
    continent: 'africa',
    capital: 'Nairobi',
    studentPopulation: '560,000',
    topUniversityCount: 2,
    educationSystem: 'KCSE, Bachelor\'s (4 yrs), Master\'s, PhD',
    currency: 'KES',
    languages: ['English', 'Swahili'],
  },
  {
    name: 'India',
    slug: 'india',
    continent: 'asia',
    capital: 'New Delhi',
    studentPopulation: '38 million',
    topUniversityCount: 45,
    educationSystem: 'Class 12 Boards, Bachelor\'s (3–4 yrs), Master\'s, PhD',
    currency: 'INR',
    languages: ['Hindi', 'English', 'Bengali', 'Tamil', 'Telugu'],
  },
  {
    name: 'Singapore',
    slug: 'singapore',
    continent: 'asia',
    capital: 'Singapore',
    studentPopulation: '185,000',
    topUniversityCount: 6,
    educationSystem: 'A-Levels/Polytechnic, Bachelor\'s (3–4 yrs), Master\'s, PhD',
    currency: 'SGD',
    languages: ['English', 'Mandarin', 'Malay', 'Tamil'],
  },
  {
    name: 'Malaysia',
    slug: 'malaysia',
    continent: 'asia',
    capital: 'Kuala Lumpur',
    studentPopulation: '1.2 million',
    topUniversityCount: 12,
    educationSystem: 'STPM/A-Levels, Bachelor\'s (3–4 yrs), Master\'s, PhD',
    currency: 'MYR',
    languages: ['Malay', 'English', 'Mandarin', 'Tamil'],
  },
  {
    name: 'Philippines',
    slug: 'philippines',
    continent: 'asia',
    capital: 'Manila',
    studentPopulation: '4.0 million',
    topUniversityCount: 5,
    educationSystem: 'Senior High School, Bachelor\'s (4 yrs), Master\'s, PhD',
    currency: 'PHP',
    languages: ['Filipino', 'English'],
  },
  {
    name: 'Pakistan',
    slug: 'pakistan',
    continent: 'asia',
    capital: 'Islamabad',
    studentPopulation: '2.2 million',
    topUniversityCount: 8,
    educationSystem: 'HSSC/A-Levels, Bachelor\'s (4 yrs), Master\'s, PhD',
    currency: 'PKR',
    languages: ['Urdu', 'English'],
  },
  {
    name: 'Bangladesh',
    slug: 'bangladesh',
    continent: 'asia',
    capital: 'Dhaka',
    studentPopulation: '4.0 million',
    topUniversityCount: 3,
    educationSystem: 'HSC, Bachelor\'s (4 yrs), Master\'s, PhD',
    currency: 'BDT',
    languages: ['Bengali', 'English'],
  },
  {
    name: 'Sri Lanka',
    slug: 'sri-lanka',
    continent: 'asia',
    capital: 'Colombo',
    studentPopulation: '400,000',
    topUniversityCount: 2,
    educationSystem: 'A-Levels, Bachelor\'s (3–4 yrs), Master\'s, PhD',
    currency: 'LKR',
    languages: ['Sinhala', 'Tamil', 'English'],
  },
  {
    name: 'Jamaica',
    slug: 'jamaica',
    continent: 'north-america',
    capital: 'Kingston',
    studentPopulation: '45,000',
    topUniversityCount: 1,
    educationSystem: 'CAPE/CSEC, Bachelor\'s (3 yrs), Master\'s, PhD',
    currency: 'JMD',
    languages: ['English'],
  },
  {
    name: 'Trinidad and Tobago',
    slug: 'trinidad-and-tobago',
    continent: 'north-america',
    capital: 'Port of Spain',
    studentPopulation: '50,000',
    topUniversityCount: 1,
    educationSystem: 'CAPE/CSEC, Bachelor\'s (3 yrs), Master\'s, PhD',
    currency: 'TTD',
    languages: ['English'],
  },
  {
    name: 'Barbados',
    slug: 'barbados',
    continent: 'north-america',
    capital: 'Bridgetown',
    studentPopulation: '15,000',
    topUniversityCount: 1,
    educationSystem: 'CAPE/CSEC, Bachelor\'s (3 yrs), Master\'s',
    currency: 'BBD',
    languages: ['English'],
  },
  {
    name: 'Bahamas',
    slug: 'bahamas',
    continent: 'north-america',
    capital: 'Nassau',
    studentPopulation: '8,000',
    topUniversityCount: 1,
    educationSystem: 'BGCSE, Associate\'s, Bachelor\'s (4 yrs)',
    currency: 'BSD',
    languages: ['English'],
  },
  {
    name: 'Zimbabwe',
    slug: 'zimbabwe',
    continent: 'africa',
    capital: 'Harare',
    studentPopulation: '95,000',
    topUniversityCount: 1,
    educationSystem: 'A-Levels, Bachelor\'s (3–4 yrs), Master\'s, PhD',
    currency: 'ZWL',
    languages: ['English', 'Shona', 'Ndebele'],
  },
  {
    name: 'Zambia',
    slug: 'zambia',
    continent: 'africa',
    capital: 'Lusaka',
    studentPopulation: '110,000',
    topUniversityCount: 1,
    educationSystem: 'Grade 12 Certificate, Bachelor\'s (4 yrs), Master\'s',
    currency: 'ZMW',
    languages: ['English'],
  },
  {
    name: 'Uganda',
    slug: 'uganda',
    continent: 'africa',
    capital: 'Kampala',
    studentPopulation: '210,000',
    topUniversityCount: 1,
    educationSystem: 'UACE, Bachelor\'s (3–4 yrs), Master\'s, PhD',
    currency: 'UGX',
    languages: ['English', 'Swahili'],
  },
  {
    name: 'Tanzania',
    slug: 'tanzania',
    continent: 'africa',
    capital: 'Dodoma',
    studentPopulation: '220,000',
    topUniversityCount: 1,
    educationSystem: 'ACSEE, Bachelor\'s (3 yrs), Master\'s, PhD',
    currency: 'TZS',
    languages: ['Swahili', 'English'],
  },
  {
    name: 'Botswana',
    slug: 'botswana',
    continent: 'africa',
    capital: 'Gaborone',
    studentPopulation: '35,000',
    topUniversityCount: 1,
    educationSystem: 'BGCSE, Bachelor\'s (4 yrs), Master\'s',
    currency: 'BWP',
    languages: ['English', 'Setswana'],
  },
  {
    name: 'Namibia',
    slug: 'namibia',
    continent: 'africa',
    capital: 'Windhoek',
    studentPopulation: '45,000',
    topUniversityCount: 1,
    educationSystem: 'NSSC, Bachelor\'s (4 yrs), Master\'s',
    currency: 'NAD',
    languages: ['English'],
  },
  {
    name: 'Cameroon',
    slug: 'cameroon',
    continent: 'africa',
    capital: 'Yaounde',
    studentPopulation: '330,000',
    topUniversityCount: 1,
    educationSystem: 'GCE A-Level/Baccalauréat, Bachelor\'s (3 yrs), Master\'s, PhD',
    currency: 'XAF',
    languages: ['English', 'French'],
  },
  {
    name: 'Rwanda',
    slug: 'rwanda',
    continent: 'africa',
    capital: 'Kigali',
    studentPopulation: '85,000',
    topUniversityCount: 1,
    educationSystem: 'AICE/A-Levels, Bachelor\'s (4 yrs), Master\'s, PhD',
    currency: 'RWF',
    languages: ['Kinyarwanda', 'English', 'French'],
  },

  // ── EUROPE ─────────────────────────────────────────────────────────────────

  {
    name: 'Germany',
    slug: 'germany',
    continent: 'europe',
    capital: 'Berlin',
    studentPopulation: '2.9 million',
    topUniversityCount: 48,
    educationSystem: 'Abitur, Bachelor\'s (3 yrs), Master\'s (2 yrs), PhD',
    currency: 'EUR',
    languages: ['German'],
  },
  {
    name: 'France',
    slug: 'france',
    continent: 'europe',
    capital: 'Paris',
    studentPopulation: '2.8 million',
    topUniversityCount: 35,
    educationSystem: 'Baccalauréat, Licence (3 yrs), Master (2 yrs), Doctorat',
    currency: 'EUR',
    languages: ['French'],
  },
  {
    name: 'Netherlands',
    slug: 'netherlands',
    continent: 'europe',
    capital: 'Amsterdam',
    studentPopulation: '820,000',
    topUniversityCount: 14,
    educationSystem: 'VWO/Atheneum, Bachelor\'s (3 yrs), Master\'s (1–2 yrs), PhD',
    currency: 'EUR',
    languages: ['Dutch', 'English'],
  },
  {
    name: 'Sweden',
    slug: 'sweden',
    continent: 'europe',
    capital: 'Stockholm',
    studentPopulation: '450,000',
    topUniversityCount: 12,
    educationSystem: 'Gymnasium, Bachelor\'s (3 yrs), Master\'s (2 yrs), PhD',
    currency: 'SEK',
    languages: ['Swedish', 'English'],
  },
  {
    name: 'Norway',
    slug: 'norway',
    continent: 'europe',
    capital: 'Oslo',
    studentPopulation: '280,000',
    topUniversityCount: 6,
    educationSystem: 'Videregående, Bachelor\'s (3 yrs), Master\'s (2 yrs), PhD',
    currency: 'NOK',
    languages: ['Norwegian', 'English'],
  },
  {
    name: 'Denmark',
    slug: 'denmark',
    continent: 'europe',
    capital: 'Copenhagen',
    studentPopulation: '260,000',
    topUniversityCount: 8,
    educationSystem: 'Gymnasium/STX, Bachelor\'s (3 yrs), Kandidat (2 yrs), PhD',
    currency: 'DKK',
    languages: ['Danish', 'English'],
  },
  {
    name: 'Finland',
    slug: 'finland',
    continent: 'europe',
    capital: 'Helsinki',
    studentPopulation: '290,000',
    topUniversityCount: 8,
    educationSystem: 'Ylioppilastutkinto, Bachelor\'s (3 yrs), Master\'s (2 yrs), PhD',
    currency: 'EUR',
    languages: ['Finnish', 'Swedish', 'English'],
  },
  {
    name: 'Switzerland',
    slug: 'switzerland',
    continent: 'europe',
    capital: 'Bern',
    studentPopulation: '280,000',
    topUniversityCount: 10,
    educationSystem: 'Maturität/Maturité, Bachelor\'s (3 yrs), Master\'s (1.5 yrs), PhD',
    currency: 'CHF',
    languages: ['German', 'French', 'Italian', 'Romansh'],
  },
  {
    name: 'Austria',
    slug: 'austria',
    continent: 'europe',
    capital: 'Vienna',
    studentPopulation: '370,000',
    topUniversityCount: 8,
    educationSystem: 'Matura, Bachelor\'s (3 yrs), Master\'s (2 yrs), PhD',
    currency: 'EUR',
    languages: ['German'],
  },
  {
    name: 'Belgium',
    slug: 'belgium',
    continent: 'europe',
    capital: 'Brussels',
    studentPopulation: '480,000',
    topUniversityCount: 9,
    educationSystem: 'Certificat d\'enseignement secondaire/ASO, Bachelor\'s (3 yrs), Master\'s (2 yrs), PhD',
    currency: 'EUR',
    languages: ['Dutch', 'French', 'German'],
  },
  {
    name: 'Spain',
    slug: 'spain',
    continent: 'europe',
    capital: 'Madrid',
    studentPopulation: '1.6 million',
    topUniversityCount: 15,
    educationSystem: 'Bachillerato/Selectividad, Grado (4 yrs), Master (1–2 yrs), Doctorado',
    currency: 'EUR',
    languages: ['Spanish', 'Catalan', 'Basque', 'Galician'],
  },
  {
    name: 'Portugal',
    slug: 'portugal',
    continent: 'europe',
    capital: 'Lisbon',
    studentPopulation: '400,000',
    topUniversityCount: 7,
    educationSystem: 'Exames Nacionais, Licenciatura (3 yrs), Mestrado (2 yrs), Doutoramento',
    currency: 'EUR',
    languages: ['Portuguese'],
  },
  {
    name: 'Italy',
    slug: 'italy',
    continent: 'europe',
    capital: 'Rome',
    studentPopulation: '1.8 million',
    topUniversityCount: 22,
    educationSystem: 'Esame di Stato, Laurea Triennale (3 yrs), Laurea Magistrale (2 yrs), Dottorato',
    currency: 'EUR',
    languages: ['Italian'],
  },
  {
    name: 'Poland',
    slug: 'poland',
    continent: 'europe',
    capital: 'Warsaw',
    studentPopulation: '1.2 million',
    topUniversityCount: 8,
    educationSystem: 'Matura, Licencjat (3 yrs), Magister (2 yrs), Doktorat',
    currency: 'PLN',
    languages: ['Polish'],
  },
  {
    name: 'Czech Republic',
    slug: 'czech-republic',
    continent: 'europe',
    capital: 'Prague',
    studentPopulation: '370,000',
    topUniversityCount: 4,
    educationSystem: 'Maturitní zkouška, Bakalář (3 yrs), Magistr (2 yrs), PhD',
    currency: 'CZK',
    languages: ['Czech'],
  },
  {
    name: 'Hungary',
    slug: 'hungary',
    continent: 'europe',
    capital: 'Budapest',
    studentPopulation: '290,000',
    topUniversityCount: 4,
    educationSystem: 'Érettségi, Bachelor (3 yrs), Master (2 yrs), PhD',
    currency: 'HUF',
    languages: ['Hungarian'],
  },
  {
    name: 'Romania',
    slug: 'romania',
    continent: 'europe',
    capital: 'Bucharest',
    studentPopulation: '500,000',
    topUniversityCount: 3,
    educationSystem: 'Bacalaureat, Licenţă (3 yrs), Masterat (2 yrs), Doctorat',
    currency: 'RON',
    languages: ['Romanian'],
  },
  {
    name: 'Greece',
    slug: 'greece',
    continent: 'europe',
    capital: 'Athens',
    studentPopulation: '310,000',
    topUniversityCount: 4,
    educationSystem: 'Apolytirion, Ptychion (4 yrs), Master (2 yrs), Didaktoriko',
    currency: 'EUR',
    languages: ['Greek'],
  },
  {
    name: 'Turkey',
    slug: 'turkey',
    continent: 'europe',
    capital: 'Ankara',
    studentPopulation: '7.8 million',
    topUniversityCount: 10,
    educationSystem: 'YKS exam, Lisans (4 yrs), Yüksek Lisans (2 yrs), Doktora',
    currency: 'TRY',
    languages: ['Turkish'],
  },

  // ── MIDDLE EAST ────────────────────────────────────────────────────────────

  {
    name: 'Israel',
    slug: 'israel',
    continent: 'middle-east',
    capital: 'Jerusalem',
    studentPopulation: '340,000',
    topUniversityCount: 8,
    educationSystem: 'Bagrut, Bachelor\'s (3 yrs), Master\'s (2 yrs), PhD',
    currency: 'ILS',
    languages: ['Hebrew', 'Arabic', 'English'],
  },
  {
    name: 'UAE',
    slug: 'uae',
    continent: 'middle-east',
    capital: 'Abu Dhabi',
    studentPopulation: '175,000',
    topUniversityCount: 5,
    educationSystem: 'EmSAT/Tawjihi, Bachelor\'s (4 yrs), Master\'s, PhD',
    currency: 'AED',
    languages: ['Arabic', 'English'],
  },
  {
    name: 'Saudi Arabia',
    slug: 'saudi-arabia',
    continent: 'middle-east',
    capital: 'Riyadh',
    studentPopulation: '1.9 million',
    topUniversityCount: 6,
    educationSystem: 'Tawjihi, Bachelor\'s (4 yrs), Master\'s (2 yrs), PhD',
    currency: 'SAR',
    languages: ['Arabic'],
  },
  {
    name: 'Egypt',
    slug: 'egypt',
    continent: 'africa',
    capital: 'Cairo',
    studentPopulation: '3.1 million',
    topUniversityCount: 5,
    educationSystem: 'Thanaweya Amma, Bachelor\'s (4–5 yrs), Master\'s, PhD',
    currency: 'EGP',
    languages: ['Arabic', 'English'],
  },
  {
    name: 'Morocco',
    slug: 'morocco',
    continent: 'africa',
    capital: 'Rabat',
    studentPopulation: '1.0 million',
    topUniversityCount: 3,
    educationSystem: 'Baccalauréat, Licence (3 yrs), Master (2 yrs), Doctorat',
    currency: 'MAD',
    languages: ['Arabic', 'French', 'Berber'],
  },
  {
    name: 'Lebanon',
    slug: 'lebanon',
    continent: 'middle-east',
    capital: 'Beirut',
    studentPopulation: '215,000',
    topUniversityCount: 2,
    educationSystem: 'Baccalauréat/Official Exams, Bachelor\'s (3–4 yrs), Master\'s, PhD',
    currency: 'LBP',
    languages: ['Arabic', 'French', 'English'],
  },

  // ── ASIA ───────────────────────────────────────────────────────────────────

  {
    name: 'Japan',
    slug: 'japan',
    continent: 'asia',
    capital: 'Tokyo',
    studentPopulation: '2.9 million',
    topUniversityCount: 20,
    educationSystem: 'Daigaku Nyushi (CSAT), Bachelor\'s (4 yrs), Master\'s (2 yrs), PhD (3 yrs)',
    currency: 'JPY',
    languages: ['Japanese'],
  },
  {
    name: 'South Korea',
    slug: 'south-korea',
    continent: 'asia',
    capital: 'Seoul',
    studentPopulation: '3.2 million',
    topUniversityCount: 18,
    educationSystem: 'CSAT (Suneung), Bachelor\'s (4 yrs), Master\'s (2 yrs), PhD (3 yrs)',
    currency: 'KRW',
    languages: ['Korean'],
  },
  {
    name: 'China',
    slug: 'china',
    continent: 'asia',
    capital: 'Beijing',
    studentPopulation: '44 million',
    topUniversityCount: 58,
    educationSystem: 'Gaokao, Bachelor\'s (4 yrs), Master\'s (2–3 yrs), PhD',
    currency: 'CNY',
    languages: ['Mandarin'],
  },
  {
    name: 'Taiwan',
    slug: 'taiwan',
    continent: 'asia',
    capital: 'Taipei',
    studentPopulation: '1.0 million',
    topUniversityCount: 10,
    educationSystem: 'GSAT/AST, Bachelor\'s (4 yrs), Master\'s (2 yrs), PhD',
    currency: 'TWD',
    languages: ['Mandarin', 'Taiwanese'],
  },
  {
    name: 'Indonesia',
    slug: 'indonesia',
    continent: 'asia',
    capital: 'Jakarta',
    studentPopulation: '9.0 million',
    topUniversityCount: 8,
    educationSystem: 'SNMPTN/SBMPTN, Sarjana (4 yrs), Magister (2 yrs), Doktor',
    currency: 'IDR',
    languages: ['Indonesian'],
  },
  {
    name: 'Vietnam',
    slug: 'vietnam',
    continent: 'asia',
    capital: 'Hanoi',
    studentPopulation: '2.1 million',
    topUniversityCount: 3,
    educationSystem: 'THPTQG exam, Cử nhân (4 yrs), Thạc sĩ (2 yrs), Tiến sĩ',
    currency: 'VND',
    languages: ['Vietnamese'],
  },
  {
    name: 'Thailand',
    slug: 'thailand',
    continent: 'asia',
    capital: 'Bangkok',
    studentPopulation: '2.5 million',
    topUniversityCount: 7,
    educationSystem: 'ONET/GAT/PAT, Bachelor\'s (4 yrs), Master\'s (2 yrs), PhD',
    currency: 'THB',
    languages: ['Thai'],
  },
  {
    name: 'Myanmar',
    slug: 'myanmar',
    continent: 'asia',
    capital: 'Naypyidaw',
    studentPopulation: '650,000',
    topUniversityCount: 1,
    educationSystem: 'Matriculation Exam, Bachelor\'s (3–5 yrs), Master\'s, PhD',
    currency: 'MMK',
    languages: ['Burmese', 'English'],
  },
  {
    name: 'Nepal',
    slug: 'nepal',
    continent: 'asia',
    capital: 'Kathmandu',
    studentPopulation: '500,000',
    topUniversityCount: 1,
    educationSystem: '+2 (NEB), Bachelor\'s (4 yrs), Master\'s (2 yrs), PhD',
    currency: 'NPR',
    languages: ['Nepali', 'English'],
  },
  {
    name: 'Kazakhstan',
    slug: 'kazakhstan',
    continent: 'asia',
    capital: 'Astana',
    studentPopulation: '620,000',
    topUniversityCount: 3,
    educationSystem: 'ENT exam, Bachelor\'s (4 yrs), Master\'s (2 yrs), PhD',
    currency: 'KZT',
    languages: ['Kazakh', 'Russian'],
  },
  {
    name: 'Hong Kong',
    slug: 'hong-kong',
    continent: 'asia',
    capital: 'Hong Kong',
    studentPopulation: '340,000',
    topUniversityCount: 7,
    educationSystem: 'HKDSE, Bachelor\'s (4 yrs), Master\'s (1–2 yrs), PhD',
    currency: 'HKD',
    languages: ['Cantonese', 'English', 'Mandarin'],
  },

  // ── SOUTH AMERICA ──────────────────────────────────────────────────────────

  {
    name: 'Brazil',
    slug: 'brazil',
    continent: 'south-america',
    capital: 'Brasilia',
    studentPopulation: '8.9 million',
    topUniversityCount: 18,
    educationSystem: 'ENEM, Bacharelado (4–5 yrs), Mestrado (2 yrs), Doutorado',
    currency: 'BRL',
    languages: ['Portuguese'],
  },
  {
    name: 'Mexico',
    slug: 'mexico',
    continent: 'north-america',
    capital: 'Mexico City',
    studentPopulation: '4.4 million',
    topUniversityCount: 8,
    educationSystem: 'Bachillerato, Licenciatura (4 yrs), Maestría (2 yrs), Doctorado',
    currency: 'MXN',
    languages: ['Spanish'],
  },
  {
    name: 'Argentina',
    slug: 'argentina',
    continent: 'south-america',
    capital: 'Buenos Aires',
    studentPopulation: '2.6 million',
    topUniversityCount: 6,
    educationSystem: 'Bachillerato, Licenciatura (4–5 yrs), Maestría (2 yrs), Doctorado',
    currency: 'ARS',
    languages: ['Spanish'],
  },
  {
    name: 'Colombia',
    slug: 'colombia',
    continent: 'south-america',
    capital: 'Bogota',
    studentPopulation: '2.3 million',
    topUniversityCount: 5,
    educationSystem: 'Saber 11, Pregrado (4–5 yrs), Maestría (2 yrs), Doctorado',
    currency: 'COP',
    languages: ['Spanish'],
  },
  {
    name: 'Chile',
    slug: 'chile',
    continent: 'south-america',
    capital: 'Santiago',
    studentPopulation: '1.2 million',
    topUniversityCount: 6,
    educationSystem: 'PDT/PAES exam, Pregrado (4–5 yrs), Magister (2 yrs), Doctorado',
    currency: 'CLP',
    languages: ['Spanish'],
  },
  {
    name: 'Peru',
    slug: 'peru',
    continent: 'south-america',
    capital: 'Lima',
    studentPopulation: '1.5 million',
    topUniversityCount: 3,
    educationSystem: 'Bachillerato, Licenciatura (5 yrs), Maestría (2 yrs), Doctorado',
    currency: 'PEN',
    languages: ['Spanish', 'Quechua'],
  },
  {
    name: 'Ecuador',
    slug: 'ecuador',
    continent: 'south-america',
    capital: 'Quito',
    studentPopulation: '680,000',
    topUniversityCount: 2,
    educationSystem: 'Ser Bachiller exam, Licenciatura (4–5 yrs), Maestría (2 yrs)',
    currency: 'USD',
    languages: ['Spanish', 'Quechua'],
  },
  {
    name: 'Venezuela',
    slug: 'venezuela',
    continent: 'south-america',
    capital: 'Caracas',
    studentPopulation: '1.3 million',
    topUniversityCount: 2,
    educationSystem: 'Bachillerato, Licenciatura (5 yrs), Maestría (2 yrs)',
    currency: 'VES',
    languages: ['Spanish'],
  },
  {
    name: 'Uruguay',
    slug: 'uruguay',
    continent: 'south-america',
    capital: 'Montevideo',
    studentPopulation: '175,000',
    topUniversityCount: 1,
    educationSystem: 'Bachillerato, Licenciatura (4–5 yrs), Maestría (2 yrs)',
    currency: 'UYU',
    languages: ['Spanish'],
  },
  {
    name: 'Costa Rica',
    slug: 'costa-rica',
    continent: 'north-america',
    capital: 'San Jose',
    studentPopulation: '220,000',
    topUniversityCount: 1,
    educationSystem: 'Bachillerato, Licenciatura (4 yrs), Maestría (2 yrs)',
    currency: 'CRC',
    languages: ['Spanish'],
  },
  {
    name: 'Panama',
    slug: 'panama',
    continent: 'north-america',
    capital: 'Panama City',
    studentPopulation: '135,000',
    topUniversityCount: 1,
    educationSystem: 'Bachillerato, Licenciatura (4 yrs), Maestría (2 yrs)',
    currency: 'USD',
    languages: ['Spanish', 'English'],
  },

  // ── AFRICA ─────────────────────────────────────────────────────────────────

  {
    name: 'Ethiopia',
    slug: 'ethiopia',
    continent: 'africa',
    capital: 'Addis Ababa',
    studentPopulation: '950,000',
    topUniversityCount: 2,
    educationSystem: 'Ethiopian University Entrance Exam, Bachelor\'s (3–4 yrs), Master\'s',
    currency: 'ETB',
    languages: ['Amharic', 'English'],
  },
  {
    name: 'Senegal',
    slug: 'senegal',
    continent: 'africa',
    capital: 'Dakar',
    studentPopulation: '180,000',
    topUniversityCount: 1,
    educationSystem: 'Baccalauréat, Licence (3 yrs), Master (2 yrs), Doctorat',
    currency: 'XOF',
    languages: ['French', 'Wolof'],
  },
  {
    name: 'Ivory Coast',
    slug: 'ivory-coast',
    continent: 'africa',
    capital: 'Yamoussoukro',
    studentPopulation: '270,000',
    topUniversityCount: 1,
    educationSystem: 'Baccalauréat, Licence (3 yrs), Master (2 yrs), Doctorat',
    currency: 'XOF',
    languages: ['French'],
  },
];

export function getCountryBySlug(slug: string): Country | undefined {
  return countries.find((c) => c.slug === slug);
}

export function getAllCountrySlugs(): { country: string }[] {
  return countries.map((c) => ({ country: c.slug }));
}

export function getCountriesByContinent(continent: string): Country[] {
  return countries.filter((c) => c.continent === continent);
}
