export interface SchoolDistrict {
  name: string;
  slug: string;
  state: string;
  stateSlug: string;
  city: string;
  enrollment: number;
  schoolCount: number;
}

export const districts: SchoolDistrict[] = [
  // ── ALABAMA ──
  {
    name: "Jefferson County Schools",
    slug: "jefferson-county-schools-al",
    state: "AL",
    stateSlug: "alabama",
    city: "Birmingham",
    enrollment: 35000,
    schoolCount: 56,
  },
  {
    name: "Mobile County Public Schools",
    slug: "mobile-county-public-schools",
    state: "AL",
    stateSlug: "alabama",
    city: "Mobile",
    enrollment: 55000,
    schoolCount: 92,
  },
  {
    name: "Huntsville City Schools",
    slug: "huntsville-city-schools",
    state: "AL",
    stateSlug: "alabama",
    city: "Huntsville",
    enrollment: 24000,
    schoolCount: 39,
  },
  {
    name: "Madison City Schools",
    slug: "madison-city-schools",
    state: "AL",
    stateSlug: "alabama",
    city: "Madison",
    enrollment: 13000,
    schoolCount: 18,
  },

  // ── ALASKA ──
  {
    name: "Anchorage School District",
    slug: "anchorage-school-district",
    state: "AK",
    stateSlug: "alaska",
    city: "Anchorage",
    enrollment: 45000,
    schoolCount: 104,
  },
  {
    name: "Fairbanks North Star Borough School District",
    slug: "fairbanks-north-star-borough-school-district",
    state: "AK",
    stateSlug: "alaska",
    city: "Fairbanks",
    enrollment: 13500,
    schoolCount: 34,
  },

  // ── ARIZONA ──
  {
    name: "Mesa Unified School District",
    slug: "mesa-unified-school-district",
    state: "AZ",
    stateSlug: "arizona",
    city: "Mesa",
    enrollment: 63000,
    schoolCount: 100,
  },
  {
    name: "Tucson Unified School District",
    slug: "tucson-unified-school-district",
    state: "AZ",
    stateSlug: "arizona",
    city: "Tucson",
    enrollment: 47000,
    schoolCount: 87,
  },
  {
    name: "Chandler Unified School District",
    slug: "chandler-unified-school-district",
    state: "AZ",
    stateSlug: "arizona",
    city: "Chandler",
    enrollment: 44000,
    schoolCount: 56,
  },
  {
    name: "Gilbert Unified School District",
    slug: "gilbert-unified-school-district",
    state: "AZ",
    stateSlug: "arizona",
    city: "Gilbert",
    enrollment: 40000,
    schoolCount: 51,
  },
  {
    name: "Peoria Unified School District",
    slug: "peoria-unified-school-district",
    state: "AZ",
    stateSlug: "arizona",
    city: "Peoria",
    enrollment: 38000,
    schoolCount: 52,
  },
  {
    name: "Paradise Valley Unified School District",
    slug: "paradise-valley-unified-school-district",
    state: "AZ",
    stateSlug: "arizona",
    city: "Phoenix",
    enrollment: 32000,
    schoolCount: 42,
  },
  {
    name: "Scottsdale Unified School District",
    slug: "scottsdale-unified-school-district",
    state: "AZ",
    stateSlug: "arizona",
    city: "Scottsdale",
    enrollment: 22000,
    schoolCount: 31,
  },
  {
    name: "Tempe Union High School District",
    slug: "tempe-union-high-school-district",
    state: "AZ",
    stateSlug: "arizona",
    city: "Tempe",
    enrollment: 14000,
    schoolCount: 9,
  },

  // ── ARKANSAS ──
  {
    name: "Little Rock School District",
    slug: "little-rock-school-district",
    state: "AR",
    stateSlug: "arkansas",
    city: "Little Rock",
    enrollment: 25000,
    schoolCount: 48,
  },
  {
    name: "Pulaski County Special School District",
    slug: "pulaski-county-special-school-district",
    state: "AR",
    stateSlug: "arkansas",
    city: "Little Rock",
    enrollment: 17000,
    schoolCount: 30,
  },

  // ── CALIFORNIA ──
  {
    name: "Los Angeles Unified School District",
    slug: "los-angeles-unified-school-district",
    state: "CA",
    stateSlug: "california",
    city: "Los Angeles",
    enrollment: 575000,
    schoolCount: 900,
  },
  {
    name: "San Diego Unified School District",
    slug: "san-diego-unified-school-district",
    state: "CA",
    stateSlug: "california",
    city: "San Diego",
    enrollment: 100000,
    schoolCount: 185,
  },
  {
    name: "Fresno Unified School District",
    slug: "fresno-unified-school-district",
    state: "CA",
    stateSlug: "california",
    city: "Fresno",
    enrollment: 70000,
    schoolCount: 110,
  },
  {
    name: "Long Beach Unified School District",
    slug: "long-beach-unified-school-district",
    state: "CA",
    stateSlug: "california",
    city: "Long Beach",
    enrollment: 70000,
    schoolCount: 94,
  },
  {
    name: "Elk Grove Unified School District",
    slug: "elk-grove-unified-school-district",
    state: "CA",
    stateSlug: "california",
    city: "Elk Grove",
    enrollment: 62000,
    schoolCount: 68,
  },
  {
    name: "San Francisco Unified School District",
    slug: "san-francisco-unified-school-district",
    state: "CA",
    stateSlug: "california",
    city: "San Francisco",
    enrollment: 50000,
    schoolCount: 130,
  },
  {
    name: "Corona-Norco Unified School District",
    slug: "corona-norco-unified-school-district",
    state: "CA",
    stateSlug: "california",
    city: "Norco",
    enrollment: 53000,
    schoolCount: 50,
  },
  {
    name: "Sacramento City Unified School District",
    slug: "sacramento-city-unified-school-district",
    state: "CA",
    stateSlug: "california",
    city: "Sacramento",
    enrollment: 40000,
    schoolCount: 78,
  },
  {
    name: "Oakland Unified School District",
    slug: "oakland-unified-school-district",
    state: "CA",
    stateSlug: "california",
    city: "Oakland",
    enrollment: 35000,
    schoolCount: 87,
  },
  {
    name: "Riverside Unified School District",
    slug: "riverside-unified-school-district",
    state: "CA",
    stateSlug: "california",
    city: "Riverside",
    enrollment: 40000,
    schoolCount: 47,
  },
  {
    name: "Stockton Unified School District",
    slug: "stockton-unified-school-district",
    state: "CA",
    stateSlug: "california",
    city: "Stockton",
    enrollment: 38000,
    schoolCount: 61,
  },
  {
    name: "Garden Grove Unified School District",
    slug: "garden-grove-unified-school-district",
    state: "CA",
    stateSlug: "california",
    city: "Garden Grove",
    enrollment: 38000,
    schoolCount: 68,
  },
  {
    name: "San Jose Unified School District",
    slug: "san-jose-unified-school-district",
    state: "CA",
    stateSlug: "california",
    city: "San Jose",
    enrollment: 30000,
    schoolCount: 42,
  },

  // ── COLORADO ──
  {
    name: "Denver Public Schools",
    slug: "denver-public-schools",
    state: "CO",
    stateSlug: "colorado",
    city: "Denver",
    enrollment: 90000,
    schoolCount: 207,
  },
  {
    name: "Jefferson County Public Schools",
    slug: "jefferson-county-public-schools-co",
    state: "CO",
    stateSlug: "colorado",
    city: "Golden",
    enrollment: 85000,
    schoolCount: 155,
  },
  {
    name: "Cherry Creek School District",
    slug: "cherry-creek-school-district",
    state: "CO",
    stateSlug: "colorado",
    city: "Greenwood Village",
    enrollment: 55000,
    schoolCount: 67,
  },
  {
    name: "Douglas County School District",
    slug: "douglas-county-school-district",
    state: "CO",
    stateSlug: "colorado",
    city: "Castle Rock",
    enrollment: 68000,
    schoolCount: 89,
  },
  {
    name: "Aurora Public Schools",
    slug: "aurora-public-schools",
    state: "CO",
    stateSlug: "colorado",
    city: "Aurora",
    enrollment: 40000,
    schoolCount: 57,
  },

  // ── CONNECTICUT ──
  {
    name: "Bridgeport Public Schools",
    slug: "bridgeport-public-schools",
    state: "CT",
    stateSlug: "connecticut",
    city: "Bridgeport",
    enrollment: 20000,
    schoolCount: 37,
  },
  {
    name: "Hartford Public Schools",
    slug: "hartford-public-schools",
    state: "CT",
    stateSlug: "connecticut",
    city: "Hartford",
    enrollment: 20000,
    schoolCount: 40,
  },
  {
    name: "New Haven Public Schools",
    slug: "new-haven-public-schools",
    state: "CT",
    stateSlug: "connecticut",
    city: "New Haven",
    enrollment: 20000,
    schoolCount: 44,
  },
  {
    name: "Waterbury Public Schools",
    slug: "waterbury-public-schools",
    state: "CT",
    stateSlug: "connecticut",
    city: "Waterbury",
    enrollment: 18500,
    schoolCount: 33,
  },

  // ── DELAWARE ──
  {
    name: "Christina School District",
    slug: "christina-school-district",
    state: "DE",
    stateSlug: "delaware",
    city: "Newark",
    enrollment: 16000,
    schoolCount: 33,
  },
  {
    name: "Red Clay Consolidated School District",
    slug: "red-clay-consolidated-school-district",
    state: "DE",
    stateSlug: "delaware",
    city: "Wilmington",
    enrollment: 15500,
    schoolCount: 30,
  },
  {
    name: "Brandywine School District",
    slug: "brandywine-school-district",
    state: "DE",
    stateSlug: "delaware",
    city: "Wilmington",
    enrollment: 11000,
    schoolCount: 19,
  },

  // ── DISTRICT OF COLUMBIA ──
  {
    name: "DC Public Schools",
    slug: "dc-public-schools",
    state: "DC",
    stateSlug: "district-of-columbia",
    city: "Washington",
    enrollment: 50000,
    schoolCount: 116,
  },

  // ── FLORIDA ──
  {
    name: "Miami-Dade County Public Schools",
    slug: "miami-dade-county-public-schools",
    state: "FL",
    stateSlug: "florida",
    city: "Miami",
    enrollment: 335000,
    schoolCount: 500,
  },
  {
    name: "Broward County Public Schools",
    slug: "broward-county-public-schools",
    state: "FL",
    stateSlug: "florida",
    city: "Fort Lauderdale",
    enrollment: 270000,
    schoolCount: 241,
  },
  {
    name: "Palm Beach County Schools",
    slug: "palm-beach-county-schools",
    state: "FL",
    stateSlug: "florida",
    city: "West Palm Beach",
    enrollment: 195000,
    schoolCount: 188,
  },
  {
    name: "Hillsborough County Public Schools",
    slug: "hillsborough-county-public-schools",
    state: "FL",
    stateSlug: "florida",
    city: "Tampa",
    enrollment: 225000,
    schoolCount: 259,
  },
  {
    name: "Orange County Public Schools",
    slug: "orange-county-public-schools",
    state: "FL",
    stateSlug: "florida",
    city: "Orlando",
    enrollment: 215000,
    schoolCount: 213,
  },
  {
    name: "Pinellas County Schools",
    slug: "pinellas-county-schools",
    state: "FL",
    stateSlug: "florida",
    city: "Largo",
    enrollment: 101000,
    schoolCount: 140,
  },
  {
    name: "Duval County Public Schools",
    slug: "duval-county-public-schools",
    state: "FL",
    stateSlug: "florida",
    city: "Jacksonville",
    enrollment: 127000,
    schoolCount: 197,
  },
  {
    name: "Polk County Public Schools",
    slug: "polk-county-public-schools",
    state: "FL",
    stateSlug: "florida",
    city: "Bartow",
    enrollment: 109000,
    schoolCount: 148,
  },
  {
    name: "Brevard Public Schools",
    slug: "brevard-public-schools",
    state: "FL",
    stateSlug: "florida",
    city: "Viera",
    enrollment: 75000,
    schoolCount: 104,
  },
  {
    name: "Volusia County Schools",
    slug: "volusia-county-schools",
    state: "FL",
    stateSlug: "florida",
    city: "DeLand",
    enrollment: 65000,
    schoolCount: 93,
  },

  // ── GEORGIA ──
  {
    name: "Gwinnett County Public Schools",
    slug: "gwinnett-county-public-schools",
    state: "GA",
    stateSlug: "georgia",
    city: "Suwanee",
    enrollment: 185000,
    schoolCount: 141,
  },
  {
    name: "DeKalb County School District",
    slug: "dekalb-county-school-district",
    state: "GA",
    stateSlug: "georgia",
    city: "Stone Mountain",
    enrollment: 100000,
    schoolCount: 135,
  },
  {
    name: "Cobb County School District",
    slug: "cobb-county-school-district",
    state: "GA",
    stateSlug: "georgia",
    city: "Marietta",
    enrollment: 111000,
    schoolCount: 115,
  },
  {
    name: "Clayton County Public Schools",
    slug: "clayton-county-public-schools",
    state: "GA",
    stateSlug: "georgia",
    city: "Jonesboro",
    enrollment: 55000,
    schoolCount: 64,
  },
  {
    name: "Atlanta Public Schools",
    slug: "atlanta-public-schools",
    state: "GA",
    stateSlug: "georgia",
    city: "Atlanta",
    enrollment: 50000,
    schoolCount: 87,
  },
  {
    name: "Richmond County School System",
    slug: "richmond-county-school-system",
    state: "GA",
    stateSlug: "georgia",
    city: "Augusta",
    enrollment: 30000,
    schoolCount: 56,
  },

  // ── HAWAII ──
  {
    name: "Hawaii Department of Education",
    slug: "hawaii-department-of-education",
    state: "HI",
    stateSlug: "hawaii",
    city: "Honolulu",
    enrollment: 175000,
    schoolCount: 290,
  },

  // ── IDAHO ──
  {
    name: "Meridian Joint School District",
    slug: "meridian-joint-school-district",
    state: "ID",
    stateSlug: "idaho",
    city: "Meridian",
    enrollment: 43000,
    schoolCount: 52,
  },
  {
    name: "Boise School District",
    slug: "boise-school-district",
    state: "ID",
    stateSlug: "idaho",
    city: "Boise",
    enrollment: 34000,
    schoolCount: 52,
  },
  {
    name: "Nampa School District",
    slug: "nampa-school-district",
    state: "ID",
    stateSlug: "idaho",
    city: "Nampa",
    enrollment: 17000,
    schoolCount: 22,
  },

  // ── ILLINOIS ──
  {
    name: "Chicago Public Schools",
    slug: "chicago-public-schools",
    state: "IL",
    stateSlug: "illinois",
    city: "Chicago",
    enrollment: 325000,
    schoolCount: 634,
  },
  {
    name: "Community Unit School District 300",
    slug: "community-unit-school-district-300",
    state: "IL",
    stateSlug: "illinois",
    city: "Carpentersville",
    enrollment: 21000,
    schoolCount: 24,
  },
  {
    name: "Rockford Public Schools",
    slug: "rockford-public-schools",
    state: "IL",
    stateSlug: "illinois",
    city: "Rockford",
    enrollment: 28000,
    schoolCount: 51,
  },

  // ── INDIANA ──
  {
    name: "Indianapolis Public Schools",
    slug: "indianapolis-public-schools",
    state: "IN",
    stateSlug: "indiana",
    city: "Indianapolis",
    enrollment: 30000,
    schoolCount: 67,
  },
  {
    name: "MSD of Washington Township",
    slug: "msd-of-washington-township",
    state: "IN",
    stateSlug: "indiana",
    city: "Indianapolis",
    enrollment: 11000,
    schoolCount: 17,
  },
  {
    name: "Fort Wayne Community Schools",
    slug: "fort-wayne-community-schools",
    state: "IN",
    stateSlug: "indiana",
    city: "Fort Wayne",
    enrollment: 31000,
    schoolCount: 51,
  },

  // ── IOWA ──
  {
    name: "Des Moines Public Schools",
    slug: "des-moines-public-schools",
    state: "IA",
    stateSlug: "iowa",
    city: "Des Moines",
    enrollment: 32000,
    schoolCount: 62,
  },
  {
    name: "Cedar Rapids Community School District",
    slug: "cedar-rapids-community-school-district",
    state: "IA",
    stateSlug: "iowa",
    city: "Cedar Rapids",
    enrollment: 17000,
    schoolCount: 35,
  },
  {
    name: "Davenport Community School District",
    slug: "davenport-community-school-district",
    state: "IA",
    stateSlug: "iowa",
    city: "Davenport",
    enrollment: 15000,
    schoolCount: 29,
  },

  // ── KANSAS ──
  {
    name: "Wichita Public Schools",
    slug: "wichita-public-schools",
    state: "KS",
    stateSlug: "kansas",
    city: "Wichita",
    enrollment: 50000,
    schoolCount: 95,
  },
  {
    name: "Shawnee Mission School District",
    slug: "shawnee-mission-school-district",
    state: "KS",
    stateSlug: "kansas",
    city: "Overland Park",
    enrollment: 28000,
    schoolCount: 40,
  },
  {
    name: "Blue Valley School District",
    slug: "blue-valley-school-district",
    state: "KS",
    stateSlug: "kansas",
    city: "Overland Park",
    enrollment: 22000,
    schoolCount: 28,
  },

  // ── KENTUCKY ──
  {
    name: "Jefferson County Public Schools",
    slug: "jefferson-county-public-schools-ky",
    state: "KY",
    stateSlug: "kentucky",
    city: "Louisville",
    enrollment: 96000,
    schoolCount: 174,
  },
  {
    name: "Fayette County Public Schools",
    slug: "fayette-county-public-schools",
    state: "KY",
    stateSlug: "kentucky",
    city: "Lexington",
    enrollment: 41000,
    schoolCount: 67,
  },

  // ── LOUISIANA ──
  {
    name: "New Orleans Public Schools",
    slug: "new-orleans-public-schools",
    state: "LA",
    stateSlug: "louisiana",
    city: "New Orleans",
    enrollment: 45000,
    schoolCount: 84,
  },
  {
    name: "East Baton Rouge Parish Schools",
    slug: "east-baton-rouge-parish-schools",
    state: "LA",
    stateSlug: "louisiana",
    city: "Baton Rouge",
    enrollment: 40000,
    schoolCount: 86,
  },
  {
    name: "Jefferson Parish Schools",
    slug: "jefferson-parish-schools",
    state: "LA",
    stateSlug: "louisiana",
    city: "Metairie",
    enrollment: 47000,
    schoolCount: 83,
  },
  {
    name: "St. Tammany Parish Schools",
    slug: "st-tammany-parish-schools",
    state: "LA",
    stateSlug: "louisiana",
    city: "Covington",
    enrollment: 38000,
    schoolCount: 54,
  },

  // ── MAINE ──
  {
    name: "Portland Public Schools",
    slug: "portland-public-schools-me",
    state: "ME",
    stateSlug: "maine",
    city: "Portland",
    enrollment: 7000,
    schoolCount: 16,
  },
  {
    name: "Auburn School Department",
    slug: "auburn-school-department",
    state: "ME",
    stateSlug: "maine",
    city: "Auburn",
    enrollment: 4500,
    schoolCount: 10,
  },

  // ── MARYLAND ──
  {
    name: "Montgomery County Public Schools",
    slug: "montgomery-county-public-schools",
    state: "MD",
    stateSlug: "maryland",
    city: "Rockville",
    enrollment: 160000,
    schoolCount: 205,
  },
  {
    name: "Prince George's County Public Schools",
    slug: "prince-georges-county-public-schools",
    state: "MD",
    stateSlug: "maryland",
    city: "Upper Marlboro",
    enrollment: 130000,
    schoolCount: 208,
  },
  {
    name: "Baltimore County Public Schools",
    slug: "baltimore-county-public-schools",
    state: "MD",
    stateSlug: "maryland",
    city: "Towson",
    enrollment: 114000,
    schoolCount: 172,
  },
  {
    name: "Baltimore City Public Schools",
    slug: "baltimore-city-public-schools",
    state: "MD",
    stateSlug: "maryland",
    city: "Baltimore",
    enrollment: 77000,
    schoolCount: 160,
  },
  {
    name: "Howard County Public Schools",
    slug: "howard-county-public-schools",
    state: "MD",
    stateSlug: "maryland",
    city: "Ellicott City",
    enrollment: 58000,
    schoolCount: 77,
  },
  {
    name: "Anne Arundel County Public Schools",
    slug: "anne-arundel-county-public-schools",
    state: "MD",
    stateSlug: "maryland",
    city: "Annapolis",
    enrollment: 82000,
    schoolCount: 128,
  },

  // ── MASSACHUSETTS ──
  {
    name: "Boston Public Schools",
    slug: "boston-public-schools",
    state: "MA",
    stateSlug: "massachusetts",
    city: "Boston",
    enrollment: 51000,
    schoolCount: 130,
  },
  {
    name: "Worcester Public Schools",
    slug: "worcester-public-schools",
    state: "MA",
    stateSlug: "massachusetts",
    city: "Worcester",
    enrollment: 26000,
    schoolCount: 48,
  },
  {
    name: "Springfield Public Schools",
    slug: "springfield-public-schools",
    state: "MA",
    stateSlug: "massachusetts",
    city: "Springfield",
    enrollment: 25000,
    schoolCount: 56,
  },
  {
    name: "Brockton Public Schools",
    slug: "brockton-public-schools",
    state: "MA",
    stateSlug: "massachusetts",
    city: "Brockton",
    enrollment: 17000,
    schoolCount: 28,
  },
  {
    name: "Lowell Public Schools",
    slug: "lowell-public-schools",
    state: "MA",
    stateSlug: "massachusetts",
    city: "Lowell",
    enrollment: 15000,
    schoolCount: 27,
  },

  // ── MICHIGAN ──
  {
    name: "Detroit Public Schools Community District",
    slug: "detroit-public-schools-community-district",
    state: "MI",
    stateSlug: "michigan",
    city: "Detroit",
    enrollment: 51000,
    schoolCount: 106,
  },
  {
    name: "Grand Rapids Public Schools",
    slug: "grand-rapids-public-schools",
    state: "MI",
    stateSlug: "michigan",
    city: "Grand Rapids",
    enrollment: 16000,
    schoolCount: 38,
  },
  {
    name: "Dearborn City School District",
    slug: "dearborn-city-school-district",
    state: "MI",
    stateSlug: "michigan",
    city: "Dearborn",
    enrollment: 19000,
    schoolCount: 31,
  },
  {
    name: "Lansing School District",
    slug: "lansing-school-district",
    state: "MI",
    stateSlug: "michigan",
    city: "Lansing",
    enrollment: 11000,
    schoolCount: 28,
  },

  // ── MINNESOTA ──
  {
    name: "Anoka-Hennepin School District",
    slug: "anoka-hennepin-school-district",
    state: "MN",
    stateSlug: "minnesota",
    city: "Coon Rapids",
    enrollment: 38000,
    schoolCount: 57,
  },
  {
    name: "St. Paul Public Schools",
    slug: "st-paul-public-schools",
    state: "MN",
    stateSlug: "minnesota",
    city: "Saint Paul",
    enrollment: 36000,
    schoolCount: 72,
  },
  {
    name: "Minneapolis Public Schools",
    slug: "minneapolis-public-schools",
    state: "MN",
    stateSlug: "minnesota",
    city: "Minneapolis",
    enrollment: 34000,
    schoolCount: 74,
  },
  {
    name: "Osseo School District",
    slug: "osseo-school-district",
    state: "MN",
    stateSlug: "minnesota",
    city: "Osseo",
    enrollment: 22000,
    schoolCount: 32,
  },

  // ── MISSISSIPPI ──
  {
    name: "Jackson Public Schools",
    slug: "jackson-public-schools",
    state: "MS",
    stateSlug: "mississippi",
    city: "Jackson",
    enrollment: 25000,
    schoolCount: 55,
  },
  {
    name: "DeSoto County Schools",
    slug: "desoto-county-schools",
    state: "MS",
    stateSlug: "mississippi",
    city: "Hernando",
    enrollment: 35000,
    schoolCount: 44,
  },

  // ── MISSOURI ──
  {
    name: "Kansas City Public Schools",
    slug: "kansas-city-public-schools",
    state: "MO",
    stateSlug: "missouri",
    city: "Kansas City",
    enrollment: 15000,
    schoolCount: 44,
  },
  {
    name: "Springfield R-XII Schools",
    slug: "springfield-r-xii-schools",
    state: "MO",
    stateSlug: "missouri",
    city: "Springfield",
    enrollment: 25000,
    schoolCount: 53,
  },
  {
    name: "St. Louis Public Schools",
    slug: "st-louis-public-schools",
    state: "MO",
    stateSlug: "missouri",
    city: "St. Louis",
    enrollment: 19000,
    schoolCount: 65,
  },
  {
    name: "Rockwood School District",
    slug: "rockwood-school-district",
    state: "MO",
    stateSlug: "missouri",
    city: "Eureka",
    enrollment: 22000,
    schoolCount: 30,
  },

  // ── MONTANA ──
  {
    name: "Billings Public Schools",
    slug: "billings-public-schools",
    state: "MT",
    stateSlug: "montana",
    city: "Billings",
    enrollment: 17000,
    schoolCount: 33,
  },
  {
    name: "Great Falls Public Schools",
    slug: "great-falls-public-schools",
    state: "MT",
    stateSlug: "montana",
    city: "Great Falls",
    enrollment: 9500,
    schoolCount: 20,
  },

  // ── NEBRASKA ──
  {
    name: "Omaha Public Schools",
    slug: "omaha-public-schools",
    state: "NE",
    stateSlug: "nebraska",
    city: "Omaha",
    enrollment: 54000,
    schoolCount: 87,
  },
  {
    name: "Lincoln Public Schools",
    slug: "lincoln-public-schools",
    state: "NE",
    stateSlug: "nebraska",
    city: "Lincoln",
    enrollment: 42000,
    schoolCount: 63,
  },
  {
    name: "Westside Community Schools",
    slug: "westside-community-schools",
    state: "NE",
    stateSlug: "nebraska",
    city: "Omaha",
    enrollment: 6500,
    schoolCount: 10,
  },

  // ── NEVADA ──
  {
    name: "Clark County School District",
    slug: "clark-county-school-district",
    state: "NV",
    stateSlug: "nevada",
    city: "Las Vegas",
    enrollment: 320000,
    schoolCount: 369,
  },
  {
    name: "Washoe County School District",
    slug: "washoe-county-school-district",
    state: "NV",
    stateSlug: "nevada",
    city: "Reno",
    enrollment: 65000,
    schoolCount: 100,
  },

  // ── NEW HAMPSHIRE ──
  {
    name: "Manchester School District",
    slug: "manchester-school-district",
    state: "NH",
    stateSlug: "new-hampshire",
    city: "Manchester",
    enrollment: 14000,
    schoolCount: 24,
  },
  {
    name: "Nashua School District",
    slug: "nashua-school-district",
    state: "NH",
    stateSlug: "new-hampshire",
    city: "Nashua",
    enrollment: 13000,
    schoolCount: 21,
  },

  // ── NEW JERSEY ──
  {
    name: "Newark Public Schools",
    slug: "newark-public-schools",
    state: "NJ",
    stateSlug: "new-jersey",
    city: "Newark",
    enrollment: 35000,
    schoolCount: 69,
  },
  {
    name: "Jersey City Public Schools",
    slug: "jersey-city-public-schools",
    state: "NJ",
    stateSlug: "new-jersey",
    city: "Jersey City",
    enrollment: 30000,
    schoolCount: 40,
  },
  {
    name: "Elizabeth Public Schools",
    slug: "elizabeth-public-schools",
    state: "NJ",
    stateSlug: "new-jersey",
    city: "Elizabeth",
    enrollment: 28000,
    schoolCount: 34,
  },
  {
    name: "Paterson Public Schools",
    slug: "paterson-public-schools",
    state: "NJ",
    stateSlug: "new-jersey",
    city: "Paterson",
    enrollment: 26000,
    schoolCount: 51,
  },
  {
    name: "Toms River Regional School District",
    slug: "toms-river-regional-school-district",
    state: "NJ",
    stateSlug: "new-jersey",
    city: "Toms River",
    enrollment: 16000,
    schoolCount: 17,
  },
  {
    name: "Camden City School District",
    slug: "camden-city-school-district",
    state: "NJ",
    stateSlug: "new-jersey",
    city: "Camden",
    enrollment: 10000,
    schoolCount: 25,
  },

  // ── NEW MEXICO ──
  {
    name: "Albuquerque Public Schools",
    slug: "albuquerque-public-schools",
    state: "NM",
    stateSlug: "new-mexico",
    city: "Albuquerque",
    enrollment: 72000,
    schoolCount: 148,
  },
  {
    name: "Las Cruces Public Schools",
    slug: "las-cruces-public-schools",
    state: "NM",
    stateSlug: "new-mexico",
    city: "Las Cruces",
    enrollment: 26000,
    schoolCount: 46,
  },
  {
    name: "Rio Rancho Public Schools",
    slug: "rio-rancho-public-schools",
    state: "NM",
    stateSlug: "new-mexico",
    city: "Rio Rancho",
    enrollment: 18000,
    schoolCount: 24,
  },

  // ── NEW YORK ──
  {
    name: "New York City Department of Education",
    slug: "new-york-city-department-of-education",
    state: "NY",
    stateSlug: "new-york",
    city: "New York City",
    enrollment: 1000000,
    schoolCount: 1700,
  },
  {
    name: "Buffalo City School District",
    slug: "buffalo-city-school-district",
    state: "NY",
    stateSlug: "new-york",
    city: "Buffalo",
    enrollment: 33000,
    schoolCount: 73,
  },
  {
    name: "Yonkers City School District",
    slug: "yonkers-city-school-district",
    state: "NY",
    stateSlug: "new-york",
    city: "Yonkers",
    enrollment: 27000,
    schoolCount: 44,
  },
  {
    name: "Rochester City School District",
    slug: "rochester-city-school-district",
    state: "NY",
    stateSlug: "new-york",
    city: "Rochester",
    enrollment: 25000,
    schoolCount: 50,
  },
  {
    name: "Syracuse City School District",
    slug: "syracuse-city-school-district",
    state: "NY",
    stateSlug: "new-york",
    city: "Syracuse",
    enrollment: 21000,
    schoolCount: 47,
  },

  // ── NORTH CAROLINA ──
  {
    name: "Charlotte-Mecklenburg Schools",
    slug: "charlotte-mecklenburg-schools",
    state: "NC",
    stateSlug: "north-carolina",
    city: "Charlotte",
    enrollment: 145000,
    schoolCount: 176,
  },
  {
    name: "Wake County Public Schools",
    slug: "wake-county-public-schools",
    state: "NC",
    stateSlug: "north-carolina",
    city: "Raleigh",
    enrollment: 160000,
    schoolCount: 193,
  },
  {
    name: "Guilford County Schools",
    slug: "guilford-county-schools",
    state: "NC",
    stateSlug: "north-carolina",
    city: "Greensboro",
    enrollment: 70000,
    schoolCount: 126,
  },
  {
    name: "Cumberland County Schools",
    slug: "cumberland-county-schools",
    state: "NC",
    stateSlug: "north-carolina",
    city: "Fayetteville",
    enrollment: 53000,
    schoolCount: 88,
  },

  // ── NORTH DAKOTA ──
  {
    name: "Fargo Public Schools",
    slug: "fargo-public-schools",
    state: "ND",
    stateSlug: "north-dakota",
    city: "Fargo",
    enrollment: 11000,
    schoolCount: 19,
  },
  {
    name: "Bismarck Public Schools",
    slug: "bismarck-public-schools",
    state: "ND",
    stateSlug: "north-dakota",
    city: "Bismarck",
    enrollment: 14500,
    schoolCount: 23,
  },

  // ── OHIO ──
  {
    name: "Columbus City Schools",
    slug: "columbus-city-schools",
    state: "OH",
    stateSlug: "ohio",
    city: "Columbus",
    enrollment: 47000,
    schoolCount: 116,
  },
  {
    name: "Cleveland Metropolitan School District",
    slug: "cleveland-metropolitan-school-district",
    state: "OH",
    stateSlug: "ohio",
    city: "Cleveland",
    enrollment: 37000,
    schoolCount: 106,
  },
  {
    name: "Cincinnati Public Schools",
    slug: "cincinnati-public-schools",
    state: "OH",
    stateSlug: "ohio",
    city: "Cincinnati",
    enrollment: 35000,
    schoolCount: 87,
  },
  {
    name: "Akron City Schools",
    slug: "akron-city-schools",
    state: "OH",
    stateSlug: "ohio",
    city: "Akron",
    enrollment: 22000,
    schoolCount: 57,
  },
  {
    name: "Toledo City School District",
    slug: "toledo-city-school-district",
    state: "OH",
    stateSlug: "ohio",
    city: "Toledo",
    enrollment: 22000,
    schoolCount: 60,
  },

  // ── OKLAHOMA ──
  {
    name: "Oklahoma City Public Schools",
    slug: "oklahoma-city-public-schools",
    state: "OK",
    stateSlug: "oklahoma",
    city: "Oklahoma City",
    enrollment: 40000,
    schoolCount: 93,
  },
  {
    name: "Tulsa Public Schools",
    slug: "tulsa-public-schools",
    state: "OK",
    stateSlug: "oklahoma",
    city: "Tulsa",
    enrollment: 35000,
    schoolCount: 86,
  },
  {
    name: "Edmond Public Schools",
    slug: "edmond-public-schools",
    state: "OK",
    stateSlug: "oklahoma",
    city: "Edmond",
    enrollment: 24000,
    schoolCount: 28,
  },

  // ── OREGON ──
  {
    name: "Portland Public Schools",
    slug: "portland-public-schools",
    state: "OR",
    stateSlug: "oregon",
    city: "Portland",
    enrollment: 47000,
    schoolCount: 84,
  },
  {
    name: "Beaverton School District",
    slug: "beaverton-school-district",
    state: "OR",
    stateSlug: "oregon",
    city: "Beaverton",
    enrollment: 40000,
    schoolCount: 55,
  },
  {
    name: "Salem-Keizer School District",
    slug: "salem-keizer-school-district",
    state: "OR",
    stateSlug: "oregon",
    city: "Salem",
    enrollment: 42000,
    schoolCount: 65,
  },
  {
    name: "Hillsboro School District",
    slug: "hillsboro-school-district",
    state: "OR",
    stateSlug: "oregon",
    city: "Hillsboro",
    enrollment: 22000,
    schoolCount: 30,
  },

  // ── PENNSYLVANIA ──
  {
    name: "Philadelphia School District",
    slug: "philadelphia-school-district",
    state: "PA",
    stateSlug: "pennsylvania",
    city: "Philadelphia",
    enrollment: 115000,
    schoolCount: 217,
  },
  {
    name: "Pittsburgh Public Schools",
    slug: "pittsburgh-public-schools",
    state: "PA",
    stateSlug: "pennsylvania",
    city: "Pittsburgh",
    enrollment: 23000,
    schoolCount: 54,
  },
  {
    name: "Allentown School District",
    slug: "allentown-school-district",
    state: "PA",
    stateSlug: "pennsylvania",
    city: "Allentown",
    enrollment: 17000,
    schoolCount: 23,
  },

  // ── RHODE ISLAND ──
  {
    name: "Providence Public Schools",
    slug: "providence-public-schools",
    state: "RI",
    stateSlug: "rhode-island",
    city: "Providence",
    enrollment: 22000,
    schoolCount: 41,
  },
  {
    name: "Cranston Public Schools",
    slug: "cranston-public-schools",
    state: "RI",
    stateSlug: "rhode-island",
    city: "Cranston",
    enrollment: 10000,
    schoolCount: 17,
  },

  // ── SOUTH CAROLINA ──
  {
    name: "Greenville County Schools",
    slug: "greenville-county-schools",
    state: "SC",
    stateSlug: "south-carolina",
    city: "Greenville",
    enrollment: 77000,
    schoolCount: 100,
  },
  {
    name: "Charleston County School District",
    slug: "charleston-county-school-district",
    state: "SC",
    stateSlug: "south-carolina",
    city: "Charleston",
    enrollment: 50000,
    schoolCount: 87,
  },
  {
    name: "Richland School District Two",
    slug: "richland-school-district-two",
    state: "SC",
    stateSlug: "south-carolina",
    city: "Columbia",
    enrollment: 28000,
    schoolCount: 36,
  },

  // ── SOUTH DAKOTA ──
  {
    name: "Sioux Falls School District",
    slug: "sioux-falls-school-district",
    state: "SD",
    stateSlug: "south-dakota",
    city: "Sioux Falls",
    enrollment: 23000,
    schoolCount: 36,
  },
  {
    name: "Rapid City Area Schools",
    slug: "rapid-city-area-schools",
    state: "SD",
    stateSlug: "south-dakota",
    city: "Rapid City",
    enrollment: 13000,
    schoolCount: 26,
  },

  // ── TENNESSEE ──
  {
    name: "Memphis-Shelby County Schools",
    slug: "memphis-shelby-county-schools",
    state: "TN",
    stateSlug: "tennessee",
    city: "Memphis",
    enrollment: 110000,
    schoolCount: 225,
  },
  {
    name: "Nashville-Davidson County Schools",
    slug: "nashville-davidson-county-schools",
    state: "TN",
    stateSlug: "tennessee",
    city: "Nashville",
    enrollment: 82000,
    schoolCount: 162,
  },
  {
    name: "Knox County Schools",
    slug: "knox-county-schools",
    state: "TN",
    stateSlug: "tennessee",
    city: "Knoxville",
    enrollment: 60000,
    schoolCount: 91,
  },
  {
    name: "Hamilton County Schools",
    slug: "hamilton-county-schools",
    state: "TN",
    stateSlug: "tennessee",
    city: "Chattanooga",
    enrollment: 45000,
    schoolCount: 80,
  },

  // ── TEXAS ──
  {
    name: "Houston Independent School District",
    slug: "houston-independent-school-district",
    state: "TX",
    stateSlug: "texas",
    city: "Houston",
    enrollment: 195000,
    schoolCount: 283,
  },
  {
    name: "Northside Independent School District",
    slug: "northside-independent-school-district",
    state: "TX",
    stateSlug: "texas",
    city: "San Antonio",
    enrollment: 105000,
    schoolCount: 122,
  },
  {
    name: "Fort Worth Independent School District",
    slug: "fort-worth-independent-school-district",
    state: "TX",
    stateSlug: "texas",
    city: "Fort Worth",
    enrollment: 80000,
    schoolCount: 147,
  },
  {
    name: "Austin Independent School District",
    slug: "austin-independent-school-district",
    state: "TX",
    stateSlug: "texas",
    city: "Austin",
    enrollment: 73000,
    schoolCount: 130,
  },
  {
    name: "Cypress-Fairbanks Independent School District",
    slug: "cypress-fairbanks-independent-school-district",
    state: "TX",
    stateSlug: "texas",
    city: "Houston",
    enrollment: 116000,
    schoolCount: 92,
  },
  {
    name: "Aldine Independent School District",
    slug: "aldine-independent-school-district",
    state: "TX",
    stateSlug: "texas",
    city: "Houston",
    enrollment: 67000,
    schoolCount: 81,
  },
  {
    name: "Dallas Independent School District",
    slug: "dallas-independent-school-district",
    state: "TX",
    stateSlug: "texas",
    city: "Dallas",
    enrollment: 145000,
    schoolCount: 230,
  },
  {
    name: "El Paso Independent School District",
    slug: "el-paso-independent-school-district",
    state: "TX",
    stateSlug: "texas",
    city: "El Paso",
    enrollment: 60000,
    schoolCount: 91,
  },
  {
    name: "San Antonio Independent School District",
    slug: "san-antonio-independent-school-district",
    state: "TX",
    stateSlug: "texas",
    city: "San Antonio",
    enrollment: 50000,
    schoolCount: 93,
  },
  {
    name: "Plano Independent School District",
    slug: "plano-independent-school-district",
    state: "TX",
    stateSlug: "texas",
    city: "Plano",
    enrollment: 54000,
    schoolCount: 72,
  },
  {
    name: "Katy Independent School District",
    slug: "katy-independent-school-district",
    state: "TX",
    stateSlug: "texas",
    city: "Katy",
    enrollment: 86000,
    schoolCount: 78,
  },
  {
    name: "Lewisville Independent School District",
    slug: "lewisville-independent-school-district",
    state: "TX",
    stateSlug: "texas",
    city: "Lewisville",
    enrollment: 53000,
    schoolCount: 68,
  },
  {
    name: "Garland Independent School District",
    slug: "garland-independent-school-district",
    state: "TX",
    stateSlug: "texas",
    city: "Garland",
    enrollment: 55000,
    schoolCount: 71,
  },
  {
    name: "Humble Independent School District",
    slug: "humble-independent-school-district",
    state: "TX",
    stateSlug: "texas",
    city: "Humble",
    enrollment: 44000,
    schoolCount: 43,
  },
  {
    name: "Spring Branch Independent School District",
    slug: "spring-branch-independent-school-district",
    state: "TX",
    stateSlug: "texas",
    city: "Houston",
    enrollment: 35000,
    schoolCount: 47,
  },
  {
    name: "Clear Creek Independent School District",
    slug: "clear-creek-independent-school-district",
    state: "TX",
    stateSlug: "texas",
    city: "League City",
    enrollment: 42000,
    schoolCount: 37,
  },

  // ── UTAH ──
  {
    name: "Granite School District",
    slug: "granite-school-district",
    state: "UT",
    stateSlug: "utah",
    city: "Salt Lake City",
    enrollment: 67000,
    schoolCount: 95,
  },
  {
    name: "Alpine School District",
    slug: "alpine-school-district",
    state: "UT",
    stateSlug: "utah",
    city: "American Fork",
    enrollment: 78000,
    schoolCount: 78,
  },
  {
    name: "Davis School District",
    slug: "davis-school-district",
    state: "UT",
    stateSlug: "utah",
    city: "Farmington",
    enrollment: 73000,
    schoolCount: 98,
  },
  {
    name: "Jordan School District",
    slug: "jordan-school-district",
    state: "UT",
    stateSlug: "utah",
    city: "Sandy",
    enrollment: 56000,
    schoolCount: 74,
  },
  {
    name: "Salt Lake City School District",
    slug: "salt-lake-city-school-district",
    state: "UT",
    stateSlug: "utah",
    city: "Salt Lake City",
    enrollment: 24000,
    schoolCount: 45,
  },

  // ── VERMONT ──
  {
    name: "Burlington School District",
    slug: "burlington-school-district",
    state: "VT",
    stateSlug: "vermont",
    city: "Burlington",
    enrollment: 4000,
    schoolCount: 9,
  },

  // ── VIRGINIA ──
  {
    name: "Fairfax County Public Schools",
    slug: "fairfax-county-public-schools",
    state: "VA",
    stateSlug: "virginia",
    city: "Falls Church",
    enrollment: 180000,
    schoolCount: 198,
  },
  {
    name: "Prince William County Public Schools",
    slug: "prince-william-county-public-schools",
    state: "VA",
    stateSlug: "virginia",
    city: "Manassas",
    enrollment: 94000,
    schoolCount: 102,
  },
  {
    name: "Virginia Beach City Public Schools",
    slug: "virginia-beach-city-public-schools",
    state: "VA",
    stateSlug: "virginia",
    city: "Virginia Beach",
    enrollment: 72000,
    schoolCount: 86,
  },
  {
    name: "Chesterfield County Public Schools",
    slug: "chesterfield-county-public-schools",
    state: "VA",
    stateSlug: "virginia",
    city: "Chesterfield",
    enrollment: 64000,
    schoolCount: 66,
  },
  {
    name: "Richmond City Public Schools",
    slug: "richmond-city-public-schools",
    state: "VA",
    stateSlug: "virginia",
    city: "Richmond",
    enrollment: 21000,
    schoolCount: 46,
  },
  {
    name: "Norfolk City Public Schools",
    slug: "norfolk-city-public-schools",
    state: "VA",
    stateSlug: "virginia",
    city: "Norfolk",
    enrollment: 30000,
    schoolCount: 58,
  },

  // ── WASHINGTON ──
  {
    name: "Seattle Public Schools",
    slug: "seattle-public-schools",
    state: "WA",
    stateSlug: "washington",
    city: "Seattle",
    enrollment: 50000,
    schoolCount: 104,
  },
  {
    name: "Northshore School District",
    slug: "northshore-school-district",
    state: "WA",
    stateSlug: "washington",
    city: "Bothell",
    enrollment: 23000,
    schoolCount: 31,
  },
  {
    name: "Lake Washington School District",
    slug: "lake-washington-school-district",
    state: "WA",
    stateSlug: "washington",
    city: "Redmond",
    enrollment: 30000,
    schoolCount: 38,
  },
  {
    name: "Bellevue School District",
    slug: "bellevue-school-district",
    state: "WA",
    stateSlug: "washington",
    city: "Bellevue",
    enrollment: 21000,
    schoolCount: 31,
  },
  {
    name: "Tacoma School District",
    slug: "tacoma-school-district",
    state: "WA",
    stateSlug: "washington",
    city: "Tacoma",
    enrollment: 29000,
    schoolCount: 57,
  },

  // ── WEST VIRGINIA ──
  {
    name: "Kanawha County Schools",
    slug: "kanawha-county-schools",
    state: "WV",
    stateSlug: "west-virginia",
    city: "Charleston",
    enrollment: 27000,
    schoolCount: 63,
  },
  {
    name: "Berkeley County Schools",
    slug: "berkeley-county-schools",
    state: "WV",
    stateSlug: "west-virginia",
    city: "Martinsburg",
    enrollment: 19000,
    schoolCount: 25,
  },

  // ── WISCONSIN ──
  {
    name: "Milwaukee Public Schools",
    slug: "milwaukee-public-schools",
    state: "WI",
    stateSlug: "wisconsin",
    city: "Milwaukee",
    enrollment: 75000,
    schoolCount: 160,
  },
  {
    name: "Madison Metropolitan School District",
    slug: "madison-metropolitan-school-district",
    state: "WI",
    stateSlug: "wisconsin",
    city: "Madison",
    enrollment: 25000,
    schoolCount: 52,
  },
  {
    name: "Green Bay Area Public Schools",
    slug: "green-bay-area-public-schools",
    state: "WI",
    stateSlug: "wisconsin",
    city: "Green Bay",
    enrollment: 20000,
    schoolCount: 40,
  },

  // ── WYOMING ──
  {
    name: "Laramie County School District 1",
    slug: "laramie-county-school-district-1",
    state: "WY",
    stateSlug: "wyoming",
    city: "Cheyenne",
    enrollment: 14000,
    schoolCount: 27,
  },
  {
    name: "Natrona County School District",
    slug: "natrona-county-school-district",
    state: "WY",
    stateSlug: "wyoming",
    city: "Casper",
    enrollment: 13000,
    schoolCount: 25,
  },
];

export function getDistrictBySlug(slug: string): SchoolDistrict | undefined {
  return districts.find((d) => d.slug === slug);
}

export function getAllDistrictSlugs(): { slug: string }[] {
  return districts.map((d) => ({ slug: d.slug }));
}

export function getDistrictsByState(stateSlug: string): SchoolDistrict[] {
  return districts.filter((d) => d.stateSlug === stateSlug);
}
