export interface USState {
  name: string;
  slug: string;
  abbr: string;
  capital: string;
  largestCity: string;
  studentCount: string;
  schoolDistrictCount: number;
  k12SchoolCount: number;
}

export const states: USState[] = [
  {
    name: "Alabama",
    slug: "alabama",
    abbr: "AL",
    capital: "Montgomery",
    largestCity: "Birmingham",
    studentCount: "720,000",
    schoolDistrictCount: 137,
    k12SchoolCount: 1498,
  },
  {
    name: "Alaska",
    slug: "alaska",
    abbr: "AK",
    capital: "Juneau",
    largestCity: "Anchorage",
    studentCount: "131,000",
    schoolDistrictCount: 54,
    k12SchoolCount: 507,
  },
  {
    name: "Arizona",
    slug: "arizona",
    abbr: "AZ",
    capital: "Phoenix",
    largestCity: "Phoenix",
    studentCount: "1,130,000",
    schoolDistrictCount: 228,
    k12SchoolCount: 2346,
  },
  {
    name: "Arkansas",
    slug: "arkansas",
    abbr: "AR",
    capital: "Little Rock",
    largestCity: "Little Rock",
    studentCount: "472,000",
    schoolDistrictCount: 238,
    k12SchoolCount: 1069,
  },
  {
    name: "California",
    slug: "california",
    abbr: "CA",
    capital: "Sacramento",
    largestCity: "Los Angeles",
    studentCount: "5,900,000",
    schoolDistrictCount: 1037,
    k12SchoolCount: 10516,
  },
  {
    name: "Colorado",
    slug: "colorado",
    abbr: "CO",
    capital: "Denver",
    largestCity: "Denver",
    studentCount: "905,000",
    schoolDistrictCount: 178,
    k12SchoolCount: 1898,
  },
  {
    name: "Connecticut",
    slug: "connecticut",
    abbr: "CT",
    capital: "Hartford",
    largestCity: "Bridgeport",
    studentCount: "530,000",
    schoolDistrictCount: 167,
    k12SchoolCount: 1097,
  },
  {
    name: "Delaware",
    slug: "delaware",
    abbr: "DE",
    capital: "Dover",
    largestCity: "Wilmington",
    studentCount: "141,000",
    schoolDistrictCount: 19,
    k12SchoolCount: 241,
  },
  {
    name: "District of Columbia",
    slug: "district-of-columbia",
    abbr: "DC",
    capital: "Washington",
    largestCity: "Washington",
    studentCount: "95,000",
    schoolDistrictCount: 1,
    k12SchoolCount: 228,
  },
  {
    name: "Florida",
    slug: "florida",
    abbr: "FL",
    capital: "Tallahassee",
    largestCity: "Jacksonville",
    studentCount: "2,910,000",
    schoolDistrictCount: 67,
    k12SchoolCount: 4241,
  },
  {
    name: "Georgia",
    slug: "georgia",
    abbr: "GA",
    capital: "Atlanta",
    largestCity: "Atlanta",
    studentCount: "1,800,000",
    schoolDistrictCount: 180,
    k12SchoolCount: 2504,
  },
  {
    name: "Hawaii",
    slug: "hawaii",
    abbr: "HI",
    capital: "Honolulu",
    largestCity: "Honolulu",
    studentCount: "175,000",
    schoolDistrictCount: 1,
    k12SchoolCount: 290,
  },
  {
    name: "Idaho",
    slug: "idaho",
    abbr: "ID",
    capital: "Boise",
    largestCity: "Boise",
    studentCount: "314,000",
    schoolDistrictCount: 115,
    k12SchoolCount: 752,
  },
  {
    name: "Illinois",
    slug: "illinois",
    abbr: "IL",
    capital: "Springfield",
    largestCity: "Chicago",
    studentCount: "1,990,000",
    schoolDistrictCount: 852,
    k12SchoolCount: 4218,
  },
  {
    name: "Indiana",
    slug: "indiana",
    abbr: "IN",
    capital: "Indianapolis",
    largestCity: "Indianapolis",
    studentCount: "1,025,000",
    schoolDistrictCount: 295,
    k12SchoolCount: 1928,
  },
  {
    name: "Iowa",
    slug: "iowa",
    abbr: "IA",
    capital: "Des Moines",
    largestCity: "Des Moines",
    studentCount: "492,000",
    schoolDistrictCount: 327,
    k12SchoolCount: 1412,
  },
  {
    name: "Kansas",
    slug: "kansas",
    abbr: "KS",
    capital: "Topeka",
    largestCity: "Wichita",
    studentCount: "491,000",
    schoolDistrictCount: 286,
    k12SchoolCount: 1311,
  },
  {
    name: "Kentucky",
    slug: "kentucky",
    abbr: "KY",
    capital: "Frankfort",
    largestCity: "Louisville",
    studentCount: "643,000",
    schoolDistrictCount: 173,
    k12SchoolCount: 1539,
  },
  {
    name: "Louisiana",
    slug: "louisiana",
    abbr: "LA",
    capital: "Baton Rouge",
    largestCity: "New Orleans",
    studentCount: "692,000",
    schoolDistrictCount: 69,
    k12SchoolCount: 1518,
  },
  {
    name: "Maine",
    slug: "maine",
    abbr: "ME",
    capital: "Augusta",
    largestCity: "Portland",
    studentCount: "173,000",
    schoolDistrictCount: 260,
    k12SchoolCount: 638,
  },
  {
    name: "Maryland",
    slug: "maryland",
    abbr: "MD",
    capital: "Annapolis",
    largestCity: "Baltimore",
    studentCount: "897,000",
    schoolDistrictCount: 24,
    k12SchoolCount: 1453,
  },
  {
    name: "Massachusetts",
    slug: "massachusetts",
    abbr: "MA",
    capital: "Boston",
    largestCity: "Boston",
    studentCount: "937,000",
    schoolDistrictCount: 408,
    k12SchoolCount: 1895,
  },
  {
    name: "Michigan",
    slug: "michigan",
    abbr: "MI",
    capital: "Lansing",
    largestCity: "Detroit",
    studentCount: "1,490,000",
    schoolDistrictCount: 842,
    k12SchoolCount: 3642,
  },
  {
    name: "Minnesota",
    slug: "minnesota",
    abbr: "MN",
    capital: "Saint Paul",
    largestCity: "Minneapolis",
    studentCount: "876,000",
    schoolDistrictCount: 333,
    k12SchoolCount: 2317,
  },
  {
    name: "Mississippi",
    slug: "mississippi",
    abbr: "MS",
    capital: "Jackson",
    largestCity: "Jackson",
    studentCount: "443,000",
    schoolDistrictCount: 147,
    k12SchoolCount: 1024,
  },
  {
    name: "Missouri",
    slug: "missouri",
    abbr: "MO",
    capital: "Jefferson City",
    largestCity: "Kansas City",
    studentCount: "872,000",
    schoolDistrictCount: 521,
    k12SchoolCount: 2391,
  },
  {
    name: "Montana",
    slug: "montana",
    abbr: "MT",
    capital: "Helena",
    largestCity: "Billings",
    studentCount: "152,000",
    schoolDistrictCount: 399,
    k12SchoolCount: 841,
  },
  {
    name: "Nebraska",
    slug: "nebraska",
    abbr: "NE",
    capital: "Lincoln",
    largestCity: "Omaha",
    studentCount: "323,000",
    schoolDistrictCount: 249,
    k12SchoolCount: 1095,
  },
  {
    name: "Nevada",
    slug: "nevada",
    abbr: "NV",
    capital: "Carson City",
    largestCity: "Las Vegas",
    studentCount: "482,000",
    schoolDistrictCount: 17,
    k12SchoolCount: 698,
  },
  {
    name: "New Hampshire",
    slug: "new-hampshire",
    abbr: "NH",
    capital: "Concord",
    largestCity: "Manchester",
    studentCount: "173,000",
    schoolDistrictCount: 176,
    k12SchoolCount: 490,
  },
  {
    name: "New Jersey",
    slug: "new-jersey",
    abbr: "NJ",
    capital: "Trenton",
    largestCity: "Newark",
    studentCount: "1,370,000",
    schoolDistrictCount: 697,
    k12SchoolCount: 2612,
  },
  {
    name: "New Mexico",
    slug: "new-mexico",
    abbr: "NM",
    capital: "Santa Fe",
    largestCity: "Albuquerque",
    studentCount: "330,000",
    schoolDistrictCount: 89,
    k12SchoolCount: 876,
  },
  {
    name: "New York",
    slug: "new-york",
    abbr: "NY",
    capital: "Albany",
    largestCity: "New York City",
    studentCount: "2,720,000",
    schoolDistrictCount: 723,
    k12SchoolCount: 4704,
  },
  {
    name: "North Carolina",
    slug: "north-carolina",
    abbr: "NC",
    capital: "Raleigh",
    largestCity: "Charlotte",
    studentCount: "1,510,000",
    schoolDistrictCount: 115,
    k12SchoolCount: 2637,
  },
  {
    name: "North Dakota",
    slug: "north-dakota",
    abbr: "ND",
    capital: "Bismarck",
    largestCity: "Fargo",
    studentCount: "112,000",
    schoolDistrictCount: 171,
    k12SchoolCount: 533,
  },
  {
    name: "Ohio",
    slug: "ohio",
    abbr: "OH",
    capital: "Columbus",
    largestCity: "Columbus",
    studentCount: "1,720,000",
    schoolDistrictCount: 614,
    k12SchoolCount: 3721,
  },
  {
    name: "Oklahoma",
    slug: "oklahoma",
    abbr: "OK",
    capital: "Oklahoma City",
    largestCity: "Oklahoma City",
    studentCount: "698,000",
    schoolDistrictCount: 521,
    k12SchoolCount: 1786,
  },
  {
    name: "Oregon",
    slug: "oregon",
    abbr: "OR",
    capital: "Salem",
    largestCity: "Portland",
    studentCount: "572,000",
    schoolDistrictCount: 197,
    k12SchoolCount: 1308,
  },
  {
    name: "Pennsylvania",
    slug: "pennsylvania",
    abbr: "PA",
    capital: "Harrisburg",
    largestCity: "Philadelphia",
    studentCount: "1,710,000",
    schoolDistrictCount: 500,
    k12SchoolCount: 3291,
  },
  {
    name: "Rhode Island",
    slug: "rhode-island",
    abbr: "RI",
    capital: "Providence",
    largestCity: "Providence",
    studentCount: "143,000",
    schoolDistrictCount: 36,
    k12SchoolCount: 311,
  },
  {
    name: "South Carolina",
    slug: "south-carolina",
    abbr: "SC",
    capital: "Columbia",
    largestCity: "Charleston",
    studentCount: "775,000",
    schoolDistrictCount: 85,
    k12SchoolCount: 1228,
  },
  {
    name: "South Dakota",
    slug: "south-dakota",
    abbr: "SD",
    capital: "Pierre",
    largestCity: "Sioux Falls",
    studentCount: "143,000",
    schoolDistrictCount: 152,
    k12SchoolCount: 718,
  },
  {
    name: "Tennessee",
    slug: "tennessee",
    abbr: "TN",
    capital: "Nashville",
    largestCity: "Memphis",
    studentCount: "1,010,000",
    schoolDistrictCount: 147,
    k12SchoolCount: 1910,
  },
  {
    name: "Texas",
    slug: "texas",
    abbr: "TX",
    capital: "Austin",
    largestCity: "Houston",
    studentCount: "5,430,000",
    schoolDistrictCount: 1028,
    k12SchoolCount: 9067,
  },
  {
    name: "Utah",
    slug: "utah",
    abbr: "UT",
    capital: "Salt Lake City",
    largestCity: "Salt Lake City",
    studentCount: "653,000",
    schoolDistrictCount: 41,
    k12SchoolCount: 1097,
  },
  {
    name: "Vermont",
    slug: "vermont",
    abbr: "VT",
    capital: "Montpelier",
    largestCity: "Burlington",
    studentCount: "81,000",
    schoolDistrictCount: 280,
    k12SchoolCount: 352,
  },
  {
    name: "Virginia",
    slug: "virginia",
    abbr: "VA",
    capital: "Richmond",
    largestCity: "Virginia Beach",
    studentCount: "1,257,000",
    schoolDistrictCount: 131,
    k12SchoolCount: 2062,
  },
  {
    name: "Washington",
    slug: "washington",
    abbr: "WA",
    capital: "Olympia",
    largestCity: "Seattle",
    studentCount: "1,105,000",
    schoolDistrictCount: 296,
    k12SchoolCount: 2616,
  },
  {
    name: "West Virginia",
    slug: "west-virginia",
    abbr: "WV",
    capital: "Charleston",
    largestCity: "Charleston",
    studentCount: "250,000",
    schoolDistrictCount: 55,
    k12SchoolCount: 701,
  },
  {
    name: "Wisconsin",
    slug: "wisconsin",
    abbr: "WI",
    capital: "Madison",
    largestCity: "Milwaukee",
    studentCount: "853,000",
    schoolDistrictCount: 421,
    k12SchoolCount: 2348,
  },
  {
    name: "Wyoming",
    slug: "wyoming",
    abbr: "WY",
    capital: "Cheyenne",
    largestCity: "Cheyenne",
    studentCount: "93,000",
    schoolDistrictCount: 48,
    k12SchoolCount: 382,
  },
];

export function getStateBySlug(slug: string): USState | undefined {
  return states.find((s) => s.slug === slug);
}

export function getAllStateSlugs(): { state: string }[] {
  return states.map((s) => ({ state: s.slug }));
}
