import Link from "next/link";

export default function Footer() {
  return (
    <footer className="border-t border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-950 mt-20">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 py-12">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-8 mb-10">
          <div>
            <p className="text-xs font-semibold uppercase tracking-widest text-slate-400 mb-3">Students</p>
            <ul className="space-y-2 text-sm text-slate-500 dark:text-slate-400">
              <li><Link href="/features/ai-syllabus-scan" className="hover:text-violet-brand">AI Syllabus Scan</Link></li>
              <li><Link href="/features/burnout-radar" className="hover:text-violet-brand">Burnout Radar™</Link></li>
              <li><Link href="/features/club-os" className="hover:text-violet-brand">Club OS</Link></li>
              <li><Link href="/features/portfolio" className="hover:text-violet-brand">4-Year Portfolio</Link></li>
            </ul>
          </div>
          <div>
            <p className="text-xs font-semibold uppercase tracking-widest text-slate-400 mb-3">Teachers</p>
            <ul className="space-y-2 text-sm text-slate-500 dark:text-slate-400">
              <li><Link href="/features/syllabus-builder" className="hover:text-violet-brand">AI Syllabus Builder</Link></li>
              <li><Link href="/features/lesson-planner" className="hover:text-violet-brand">AI Lesson Planner</Link></li>
              <li><Link href="/features/class-code" className="hover:text-violet-brand">Class Code Import</Link></li>
              <li><Link href="/features/lms-export" className="hover:text-violet-brand">LMS Export</Link></li>
            </ul>
          </div>
          <div>
            <p className="text-xs font-semibold uppercase tracking-widest text-slate-400 mb-3">Resources</p>
            <ul className="space-y-2 text-sm text-slate-500 dark:text-slate-400">
              <li><Link href="/blog" className="hover:text-violet-brand">Blog</Link></li>
              <li><Link href="/templates" className="hover:text-violet-brand">Syllabus Templates</Link></li>
              <li><Link href="/glossary" className="hover:text-violet-brand">Glossary</Link></li>
              <li><Link href="/compare/magicschool-ai" className="hover:text-violet-brand">vs MagicSchool AI</Link></li>
            </ul>
          </div>
          <div>
            <p className="text-xs font-semibold uppercase tracking-widest text-slate-400 mb-3">Company</p>
            <ul className="space-y-2 text-sm text-slate-500 dark:text-slate-400">
              <li><Link href="/pricing" className="hover:text-violet-brand">Pricing</Link></li>
              <li><Link href="/about" className="hover:text-violet-brand">About</Link></li>
              <li><Link href="/contact" className="hover:text-violet-brand">Contact</Link></li>
              <li><Link href="/privacy" className="hover:text-violet-brand">Privacy</Link></li>
              <li><Link href="/terms" className="hover:text-violet-brand">Terms</Link></li>
            </ul>
          </div>
        </div>
        <div className="border-t border-slate-100 dark:border-slate-800 pt-6">
          <p className="text-xs text-slate-400 leading-relaxed max-w-3xl">
            <strong className="text-slate-500">Disclaimer:</strong> Syllio is a student and educator productivity tool.
            Content generated by Syllio, including syllabi, lesson plans, course outlines, and study schedules,
            is for organizational purposes only and does not constitute official academic guidance, professional
            advice, or any form of legal, medical, or financial counsel. Always refer to your institution&apos;s
            official course requirements, academic policies, and advisor for authoritative information.
          </p>
          <p className="text-xs text-slate-400 mt-4">© {new Date().getFullYear()} Syllio. All rights reserved.</p>
        </div>
      </div>
    </footer>
  );
}
